--create or replace view f_loads as
select
  sys_context('USERENV','SERVICE_NAME') DB_Service_Name,
  a.lastupdate Modification_Time,
  a.loadno Unique_Key1,
  a.loadno as load_number,
  a.entrydate as entry_date,
  a.apptdate as appointment_date,
  a.rcvddate as received_date,
  a.billdate as billed_date,
  a.loadstatus as status,
  b.abbrev as status_desc,
  a.loadtype as load_type,
  c.abbrev as load_type_desc,
  a.shiptype as shipment_type,
  d.abbrev as shipment_type_desc,
  a.shipterms as shipment_terms,
  e.abbrev as shipment_terms_desc,
  a.trailer,
  a.seal,
  a.facility,
  a.doorloc as door_location,
  a.stageloc as stage_location,
  a.carrier,
  a.qtyorder as qty_order,
  a.weightorder as weight_order,
  a.qtyship as qty_shipped,
  a.weightship as weight_shipped,
  a.qtyrcvd as qty_received,
  a.weightrcvd as weight_received,
  a.lastuser as last_update_user,
  a.lastupdate as last_update_time
from alps.loads a, alps.loadstatus b, alps.loadtypes c,
  alps.shipmenttypes d, alps.shipmentterms e
where a.loadstatus = b.code(+) and a.loadtype = c.code(+)
  and a.shiptype = d.code(+) and a.shipterms = e.code(+);