--create or replace view f_order_header as 
select 
  sys_context('USERENV','SERVICE_NAME') DB_Service_Name,
  a.lastupdate Modification_Time,
  a.orderid Unique_Key1,
  a.shipid Unique_Key2,
  orderid,
  shipid,
  custid as customer,
  fromfacility from_facility,
  tofacility to_facility,
  ordertype as order_type,
  d.abbrev as order_type_desc,
  po,
  reference,
  orderstatus order_status,
  b.abbrev as order_status_desc,
  commitstatus as commit_status,
  c.abbrev as commit_status_desc,
  priority as order_priority,
  e.abbrev as order_priority_desc,
  a.shiptype as shipment_type,
  f.abbrev as shipment_type_desc,
  a.shipterms as shipment_terms,
  i.abbrev as shipment_terms_desc,
  carrier,
  shipper,
  shipto_master as ship_to_master,
  a.shipto as ship_to,
  nvl(g.name, a.shiptoname) as ship_to_name,
  nvl(g.contact, a.shiptocontact) as ship_to_contact,
  nvl(g.addr1, a.shiptoaddr1) as ship_to_address_1,
  nvl(g.addr2, a.shiptoaddr2) as ship_to_address_2,
  nvl(g.city, a.shiptocity) as ship_to_city,
  nvl(g.state, a.shiptostate) as ship_to_state,
  nvl(g.postalcode, a.shiptopostalcode) as ship_to_zip_code,
  nvl(g.countrycode, a.shiptocountrycode) as ship_to_country,
  nvl(g.phone, a.shiptophone) as ship_to_phone,
  nvl(g.fax, a.shiptofax) as ship_to_fax,
  nvl(g.email, a.shiptoemail) as ship_to_email,
  a.consignee,
  nvl(h.name, a.billtoname) as bill_to_name,
  nvl(h.contact, a.billtocontact) as bill_to_contact,
  nvl(h.addr1, a.billtoaddr1) as bill_to_address_1,
  nvl(h.addr2, a.billtoaddr2) as bill_to_address_2,
  nvl(h.city, a.billtocity) as bill_to_city,
  nvl(h.state, a.billtostate) as bill_to_state,
  nvl(h.postalcode, a.billtopostalcode) as bill_to_zip_code,
  nvl(h.countrycode, a.billtocountrycode) as bill_to_country,
  nvl(h.phone, a.billtophone) as bill_to_phone,
  nvl(h.fax, a.billtofax) as bill_to_fax,
  nvl(h.email, a.billtoemail) as bill_to_email,
  loadno as load_number,
  stopno as load_stop_number,
  shipno as load_stop_ship_number,
  entrydate as entry_date,
  apptdate as appointment_date,
  shipdate as shipment_date,
  qtyorder as qty_order,
  weightorder as weight_order,
  qtycommit as qty_commit,
  weightcommit as weight_commit,
  qtyship as qty_ship,
  weightship as weight_ship,
  qtyrcvd as qty_received,
  weightrcvd as weight_received,
  hdrpassthrudate01 as pt_date_01,
  hdrpassthrudate02 as pt_date_02,
  hdrpassthrudate03 as pt_date_03,
  hdrpassthrudate04 as pt_date_04,
  hdrpassthrudoll01 as pt_dollar_01,
  hdrpassthrudoll02 as pt_dollar_02,
  hdrpassthruchar01 as pt_character_01,
  hdrpassthruchar02 as pt_character_02,
  hdrpassthruchar03 as pt_character_03,
  hdrpassthruchar04 as pt_character_04,
  hdrpassthruchar05 as pt_character_05,
  hdrpassthruchar06 as pt_character_06,
  hdrpassthruchar07 as pt_character_07,
  hdrpassthruchar08 as pt_character_08,
  hdrpassthruchar09 as pt_character_09,
  hdrpassthruchar10 as pt_character_10,
  hdrpassthruchar11 as pt_character_11,
  hdrpassthruchar12 as pt_character_12,
  hdrpassthruchar13 as pt_character_13,
  hdrpassthruchar14 as pt_character_14,
  hdrpassthruchar15 as pt_character_15,
  hdrpassthruchar16 as pt_character_16,
  hdrpassthruchar17 as pt_character_17,
  hdrpassthruchar18 as pt_character_18,
  hdrpassthruchar19 as pt_character_19,
  hdrpassthruchar20 as pt_character_20,
  hdrpassthruchar21 as pt_character_21,
  hdrpassthruchar22 as pt_character_22,
  hdrpassthruchar23 as pt_character_23,
  hdrpassthruchar24 as pt_character_24,
  hdrpassthruchar25 as pt_character_25,
  hdrpassthruchar26 as pt_character_26,
  hdrpassthruchar27 as pt_character_27,
  hdrpassthruchar28 as pt_character_28,
  hdrpassthruchar29 as pt_character_29,
  hdrpassthruchar30 as pt_character_30,
  hdrpassthruchar31 as pt_character_31,
  hdrpassthruchar32 as pt_character_32,
  hdrpassthruchar33 as pt_character_33,
  hdrpassthruchar34 as pt_character_34,
  hdrpassthruchar35 as pt_character_35,
  hdrpassthruchar36 as pt_character_36,
  hdrpassthruchar37 as pt_character_37,
  hdrpassthruchar38 as pt_character_38,
  hdrpassthruchar39 as pt_character_39,
  hdrpassthruchar40 as pt_character_40, 
  hdrpassthruchar41 as pt_character_41,
  hdrpassthruchar42 as pt_character_42,
  hdrpassthruchar43 as pt_character_43,
  hdrpassthruchar44 as pt_character_44,
  hdrpassthruchar45 as pt_character_45,
  hdrpassthruchar46 as pt_character_46,
  hdrpassthruchar47 as pt_character_47,
  hdrpassthruchar48 as pt_character_48,
  hdrpassthruchar49 as pt_character_49,
  hdrpassthruchar50 as pt_character_50,
  hdrpassthruchar51 as pt_character_51,
  hdrpassthruchar52 as pt_character_52,
  hdrpassthruchar53 as pt_character_53,
  hdrpassthruchar54 as pt_character_54,
  hdrpassthruchar55 as pt_character_55,
  hdrpassthruchar56 as pt_character_56,
  hdrpassthruchar57 as pt_character_57,
  hdrpassthruchar58 as pt_character_58,
  hdrpassthruchar59 as pt_character_59,
  hdrpassthruchar60 as pt_character_60, 
  hdrpassthrunum01 as pt_number_01,
  hdrpassthrunum02 as pt_number_02,
  hdrpassthrunum03 as pt_number_03,
  hdrpassthrunum04 as pt_number_04,
  hdrpassthrunum05 as pt_number_05,
  hdrpassthrunum06 as pt_number_06,
  hdrpassthrunum07 as pt_number_07,
  hdrpassthrunum08 as pt_number_08,
  hdrpassthrunum09 as pt_number_09,
  hdrpassthrunum10 as pt_number_10,
  a.statusupdate status_update_time,
  a.statususer status_update_user,
  a.lastupdate last_update_time,
  a.lastuser last_update_user
from alps.orderhdr a, alps.orderstatus b, alps.commitstatus c, alps.ordertypes d, alps.orderpriority e,
  alps.shipmenttypes f, alps.consigneeview g, alps.consigneeview h, alps.shipmentterms i
where a.orderstatus = b.code(+)
  and a.commitstatus = c.code(+)
  and a.ordertype = d.code(+)
  and a.priority = e.code(+)
  and a.shiptype = f.code(+)
  and a.shipto = g.consignee(+)
  and a.consignee = h.consignee(+)
  and a.shipterms = i.code(+);

  