--create or replace view f_shippingplate as
select
  sys_context('USERENV','SERVICE_NAME') DB_Service_Name,
  a.lastupdate Modification_Time,
  a.lpid Unique_Key1,
  a.lpid,
  a.parentlpid as parent_lpid,
  a.fromlpid as from_lpid,
  a.facility,
  a.custid as customer,
  a.item,
  a.lotnumber as lot_number,
  a.orderitem as ordered_item,
  a.orderlot as ordered_lot_number,
  a.location,
  a.pickedfromloc as picked_from_location,
  a.unitofmeasure as unit_of_measure,
  a.quantity,
  a.pickuom as pick_unit_of_measure,
  a.pickqty as pick_quantity,
  a.uomentered as entered_unit_of_measure,
  a.qtyentered as entered_quantity,
  a.status,
  b.abbrev as status_desc,
  a.type,
  d.abbrev as type_desc,
  a.inventoryclass as inventory_class,
  e.abbrev as inventory_class_desc,
  a.invstatus as inventory_status,
  f.abbrev as inventory_status_desc,
  a.holdreason as hold_reason,
  c.abbrev as hold_reason_desc,
  a.serialnumber as serial_number,
  a.useritem1 as user_item_1,
  a.useritem2 as user_item_2,
  a.useritem3 as user_item_3,
  a.trackingno as tracking_number,
  a.cartontype as carton_type,
  g.abbrev as carton_type_desc,
  g.length as carton_length,
  g.width as carton_width,
  g.height as carton_height,
  g.container_weight as carton_container_weight,
  a.loadno as load_number,
  a.stopno as load_stop_number,
  a.shipno as load_stop_ship_number,
  a.orderid,
  a.shipid,
  a.weight,
  a.length,
  a.width,
  a.height,
  a.lastuser as last_update_user,
  a.lastupdate as last_update_time
from alps.shippingplate a, alps.shippingplatestatus b, alps.holdreasons c,
  alps.shippingplatetypes d, alps.inventoryclass e, alps.inventorystatus f,
  alps.cartontypes g
where a.status = b.code(+) and a.holdreason = c.code(+) and a.type = d.code(+)
  and a.inventoryclass = e.code(+) and a.invstatus = f.code(+)
  and a.cartontype = g.code(+);