CREATE INDEX LOADS_TMS_SHIPMENT_ID_IDX ON LOADS(TMS_SHIPMENT_ID) tablespace users16kb;
CREATE INDEX PLATE_TYPE_IDX ON PLATE(TYPE) tablespace users16kb;
CREATE INDEX CONSIGNEE_STORECODE ON CONSIGNEE(SUBSTR(CONSIGNEE,1,4), STORECODE) tablespace users16kb;
CREATE INDEX WEBER_CASE_LABELS_LPIDX ON WEBER_CASE_LABELS(LPID) tablespace users16kb;
CREATE INDEX WEBER_PALLET_LABELS_LPIDX ON WEBER_PALLET_LABELS(LPID) tablespace users16kb;
exit;
