--
-- $Id$
--
create or replace package alps.pkg_manage_orders as
                                               

procedure usp_insert_orderhdr
(  order_type VARCHAR2,
   cust_id VARCHAR2,
   po VARCHAR2, 
   priority VARCHAR2,    
   from_facilty VARCHAR2,
   to_facility VARCHAR2,
   ship_to_name VARCHAR2,
   ship_to_contact VARCHAR2,
   ship_to_addr1 VARCHAR2,
   ship_to_addr2 VARCHAR2,
   ship_to_city VARCHAR2,
   ship_to_state VARCHAR2,
   ship_to_postal_code VARCHAR2,
   ship_to_country_code VARCHAR2,
   ship_to_phone VARCHAR2,
   ship_to_fax VARCHAR2,
   ship_to_email VARCHAR2,
   bill_to_name VARCHAR2,
   bill_to_contact VARCHAR2,
   bill_to_addr1 VARCHAR2,
   bill_to_addr2 VARCHAR2,
   bill_to_city VARCHAR2,
   bill_to_state VARCHAR2,
   bill_to_postal_code VARCHAR2,
   bill_to_country_code VARCHAR2,
   bill_to_phone VARCHAR2,
   bill_to_fax VARCHAR2,
   bill_to_email VARCHAR2,
   arrival_date DATE,
   ship_type VARCHAR2,
   carrier VARCHAR2,
   reference VARCHAR2,
   ship_terms VARCHAR2,
   saturday_delivery CHAR,
   apptdate DATE, 
   shipdate DATE,
   ship_to VARCHAR2,
   consignee VARCHAR2,
   last_user VARCHAR2,
   status_user VARCHAR2, 
   billoflading VARCHAR2,
   comment1 CLOB,
   bolcomments CLOB,
   delivery_service VARCHAR2,
   in_shipper VARCHAR2,
   in_expanded_fields CHAR,
    return_status OUT NUMBER,
   return_msg OUT VARCHAR2,
   return_order_id OUT NUMBER 
);

procedure usp_update_orderhdr
(  in_order_type VARCHAR2,
   in_cust_id VARCHAR2,
   in_po VARCHAR2, 
   in_priority VARCHAR2,    
   in_from_facilty VARCHAR2,
   in_to_facility VARCHAR2,
   in_ship_to_name VARCHAR2,
   in_ship_to_contact VARCHAR2,
   in_ship_to_addr1 VARCHAR2,
   in_ship_to_addr2 VARCHAR2,
   in_ship_to_city VARCHAR2,
   in_ship_to_state VARCHAR2,
   in_ship_to_postal_code VARCHAR2,
   in_ship_to_country_code VARCHAR2,
   in_ship_to_phone VARCHAR2,
   in_ship_to_fax VARCHAR2,
   in_ship_to_email VARCHAR2,
   in_bill_to_name VARCHAR2,
   in_bill_to_contact VARCHAR2,
   in_bill_to_addr1 VARCHAR2, 
   in_bill_to_addr2 VARCHAR2,
   in_bill_to_city VARCHAR2,
   in_bill_to_state VARCHAR2,
   in_bill_to_postal_code VARCHAR2,
   in_bill_to_country_code VARCHAR2,
   in_bill_to_phone VARCHAR2,
   in_bill_to_fax VARCHAR2,
   in_bill_to_email VARCHAR2,
   in_arrival_date DATE,
   in_ship_type VARCHAR2,
   in_carrier VARCHAR2,
   in_reference VARCHAR2,
   in_ship_terms VARCHAR2,
   in_saturday_delivery CHAR,
   in_apptdate DATE, 
   in_shipdate DATE,
   in_ship_to VARCHAR2,
   in_consignee VARCHAR2,
   in_last_user VARCHAR2,
   in_status_user VARCHAR2,
   in_billoflading VARCHAR2,
   in_comment1 CLOB,   
   in_bolcomments CLOB,
   in_delivery_service VARCHAR2,
   in_shipper VARCHAR2,
   in_expanded_fields CHAR,
   in_orderid NUMBER,
   in_shipid NUMBER,
   return_status OUT NUMBER,
   return_msg OUT VARCHAR2
);

procedure usp_update_orderhdr_passthrus
(  in_orderid NUMBER,
   in_shipid NUMBER,
   in_hdrpassthruchar01 VARCHAR2,
   in_hdrpassthruchar02 VARCHAR2,
   in_hdrpassthruchar03 VARCHAR2,
   in_hdrpassthruchar04 VARCHAR2,
   in_hdrpassthruchar05 VARCHAR2,
   in_hdrpassthruchar06 VARCHAR2,
   in_hdrpassthruchar07 VARCHAR2,
   in_hdrpassthruchar08 VARCHAR2,
   in_hdrpassthruchar09 VARCHAR2,
   in_hdrpassthruchar10 VARCHAR2,
   in_hdrpassthruchar11 VARCHAR2,
   in_hdrpassthruchar12 VARCHAR2,
   in_hdrpassthruchar13 VARCHAR2,
   in_hdrpassthruchar14 VARCHAR2,
   in_hdrpassthruchar15 VARCHAR2,
   in_hdrpassthruchar16 VARCHAR2,
   in_hdrpassthruchar17 VARCHAR2,
   in_hdrpassthruchar18 VARCHAR2,
   in_hdrpassthruchar19 VARCHAR2,
   in_hdrpassthruchar20 VARCHAR2,
   in_hdrpassthruchar21 VARCHAR2,
   in_hdrpassthruchar22 VARCHAR2,
   in_hdrpassthruchar23 VARCHAR2,
   in_hdrpassthruchar24 VARCHAR2,
   in_hdrpassthruchar25 VARCHAR2,
   in_hdrpassthruchar26 VARCHAR2,
   in_hdrpassthruchar27 VARCHAR2,
   in_hdrpassthruchar28 VARCHAR2,
   in_hdrpassthruchar29 VARCHAR2,
   in_hdrpassthruchar30 VARCHAR2,
   in_hdrpassthruchar31 VARCHAR2,
   in_hdrpassthruchar32 VARCHAR2,
   in_hdrpassthruchar33 VARCHAR2,
   in_hdrpassthruchar34 VARCHAR2,
   in_hdrpassthruchar35 VARCHAR2,
   in_hdrpassthruchar36 VARCHAR2,
   in_hdrpassthruchar37 VARCHAR2,
   in_hdrpassthruchar38 VARCHAR2,
   in_hdrpassthruchar39 VARCHAR2,
   in_hdrpassthruchar40 VARCHAR2,
   in_hdrpassthruchar41 VARCHAR2,
   in_hdrpassthruchar42 VARCHAR2,
   in_hdrpassthruchar43 VARCHAR2,
   in_hdrpassthruchar44 VARCHAR2,
   in_hdrpassthruchar45 VARCHAR2,
   in_hdrpassthruchar46 VARCHAR2,
   in_hdrpassthruchar47 VARCHAR2,
   in_hdrpassthruchar48 VARCHAR2,
   in_hdrpassthruchar49 VARCHAR2,
   in_hdrpassthruchar50 VARCHAR2,
   in_hdrpassthruchar51 VARCHAR2,
   in_hdrpassthruchar52 VARCHAR2,
   in_hdrpassthruchar53 VARCHAR2,
   in_hdrpassthruchar54 VARCHAR2,
   in_hdrpassthruchar55 VARCHAR2,
   in_hdrpassthruchar56 VARCHAR2,
   in_hdrpassthruchar57 VARCHAR2,
   in_hdrpassthruchar58 VARCHAR2,
   in_hdrpassthruchar59 VARCHAR2,
   in_hdrpassthruchar60 VARCHAR2,
   in_hdrpassthrudate01 VARCHAR2,
   in_hdrpassthrudate02 VARCHAR2,
   in_hdrpassthrudate03 VARCHAR2,
   in_hdrpassthrudate04 VARCHAR2,
   in_hdrpassthrudoll01 VARCHAR2,
   in_hdrpassthrudoll02 VARCHAR2,
   in_hdrpassthrunum01 VARCHAR2,
   in_hdrpassthrunum02 VARCHAR2,
   in_hdrpassthrunum03 VARCHAR2,
   in_hdrpassthrunum04 VARCHAR2,
   in_hdrpassthrunum05 VARCHAR2,
   in_hdrpassthrunum06 VARCHAR2,
   in_hdrpassthrunum07 VARCHAR2,
   in_hdrpassthrunum08 VARCHAR2,
   in_hdrpassthrunum09 VARCHAR2,
   in_hdrpassthrunum10 VARCHAR2,
   in_cancelAfterDate VARCHAR2,
   in_deliveryrequesteddate VARCHAR2,
   in_requestedshipdate VARCHAR2,
   in_shipnotbeforedate VARCHAR2,
   in_shipnolaterdate VARCHAR2,
   in_cancelifnotdeliveredbydate VARCHAR2,
   in_donotdeliverafterdate VARCHAR2,
   in_donotdeliverbeforedate VARCHAR2,
   in_lastuser VARCHAR2,
   return_status OUT NUMBER,
   return_msg OUT VARCHAR2
);

procedure usp_insert_lineitems
(  
   from_facility VARCHAR2,
   order_id NUMBER, 
	ship_id NUMBER,
   cust_id VARCHAR2,
   in_item VARCHAR2,   
   qty_order NUMBER,
   qty_entered NUMBER,   
   --item_descr String, 
   --weight_order NUMBER,
   --cube_order NUMBER,
   lot_number VARCHAR2,
   last_user VARCHAR2,
   item_entered VARCHAR2,
   uom_entered VARCHAR2,
   in_comment1 CLOB,
   in_consigneesku VARCHAR2,   
   return_status OUT NUMBER,
   return_msg OUT VARCHAR2
   --return_order_id OUT NUMBER
);

procedure usp_update_orderdtl
(  
   order_id NUMBER, 
   ship_id NUMBER,
   cust_id VARCHAR2,
   in_item VARCHAR2,   
   qty_order NUMBER,
   qty_entered NUMBER,   
   lot_number VARCHAR2,
   last_user VARCHAR2,
   uom_entered VARCHAR2,
   in_comment1 CLOB,
   in_consigneesku VARCHAR2,   
   return_status OUT NUMBER,
   return_msg OUT VARCHAR2
);

procedure usp_update_orderdtl_passthrus
(  in_orderid NUMBER,
   in_shipid NUMBER,
   in_item VARCHAR2,   
   in_lotnumber VARCHAR2,
   in_dtlpassthruchar01 VARCHAR2,
   in_dtlpassthruchar02 VARCHAR2,
   in_dtlpassthruchar03 VARCHAR2,
   in_dtlpassthruchar04 VARCHAR2,
   in_dtlpassthruchar05 VARCHAR2,
   in_dtlpassthruchar06 VARCHAR2,
   in_dtlpassthruchar07 VARCHAR2,
   in_dtlpassthruchar08 VARCHAR2,
   in_dtlpassthruchar09 VARCHAR2,
   in_dtlpassthruchar10 VARCHAR2,
   in_dtlpassthruchar11 VARCHAR2,
   in_dtlpassthruchar12 VARCHAR2,
   in_dtlpassthruchar13 VARCHAR2,
   in_dtlpassthruchar14 VARCHAR2,
   in_dtlpassthruchar15 VARCHAR2,
   in_dtlpassthruchar16 VARCHAR2,
   in_dtlpassthruchar17 VARCHAR2,
   in_dtlpassthruchar18 VARCHAR2,
   in_dtlpassthruchar19 VARCHAR2,
   in_dtlpassthruchar20 VARCHAR2,
   in_dtlpassthruchar21 VARCHAR2,
   in_dtlpassthruchar22 VARCHAR2,
   in_dtlpassthruchar23 VARCHAR2,
   in_dtlpassthruchar24 VARCHAR2,
   in_dtlpassthruchar25 VARCHAR2,
   in_dtlpassthruchar26 VARCHAR2,
   in_dtlpassthruchar27 VARCHAR2,
   in_dtlpassthruchar28 VARCHAR2,
   in_dtlpassthruchar29 VARCHAR2,
   in_dtlpassthruchar30 VARCHAR2,
   in_dtlpassthruchar31 VARCHAR2,
   in_dtlpassthruchar32 VARCHAR2,
   in_dtlpassthruchar33 VARCHAR2,
   in_dtlpassthruchar34 VARCHAR2,
   in_dtlpassthruchar35 VARCHAR2,
   in_dtlpassthruchar36 VARCHAR2,
   in_dtlpassthruchar37 VARCHAR2,
   in_dtlpassthruchar38 VARCHAR2,
   in_dtlpassthruchar39 VARCHAR2,
   in_dtlpassthruchar40 VARCHAR2,
   in_dtlpassthrudate01 VARCHAR2,
   in_dtlpassthrudate02 VARCHAR2,
   in_dtlpassthrudate03 VARCHAR2,
   in_dtlpassthrudate04 VARCHAR2,
   in_dtlpassthrudoll01 VARCHAR2,
   in_dtlpassthrudoll02 VARCHAR2,
   in_dtlpassthrunum01 VARCHAR2,
   in_dtlpassthrunum02 VARCHAR2,
   in_dtlpassthrunum03 VARCHAR2,
   in_dtlpassthrunum04 VARCHAR2,
   in_dtlpassthrunum05 VARCHAR2,
   in_dtlpassthrunum06 VARCHAR2,
   in_dtlpassthrunum07 VARCHAR2,
   in_dtlpassthrunum08 VARCHAR2,
   in_dtlpassthrunum09 VARCHAR2,
   in_dtlpassthrunum10 VARCHAR2,
   in_dtlpassthrunum11 VARCHAR2,
   in_dtlpassthrunum12 VARCHAR2,
   in_dtlpassthrunum13 VARCHAR2,
   in_dtlpassthrunum14 VARCHAR2,
   in_dtlpassthrunum15 VARCHAR2,
   in_dtlpassthrunum16 VARCHAR2,
   in_dtlpassthrunum17 VARCHAR2,
   in_dtlpassthrunum18 VARCHAR2,
   in_dtlpassthrunum19 VARCHAR2,
   in_dtlpassthrunum20 VARCHAR2,
   in_lastuser VARCHAR2,
   return_status OUT NUMBER,
   return_msg OUT VARCHAR2
);

procedure usp_delete_lineitems
(     
   order_id NUMBER, 
	ship_id NUMBER,
   item VARCHAR2,
   return_status OUT NUMBER,
   return_msg OUT VARCHAR2
);

function item_alias
(in_custid varchar2,
in_item varchar2
) return varchar2;

PRAGMA RESTRICT_REFERENCES (item_alias,WNDS,WNPS,RNPS);

      
end pkg_manage_orders;   

/
exit;
