drop table pklrequest_header;

create table pklrequest_header
(pklsessionid  number(7)
,ORDERID NUMBER(9)
,SHIPID NUMBER(2)
,CUSTID VARCHAR2(10)
,ORDERTYPE VARCHAR2(1)
,ENTRYDATE DATE
,APPTDATE DATE
,SHIPDATE DATE
,PO VARCHAR2(20)
,RMA VARCHAR2(20)
,ORDERSTATUS VARCHAR2(1)
,COMMITSTATUS VARCHAR2(1)
,FROMFACILITY VARCHAR2(3)
,TOFACILITY VARCHAR2(3)
,LOADNO NUMBER(7)
,STOPNO NUMBER(7)
,SHIPNO NUMBER(7)
,SHIPTO VARCHAR2(10)
,DELAREA VARCHAR2(3)
,QTYORDER NUMBER(7)
,WEIGHTORDER NUMBER(17,8)
,CUBEORDER NUMBER(10,4)
,AMTORDER NUMBER(10,2)
,QTYCOMMIT NUMBER(7)
,WEIGHTCOMMIT NUMBER(17,8)
,CUBECOMMIT NUMBER(10,4)
,AMTCOMMIT NUMBER(10,2)
,QTYSHIP NUMBER(7)
,WEIGHTSHIP NUMBER(17,8)
,CUBESHIP NUMBER(10,4)
,AMTSHIP NUMBER(10,2)
,QTYTOTCOMMIT NUMBER(7)
,WEIGHTTOTCOMMIT NUMBER(17,8)
,CUBETOTCOMMIT NUMBER(10,4)
,AMTTOTCOMMIT NUMBER(10,2)
,QTYRCVD NUMBER(7)
,WEIGHTRCVD NUMBER(17,8)
,CUBERCVD NUMBER(10,4)
,AMTRCVD NUMBER(10,2)
,COMMENT1 CLOB
,STATUSUSER VARCHAR2(12)
,STATUSUPDATE DATE
,LASTUSER VARCHAR2(12)
,LASTUPDATE DATE
,BILLOFLADING VARCHAR2(40)
,PRIORITY VARCHAR2(1)
,SHIPPER VARCHAR2(10)
,ARRIVALDATE DATE
,CONSIGNEE VARCHAR2(10)
,SHIPTYPE VARCHAR2(1)
,CARRIER VARCHAR2(10)
,REFERENCE VARCHAR2(20)
,SHIPTERMS VARCHAR2(3)
,WAVE NUMBER(9)
,STAGELOC VARCHAR2(10)
,QTYPICK NUMBER(7)
,WEIGHTPICK NUMBER(17,8)
,CUBEPICK NUMBER(10,4)
,AMTPICK NUMBER(10,2)
,SHIPTONAME VARCHAR2(40)
,SHIPTOCONTACT VARCHAR2(40)
,SHIPTOADDR1 VARCHAR2(40)
,SHIPTOADDR2 VARCHAR2(40)
,SHIPTOCITY VARCHAR2(30)
,SHIPTOSTATE VARCHAR2(5)
,SHIPTOPOSTALCODE VARCHAR2(12)
,SHIPTOCOUNTRYCODE VARCHAR2(3)
,SHIPTOPHONE VARCHAR2(25)
,SHIPTOFAX VARCHAR2(25)
,SHIPTOEMAIL VARCHAR2(255)
,BILLTONAME VARCHAR2(40)
,BILLTOCONTACT VARCHAR2(40)
,BILLTOADDR1 VARCHAR2(40)
,BILLTOADDR2 VARCHAR2(40)
,BILLTOCITY VARCHAR2(30)
,BILLTOSTATE VARCHAR2(5)
,BILLTOPOSTALCODE VARCHAR2(12)
,BILLTOCOUNTRYCODE VARCHAR2(3)
,BILLTOPHONE VARCHAR2(25)
,BILLTOFAX VARCHAR2(25)
,BILLTOEMAIL VARCHAR2(255)
,PARENTORDERID NUMBER(9)
,PARENTSHIPID NUMBER(2)
,PARENTORDERitem varchar2(50)
,PARENTORDERLOT VARCHAR2(30)
,WORKORDERSEQ NUMBER(8)
,STAFFHRS NUMBER(10,4)
,QTY2SORT NUMBER(7)
,WEIGHT2SORT NUMBER(17,8)
,CUBE2SORT NUMBER(10,4)
,AMT2SORT NUMBER(10,2)
,QTY2PACK NUMBER(7)
,WEIGHT2PACK NUMBER(17,8)
,CUBE2PACK NUMBER(10,4)
,AMT2PACK NUMBER(10,2)
,QTY2CHECK NUMBER(7)
,WEIGHT2CHECK NUMBER(17,8)
,CUBE2CHECK NUMBER(10,4)
,AMT2CHECK NUMBER(10,2)
,IMPORTFILEID VARCHAR2(255)
,HDRPASSTHRUCHAR01 VARCHAR2(255)
,HDRPASSTHRUCHAR02 VARCHAR2(255)
,HDRPASSTHRUCHAR03 VARCHAR2(255)
,HDRPASSTHRUCHAR04 VARCHAR2(255)
,HDRPASSTHRUCHAR05 VARCHAR2(255)
,HDRPASSTHRUCHAR06 VARCHAR2(255)
,HDRPASSTHRUCHAR07 VARCHAR2(255)
,HDRPASSTHRUCHAR08 VARCHAR2(255)
,HDRPASSTHRUCHAR09 VARCHAR2(255)
,HDRPASSTHRUCHAR10 VARCHAR2(255)
,HDRPASSTHRUCHAR11 VARCHAR2(255)
,HDRPASSTHRUCHAR12 VARCHAR2(255)
,HDRPASSTHRUCHAR13 VARCHAR2(255)
,HDRPASSTHRUCHAR14 VARCHAR2(255)
,HDRPASSTHRUCHAR15 VARCHAR2(255)
,HDRPASSTHRUCHAR16 VARCHAR2(255)
,HDRPASSTHRUCHAR17 VARCHAR2(255)
,HDRPASSTHRUCHAR18 VARCHAR2(255)
,HDRPASSTHRUCHAR19 VARCHAR2(255)
,HDRPASSTHRUCHAR20 VARCHAR2(255)
,HDRPASSTHRUNUM01 NUMBER(16,4)
,HDRPASSTHRUNUM02 NUMBER(16,4)
,HDRPASSTHRUNUM03 NUMBER(16,4)
,HDRPASSTHRUNUM04 NUMBER(16,4)
,HDRPASSTHRUNUM05 NUMBER(16,4)
,HDRPASSTHRUNUM06 NUMBER(16,4)
,HDRPASSTHRUNUM07 NUMBER(16,4)
,HDRPASSTHRUNUM08 NUMBER(16,4)
,HDRPASSTHRUNUM09 NUMBER(16,4)
,HDRPASSTHRUNUM10 NUMBER(16,4)
,CONFIRMED DATE
,REJECTCODE NUMBER(6)
,REJECTTEXT VARCHAR2(255)
,DATESHIPPED DATE
,ORIGORDERID NUMBER(9)
,ORIGSHIPID NUMBER(2)
,BULKRETORDERID NUMBER(9)
,BULKRETSHIPID NUMBER(2)
,RETURNTRACKINGNO VARCHAR2(30)
,PACKLISTSHIPDATE DATE
,EDICANCELPENDING CHAR(1)
,DELIVERYSERVICE VARCHAR2(4)
,SATURDAYDELIVERY CHAR(1)
,SPECIALSERVICE1 VARCHAR2(4)
,SPECIALSERVICE2 VARCHAR2(4)
,SPECIALSERVICE3 VARCHAR2(4)
,SPECIALSERVICE4 VARCHAR2(4)
,COD CHAR(1)
,AMTCOD NUMBER(10,2)
,ASNVARIANCE CHAR(1)
,BACKORDERYN CHAR(1)
,CANCELREASON VARCHAR2(12)
,RFAUTODISPLAY VARCHAR2(1)
,SOURCE VARCHAR2(3)
,TRANSAPPTDATE DATE
,DELIVERYAPTCONFNAME VARCHAR2(20)
,INTERLINECARRIER VARCHAR2(4)
,COMPANYCHECKOK CHAR(1)
,FTZ216AUTHORIZATION VARCHAR2(20)
,SHIPPERNAME VARCHAR2(40)
,SHIPPERCONTACT VARCHAR2(40)
,SHIPPERADDR1 VARCHAR2(40)
,SHIPPERADDR2 VARCHAR2(40)
,SHIPPERCITY VARCHAR2(30)
,SHIPPERSTATE VARCHAR2(5)
,SHIPPERPOSTALCODE VARCHAR2(12)
,SHIPPERCOUNTRYCODE VARCHAR2(3)
,SHIPPERPHONE VARCHAR2(15)
,SHIPPERFAX VARCHAR2(15)
,SHIPPEREMAIL VARCHAR2(255)
,CANCEL_ID VARCHAR2(30)
,CANCELLED_DATE DATE
,CANCEL_USER_ID VARCHAR2(12)
,PRONO VARCHAR2(20)
,lastpicklabel varchar2(15)
,delservicedescr varchar2(36)
,custNAME VARCHAR2(40)
,custCONTACT VARCHAR2(40)
,custADDR1 VARCHAR2(40)
,custADDR2 VARCHAR2(40)
,custCITY VARCHAR2(30)
,custSTATE VARCHAR2(5)
,custPOSTALCODE VARCHAR2(12)
,custCOUNTRYCODE VARCHAR2(3)
,custPHONE VARCHAR2(25)
,shiptypedescr varchar2(36)
,carriername varchar2(40)
,facilityNAME VARCHAR2(40)
,facilityCONTACT VARCHAR2(40)
,facilityADDR1 VARCHAR2(40)
,facilityADDR2 VARCHAR2(40)
,facilityCITY VARCHAR2(30)
,facilitySTATE VARCHAR2(5)
,facilityPOSTALCODE VARCHAR2(12)
,facilityCOUNTRYCODE VARCHAR2(3)
,facilityPHONE VARCHAR2(25)
);

create index pklrequest_hdr_sessionid_idx
 on pklrequest_header(pklsessionid);

create index pklrequest_hdr_lastupdate_idx
 on pklrequest_header(lastupdate);

create or replace package pklheaderpkg
as type pklrequest_header_type is ref cursor return pklrequest_header%rowtype;
end pklheaderpkg;
/
create or replace procedure pklheaderproc
(pklrequest_header_cursor IN OUT pklheaderpkg.pklrequest_header_type
,in_pklsessionid number
,in_orderid number
,in_shipid number
,in_debug_yn IN varchar2)
as
--
-- $Id$
--

cursor curOrderHdr is
  select *
    from orderhdr
   where orderid = in_orderid
     and shipid = in_shipid;
oh curOrderHdr%rowtype;

cursor curConsignee is
  select name,contact,addr1,addr2,city,state,postalcode,countrycode,phone
    from consignee
   where consignee = oh.shipto;

cursor curFacility is
  select name,manager,addr1,addr2,city,state,postalcode,countrycode,phone
    from facility
   where facility = oh.fromfacility;

cursor curCarrierServiceCodes is
  select descr
    from carrierservicecodes
   where oh.carrier = carrier
     and servicecode = oh.deliveryservice;

cursor curCustomer is
  select name,contact,addr1,addr2,city,state,postalcode,countrycode,phone
    from customer
   where custid = oh.custid;

cursor curCarrier is
  select name
    from carrier
   where carrier = oh.carrier;

cntRows integer;
wrk pklrequest_header%rowtype;

begin

delete from pklrequest_header
where pklsessionid = in_pklsessionid;
commit;

delete from pklrequest_header
where lastupdate < trunc(sysdate);
commit;

wrk := null;

oh := null;
open curOrderHdr;
fetch curOrderHdr into oh;
close curOrderHdr;
if oh.orderid is null then
  goto return_pkls_rows;
end if;

if trim(oh.shipto) is not null then
  open curConsignee;
  fetch curConsignee into
    oh.shiptoname,oh.shiptocontact,oh.shiptoaddr1,oh.shiptoaddr2,
    oh.shiptocity,oh.shiptostate,oh.shiptopostalcode,oh.shiptocountrycode,
    oh.shiptophone;
  close curConsignee;
end if;

wrk.lastpicklabel := substr(zoe.last_pick_label(oh.orderid,oh.shipid),1,15);

open curCarrierServiceCodes;
fetch curCarrierServiceCodes into wrk.delservicedescr;
close curCarrierServiceCodes;

open curCustomer;
fetch curCustomer into
  wrk.custname,wrk.custcontact,wrk.custaddr1,wrk.custaddr2,
  wrk.custcity,wrk.custstate,wrk.custpostalcode,wrk.custcountrycode,
  wrk.custphone;
close curCustomer;

open curfacility;
fetch curfacility into
  wrk.facilityname,wrk.facilitycontact,wrk.facilityaddr1,wrk.facilityaddr2,
  wrk.facilitycity,wrk.facilitystate,wrk.facilitypostalcode,wrk.facilitycountrycode,
  wrk.facilityphone;
close curfacility;

begin
  select descr
    into wrk.shiptypedescr
    from shipmenttypes
   where code = oh.shiptype;
exception when others then
  wrk.shiptypedescr := oh.orderstatus;
end;

open curCarrier;
fetch curCarrier into wrk.carriername;
close curCarrier;

insert into pklrequest_header
values (in_pklsessionid,oh.ORDERID,oh.SHIPID,oh.CUSTID,oh.ORDERTYPE,oh.ENTRYDATE,oh.APPTDATE,
oh.SHIPDATE,oh.PO,oh.RMA,oh.ORDERSTATUS,oh.COMMITSTATUS,oh.FROMFACILITY,oh.TOFACILITY,
oh.LOADNO,oh.STOPNO,oh.SHIPNO,oh.SHIPTO,oh.DELAREA,oh.QTYORDER,oh.WEIGHTORDER,oh.CUBEORDER,
oh.AMTORDER,oh.QTYCOMMIT,oh.WEIGHTCOMMIT,oh.CUBECOMMIT,oh.AMTCOMMIT,oh.QTYSHIP,
oh.WEIGHTSHIP,oh.CUBESHIP,oh.AMTSHIP,oh.QTYTOTCOMMIT,oh.WEIGHTTOTCOMMIT,oh.CUBETOTCOMMIT,
oh.AMTTOTCOMMIT,oh.QTYRCVD,oh.WEIGHTRCVD,oh.CUBERCVD,oh.AMTRCVD,oh.COMMENT1,oh.STATUSUSER,
oh.STATUSUPDATE,oh.LASTUSER,oh.LASTUPDATE,oh.BILLOFLADING,oh.PRIORITY,oh.SHIPPER,
oh.ARRIVALDATE,oh.CONSIGNEE,oh.SHIPTYPE,oh.CARRIER,oh.REFERENCE,oh.SHIPTERMS,
oh.WAVE,oh.STAGELOC,oh.QTYPICK,oh.WEIGHTPICK,oh.CUBEPICK,oh.AMTPICK,oh.SHIPTONAME,
oh.SHIPTOCONTACT,oh.SHIPTOADDR1,oh.SHIPTOADDR2,oh.SHIPTOCITY,oh.SHIPTOSTATE,
oh.SHIPTOPOSTALCODE,oh.SHIPTOCOUNTRYCODE,oh.SHIPTOPHONE,oh.SHIPTOFAX,oh.SHIPTOEMAIL,
oh.BILLTONAME,oh.BILLTOCONTACT,oh.BILLTOADDR1,oh.BILLTOADDR2,oh.BILLTOCITY,
oh.BILLTOSTATE,oh.BILLTOPOSTALCODE,oh.BILLTOCOUNTRYCODE,oh.BILLTOPHONE,oh.BILLTOFAX,
oh.BILLTOEMAIL,oh.PARENTORDERID,oh.PARENTSHIPID,oh.PARENTORDERITEM,oh.PARENTORDERLOT,
oh.WORKORDERSEQ,oh.STAFFHRS,oh.QTY2SORT,oh.WEIGHT2SORT,oh.CUBE2SORT,oh.AMT2SORT,
oh.QTY2PACK,oh.WEIGHT2PACK,oh.CUBE2PACK,oh.AMT2PACK,oh.QTY2CHECK,oh.WEIGHT2CHECK,
oh.CUBE2CHECK,oh.AMT2CHECK,oh.IMPORTFILEID,oh.HDRPASSTHRUCHAR01,oh.HDRPASSTHRUCHAR02,
oh.HDRPASSTHRUCHAR03,oh.HDRPASSTHRUCHAR04,oh.HDRPASSTHRUCHAR05,oh.HDRPASSTHRUCHAR06,
oh.HDRPASSTHRUCHAR07,oh.HDRPASSTHRUCHAR08,oh.HDRPASSTHRUCHAR09,oh.HDRPASSTHRUCHAR10,
oh.HDRPASSTHRUCHAR11,oh.HDRPASSTHRUCHAR12,oh.HDRPASSTHRUCHAR13,oh.HDRPASSTHRUCHAR14,
oh.HDRPASSTHRUCHAR15,oh.HDRPASSTHRUCHAR16,oh.HDRPASSTHRUCHAR17,oh.HDRPASSTHRUCHAR18,
oh.HDRPASSTHRUCHAR19,oh.HDRPASSTHRUCHAR20,oh.HDRPASSTHRUNUM01,oh.HDRPASSTHRUNUM02,
oh.HDRPASSTHRUNUM03,oh.HDRPASSTHRUNUM04,oh.HDRPASSTHRUNUM05,oh.HDRPASSTHRUNUM06,
oh.HDRPASSTHRUNUM07,oh.HDRPASSTHRUNUM08,oh.HDRPASSTHRUNUM09,oh.HDRPASSTHRUNUM10,
oh.CONFIRMED,oh.REJECTCODE,oh.REJECTTEXT,oh.DATESHIPPED,oh.ORIGORDERID,oh.ORIGSHIPID,
oh.BULKRETORDERID,oh.BULKRETSHIPID,oh.RETURNTRACKINGNO,oh.PACKLISTSHIPDATE,
oh.EDICANCELPENDING,oh.DELIVERYSERVICE,oh.SATURDAYDELIVERY,oh.SPECIALSERVICE1,
oh.SPECIALSERVICE2,oh.SPECIALSERVICE3,oh.SPECIALSERVICE4,oh.COD,oh.AMTCOD,oh.ASNVARIANCE,
oh.BACKORDERYN,oh.CANCELREASON,oh.RFAUTODISPLAY,oh.SOURCE,oh.TRANSAPPTDATE,
oh.DELIVERYAPTCONFNAME,oh.INTERLINECARRIER,oh.COMPANYCHECKOK,oh.FTZ216AUTHORIZATION,
oh.SHIPPERNAME,oh.SHIPPERCONTACT,oh.SHIPPERADDR1,oh.SHIPPERADDR2,oh.SHIPPERCITY,
oh.SHIPPERSTATE,oh.SHIPPERPOSTALCODE,oh.SHIPPERCOUNTRYCODE,oh.SHIPPERPHONE,
oh.SHIPPERFAX,oh.SHIPPEREMAIL,oh.CANCEL_ID,oh.CANCELLED_DATE,oh.CANCEL_USER_ID,
wrk.PRONO,wrk.lastpicklabel,wrk.delservicedescr,wrk.custNAME,
wrk.custCONTACT,wrk.custADDR1,wrk.custADDR2,wrk.custCITY,wrk.custSTATE,
wrk.custPOSTALCODE,wrk.custCOUNTRYCODE,wrk.custPHONE,wrk.shiptypedescr,
wrk.carriername,wrk.facilityname,wrk.facilitycontact,wrk.facilityaddr1,wrk.facilityaddr2,
wrk.facilitycity,wrk.facilitystate,wrk.facilitypostalcode,wrk.facilitycountrycode,
wrk.facilityphone);

<<return_pkls_rows>>

commit;

open pklrequest_header_cursor for
 select *
   from pklrequest_header
  where pklsessionid = in_pklsessionid;

end pklheaderproc;
/
show errors package pklheaderpkg;
show errors procedure pklheaderproc;
exit;
