create or replace view asofshippingplateview as
select
sp.LPID,
sp.ITEM,
sp.CUSTID,
sp.FACILITY,
sp.LOCATION,
sp.STATUS,
sp.HOLDREASON,
sp.UNITOFMEASURE,
sp.QUANTITY,
sp.TYPE,
sp.FROMLPID,
sp.SERIALNUMBER,
decode(ci.lotrequired,'P',NULL,sp.LOTNUMBER) as LOTNUMBER,
sp.PARENTLPID,
sp.USERITEM1,
sp.USERITEM2,
sp.USERITEM3,
sp.LASTUSER,
sp.LASTUPDATE,
sp.INVSTATUS,
sp.QTYENTERED,
sp.ORDERITEM,
sp.UOMENTERED,
sp.INVENTORYCLASS,
sp.LOADNO,
sp.STOPNO,
sp.SHIPNO,
sp.ORDERID,
sp.SHIPID,
sp.WEIGHT,
sp.UCC128,
sp.LABELFORMAT,
sp.TASKID,
sp.DROPSEQ,
sp.ORDERLOT,
sp.PICKUOM,
sp.PICKQTY,
sp.TRACKINGNO,
sp.CARTONSEQ,
sp.CHECKED,
sp.TOTELPID,
sp.CARTONTYPE,
sp.PICKEDFROMLOC,
sp.SHIPPINGCOST,
sp.CARRIERCODEUSED,
sp.SATDELIVERYUSED,
sp.OPENFACILITY,
sp.AUDITED,
sp.PREVLOCATION,
sp.FROMLPIDPARENT,
sp.RMATRACKINGNO,
sp.ACTUALCARRIER
from shippingplate sp,custitem ci
where sp.custid=ci.custid and
	sp.item=ci.item;

comment on table asofshippingplateview is '$Id$';

exit;
