create or replace view bar_bolrpt
(
       OH_orderid,
       OH_shipid,
       OH_entrydate,
       OH_apptdate,
       OH_shipdate,
       OH_po,
       OH_orderstatus,
       OH_billoflading,
       OH_arrivaldate,
       OH_loadno,
       OH_reference,
       CN_name,
       CN_addr1,
       CN_addr2,
       CN_city,
       CN_state,
       CN_postalcode,
       CN_countrycode,
       CR_name,
       CR_addr1,
       CR_addr2,
       CR_city,
       CR_state,
       CR_postalcode,
       CR_countrycode,
       CAR_name,
       CR_scac,
       CU_custid,
       CU_name,
       CU_addr1,
       CU_addr2,
       CU_city,
       CU_state,
       CU_postalcode,
       CU_countrycode,
       OD_orderid,
       OD_shipid,
       OD_item,
       SP_item,
       OD_qtyship,
       OD_weightship,
       OD_lotnumber,
       OD_lotnumber_null,
       FAC_name,
       FAC_addr1,
       FAC_addr2,
       FAC_city,
       FAC_state,
       FAC_postalcode,
       FAC_countrycode,
       LD_trailer,
       LD_seal,
       LD_prono,
       ODC_item,
       CI_descr,
       CI_hazardous,
       CI_lotsumbol,
       ST_abbrev,
       STRM_abbrev,
       PO_NUMBER,
       DATE_SHIPPED,
       QTY_ORDERED,
       QTY_ENTERED,
       UOM_ENTERED,
		   OH_CONSIGNEE,
		   OH_SHIPTO
)
as
select
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.name,CNPPD.name),CN.name),OH.billtoname),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.name,OH.shiptoname),OH.billtoname),
                '3RD',decode(OH.billtoname,null,decode(CN.name,null,CU.name,CN.name),OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.addr1,CNPPD.addr1),CN.addr1),OH.billtoaddr1),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),OH.billtoaddr1),
                '3RD',decode(OH.billtoname,null,decode(CN.name,null,CU.addr1,CN.addr1),OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.addr2,CNPPD.addr2),CN.addr2),OH.billtoaddr2),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),OH.billtoaddr2),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.addr1,CN.addr1),OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.city,CNPPD.city),CN.city), OH.billtocity),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.city, OH.shiptocity), OH.billtocity),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.city,CN.city), OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.state,CNPPD.state),CN.state),OH.billtostate),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.state, OH.shiptostate),OH.billtostate),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.state,CN.state),OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.postalcode,CNPPD.postalcode),CN.postalcode),OH.billtopostalcode),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),OH.billtopostalcode),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.postalcode,CN.postalcode),OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.countrycode,CNPPD.countrycode),CN.countrycode),OH.billtocountrycode),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),OH.billtocountrycode),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.countrycode,CN.countrycode),OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       sum(SP.quantity),
       sum(SP.weight),
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
        OH.HDRPASSTHRUCHAR03,
        OH.DATESHIPPED,
        OD.QTYORDER,
        OD.QTYENTERED,
        OD.UOMENTERED,
		  OH.CONSIGNEE,
		  OH.SHIPTO
from
    orderhdr OH,
    consignee CN,
    consignee CNS,
    carrier CR,
    custitem CI,
    customer CU,
    orderdtl OD,
    shippingplate SP,
    facility FAC,
    loads LD,
    orderdtlbolcomments ODC,
    shipmenttypes ST,
    shipmentterms STRM,
    consignee CNPPD
where
    nvl(OH.consignee,OH.shipto) = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.custid = CU.custid(+) and
    OH.orderid = OD.orderid and
    OH.shipid = OD.shipid and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OD.custid = CI.custid and
    OD.item = CI.item and
    OD.orderid = ODC.orderid(+) and
    OD.shipid = ODC.shipid(+) and
    OD.item = ODC.item(+) and
    OD.orderid = SP.orderid and
    OD.shipid = SP.shipid and
    OD.item = SP.orderitem and
    SP.type in ('F','P') and
    nvl(OD.lotnumber,'(none)') = nvl(SP.orderlot,'(none)') and
    nvl(OD.lotnumber,'(none)') = nvl(ODC.lotnumber(+),'(none)') and
    OH.shiptype = ST.code (+) and
    OH.shipterms = STRM.code (+) and
    (OH.orderstatus = '8' or
    OH.orderstatus = '9') and
    CU.billfreightto = CNPPD.consignee(+)
group by
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
        decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.name,CNPPD.name),CN.name),OH.billtoname),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.name,OH.shiptoname),OH.billtoname),
                '3RD',decode(OH.billtoname,null,decode(CN.name,null,CU.name,CN.name),OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.addr1,CNPPD.addr1),CN.addr1),OH.billtoaddr1),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),OH.billtoaddr1),
                '3RD',decode(OH.billtoname,null,decode(CN.name,null,CU.addr1,CN.addr1),OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.addr2,CNPPD.addr2),CN.addr2),OH.billtoaddr2),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),OH.billtoaddr2),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.addr1,CN.addr1),OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.city,CNPPD.city),CN.city), OH.billtocity),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.city, OH.shiptocity), OH.billtocity),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.city,CN.city), OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.state,CNPPD.state),CN.state),OH.billtostate),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.state, OH.shiptostate),OH.billtostate),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.state,CN.state),OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.postalcode,CNPPD.postalcode),CN.postalcode),OH.billtopostalcode),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),OH.billtopostalcode),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.postalcode,CN.postalcode),OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', decode(OH.billtoname,null,decode(CN.name,null,decode(CNPPD.name,null,CU.countrycode,CNPPD.countrycode),CN.countrycode),OH.billtocountrycode),
                'COL', decode(OH.billtoname,null,decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),OH.billtocountrycode),
                '3RD', decode(OH.billtoname,null,decode(CN.name,null,CU.countrycode,CN.countrycode),OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
        OH.HDRPASSTHRUCHAR03,
        OH.DATESHIPPED,
        OD.QTYORDER,
        OD.QTYENTERED,
        OD.UOMENTERED,
		    OH.CONSIGNEE,
		    OH.SHIPTO;

comment on table bar_bolrpt is '$Id$';

exit;

