create or replace view bolrpt
(
       OH_orderid,
       OH_shipid,
       OH_entrydate,
       OH_apptdate,
       OH_shipdate,
       OH_po,
       OH_orderstatus,
       OH_billoflading,
       OH_arrivaldate,
       OH_loadno,
       OH_reference,
       CN_name,
       CN_addr1,
       CN_addr2,
       CN_city,
       CN_state,
       CN_postalcode,
       CN_countrycode,
       CR_name,
       CR_addr1,
       CR_addr2,
       CR_city,
       CR_state,
       CR_postalcode,
       CR_countrycode,
       CAR_name,
       CR_scac,
       CU_custid,
       CU_name,
       CU_addr1,
       CU_addr2,
       CU_city,
       CU_state,
       CU_postalcode,
       CU_countrycode,
       OD_orderid,
       OD_shipid,
       OD_item,
       SP_item,
       OD_qtyship,
       OD_weightship,
       OD_lotnumber,
       OD_lotnumber_null,
       FAC_name,
       FAC_addr1,
       FAC_addr2,
       FAC_city,
       FAC_state,
       FAC_postalcode,
       FAC_countrycode,
       LD_trailer,
       LD_seal,
       LD_prono,
       ODC_item,
       CI_descr,
       CI_hazardous,
       CI_lotsumbol,
       ST_abbrev,
       STRM_abbrev,
       PO_NUMBER,
       DATE_SHIPPED,
       QTY_ORDERED,
       QTY_ENTERED,
       UOM_ENTERED,
	 OD_CUBEORDER,
       OD_CUBESHIP,
       OD_WEIGHTORDER,
       CHEMCODE,
       BASEUOM,
       SECONDARYCHEMCODE,
TERTIARYCHEMCODE,
QUATERNARYCHEMCODE,
IMOPRIMARYCHEMCODE,
IMOSECONDARYCHEMCODE,
IMOTERTIARYCHEMCODE,
IMOQUATERNARYCHEMCODE,
IATAPRIMARYCHEMCODE,
IATASECONDARYCHEMCODE,
IATATERTIARYCHEMCODE,
IATAQUATERNARYCHEMCODE,
COD, COD_AMOUNT,
OH_SHIPTYPE,
OH_COMPANYCHECKOK,
       GROSSWEIGHT,
OH_CONSIGNEE,
OH_SHIPTO,
LD_LOADSTATUS,
LD_STATUSUPDATE,
OD_qtypick,
OD_weightpick,
OD_cubepick,
SP_lotnumber,
SHIPTO_ORDER_COUNT,
LD_OB_ARRIVALDATE,
OD_QTYSHIP_CASE,
OD_QTYPICK_CASE,
OD_QTYSHIP_ROLL,
OD_QTYPICK_ROLL,
OD_QTYSHIP_DRUM,
OD_QTYPICK_DRUM,
OD_QTYSHIP_BAG,
OD_QTYPICK_BAG,
SP_ORDERLOTNOTNULL
)
as
select
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       sum(SP.quantity),
       sum(SP.weight),
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
        OH.HDRPASSTHRUCHAR03,
        OH.DATESHIPPED,
        OD.QTYORDER,
        OD.QTYENTERED,
        OD.UOMENTERED,
	  OD.CUBEORDER,
       sum(zci.item_cube(SP.custid,SP.item,SP.unitofmeasure) * SP.quantity),
        OD.WEIGHTORDER,
	  CI.primarychemcode,
        CI.baseuom,
        CI.SECONDARYCHEMCODE,
CI.TERTIARYCHEMCODE,
CI.QUATERNARYCHEMCODE,
CI.IMOPRIMARYCHEMCODE,
CI.IMOSECONDARYCHEMCODE,
CI.IMOTERTIARYCHEMCODE,
CI.IMOQUATERNARYCHEMCODE,
CI.IATAPRIMARYCHEMCODE,
CI.IATASECONDARYCHEMCODE,
CI.IATATERTIARYCHEMCODE,
CI.IATAQUATERNARYCHEMCODE,
OH.cod,
OH.amtcod,
OH.shiptype,
OH.companycheckok,
sum(SP.weight + (zlbl.uom_qty_conv(od.custid,sp.item,SP.quantity,od.uom,ci.baseuom) * nvl(ci.tareweight,0))),
OH.CONSIGNEE,
OH.SHIPTO,
LD.LOADSTATUS,
LD.STATUSUPDATE,
OD.QTYPICK,
OD.WEIGHTPICK,
OD.CUBEPICK,
nvl(decode(CI.lotsumbol,'Y',null,SP.lotnumber),'**NULL**'),
min((select count(1)
   from orderhdr
  where loadno=OH.loadno
    and ((shipto=OH.shipto)
     or  (shiptoname=OH.shiptoname
    and   shiptoaddr1=OH.shiptoaddr1)))) shipto_order_count,
zld.outbound_arrivaldate(LD.loadno),
sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Case'),'CS')),0)),
sum(nvl(zbut.translate_uom_function(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Case'),'CS')),0)),
sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Roll'),'ROLL')),0)),
sum(nvl(zbut.translate_uom_function(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Roll'),'ROLL')),0)),
sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Drum'),'DRUM')),0)),
sum(nvl(zbut.translate_uom_function(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Drum'),'DRUM')),0)),
sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Bag'),'BAG')),0)),
sum(nvl(zbut.translate_uom_function(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Bag'),'BAG')),0)),
nvl(SP.orderlot,'(none)')
from
    orderhdr OH,
    consignee CN,
    consignee CNS,
    carrier CR,
    custitem CI,
    customer CU,
    orderdtl OD,
    shippingplate SP,
    facility FAC,
    loads LD,
    orderdtlbolcomments ODC,
    shipmenttypes ST,
    shipmentterms STRM
where
    nvl(OH.consignee,OH.shipto) = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.custid = CU.custid(+) and
    OH.orderid = OD.orderid and
    OH.shipid = OD.shipid and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OD.custid = CI.custid and
    SP.item = CI.item and
    OD.orderid = ODC.orderid(+) and
    OD.shipid = ODC.shipid(+) and
    OD.item = ODC.item(+) and
    OD.orderid = SP.orderid and
    OD.shipid = SP.shipid and
    OD.item = SP.orderitem and
    SP.type in ('F','P') and
    nvl(OD.lotnumber,'(none)') = nvl(SP.orderlot,'(none)') and
    nvl(OD.lotnumber,'(none)') = nvl(ODC.lotnumber(+),'(none)') and
    OH.shiptype = ST.code (+) and
    OH.shipterms = STRM.code (+) and
    (OH.orderstatus in ('8','9') or
     (OH.orderstatus in ('A','R') and
      OH.ordertype in ('T','C','U')))
group by
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
        OH.HDRPASSTHRUCHAR03,
        OH.DATESHIPPED,
        OD.QTYORDER,
        OD.QTYENTERED,
        OD.UOMENTERED,
	  OD.CUBEORDER,
        OD.WEIGHTORDER,
	  CI.primarychemcode,
        CI.baseuom,
        CI.SECONDARYCHEMCODE,
CI.TERTIARYCHEMCODE,
CI.QUATERNARYCHEMCODE,
CI.IMOPRIMARYCHEMCODE,
CI.IMOSECONDARYCHEMCODE,
CI.IMOTERTIARYCHEMCODE,
CI.IMOQUATERNARYCHEMCODE,
CI.IATAPRIMARYCHEMCODE,
CI.IATASECONDARYCHEMCODE,
CI.IATATERTIARYCHEMCODE,
CI.IATAQUATERNARYCHEMCODE,
OH.cod,
OH.amtcod,
OH.shiptype,
OH.companycheckok,
OH.CONSIGNEE,
OH.SHIPTO,
LD.LOADSTATUS,
LD.STATUSUPDATE,
OD.QTYPICK,
OD.WEIGHTPICK,
OD.CUBEPICK,
zld.outbound_arrivaldate(LD.loadno),
nvl(SP.orderlot,'(none)');

comment on table bolrpt is '$Id$';        

create or replace view bolrpt_picked
(
       OH_orderid,
       OH_shipid,
       OH_entrydate,
       OH_apptdate,
       OH_shipdate,
       OH_po,
       OH_orderstatus,
       OH_billoflading,
       OH_arrivaldate,
       OH_loadno,
       OH_reference,
       CN_name,
       CN_addr1,
       CN_addr2,
       CN_city,
       CN_state,
       CN_postalcode,
       CN_countrycode,
       CR_name,
       CR_addr1,
       CR_addr2,
       CR_city,
       CR_state,
       CR_postalcode,
       CR_countrycode,
       CAR_name,
       CR_scac,
       CU_custid,
       CU_name,
       CU_addr1,
       CU_addr2,
       CU_city,
       CU_state,
       CU_postalcode,
       CU_countrycode,
       OD_orderid,
       OD_shipid,
       OD_item,
       SP_item,
       OD_qtyship,
       OD_weightship,
       OD_lotnumber,
       OD_lotnumber_null,
       FAC_name,
       FAC_addr1,
       FAC_addr2,
       FAC_city,
       FAC_state,
       FAC_postalcode,
       FAC_countrycode,
       LD_trailer,
       LD_seal,
       LD_prono,
       ODC_item,
       CI_descr,
       CI_hazardous,
       CI_lotsumbol,
       ST_abbrev,
       STRM_abbrev,
       PO_NUMBER,
       DATE_SHIPPED,
       QTY_ORDERED,
       QTY_ENTERED,
       UOM_ENTERED,
	 OD_CUBEORDER,
       OD_CUBESHIP,
       OD_WEIGHTORDER,
       CHEMCODE,
       BASEUOM,
       SECONDARYCHEMCODE,
TERTIARYCHEMCODE,
QUATERNARYCHEMCODE,
IMOPRIMARYCHEMCODE,
IMOSECONDARYCHEMCODE,
IMOTERTIARYCHEMCODE,
IMOQUATERNARYCHEMCODE,
IATAPRIMARYCHEMCODE,
IATASECONDARYCHEMCODE,
IATATERTIARYCHEMCODE,
IATAQUATERNARYCHEMCODE,
COD, COD_AMOUNT,
OH_SHIPTYPE,
OH_COMPANYCHECKOK,
       GROSSWEIGHT,
OH_CONSIGNEE,
OH_SHIPTO,
LD_LOADSTATUS,
LD_STATUSUPDATE,
OD_qtypick,
OD_weightpick,
OD_cubepick,
SP_lotnumber,
shipto_order_count,
OD_qtyship_case,
OD_qtypick_case,
OD_qtyship_roll,
OD_qtypick_roll,
OD_qtyship_drum,
OD_qtypick_drum,
OD_qtyship_bag,
OD_qtypick_bag,
SP_ORDERLOTNOTNULL
)
as
select
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       sum(SP.quantity),
       sum(SP.weight),
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
        OH.HDRPASSTHRUCHAR03,
        OH.DATESHIPPED,
        OD.QTYORDER,
        OD.QTYENTERED,
        OD.UOMENTERED,
	  OD.CUBEORDER,
sum(zlbl.uom_qty_conv(od.custid,sp.item,SP.quantity,od.uom,ci.baseuom) * CI.cube/1728),
        OD.WEIGHTORDER,
	  CI.primarychemcode,
        CI.baseuom,
        CI.SECONDARYCHEMCODE,
CI.TERTIARYCHEMCODE,
CI.QUATERNARYCHEMCODE,
CI.IMOPRIMARYCHEMCODE,
CI.IMOSECONDARYCHEMCODE,
CI.IMOTERTIARYCHEMCODE,
CI.IMOQUATERNARYCHEMCODE,
CI.IATAPRIMARYCHEMCODE,
CI.IATASECONDARYCHEMCODE,
CI.IATATERTIARYCHEMCODE,
CI.IATAQUATERNARYCHEMCODE,
OH.cod,
OH.amtcod,
OH.shiptype,
OH.companycheckok,
sum(SP.weight + (zlbl.uom_qty_conv(od.custid,sp.item,SP.quantity,od.uom,ci.baseuom) * nvl(ci.tareweight,0))),
OH.CONSIGNEE,
OH.SHIPTO,
LD.LOADSTATUS,
LD.STATUSUPDATE,
OD.QTYPICK,
OD.WEIGHTPICK,
OD.CUBEPICK,
nvl(decode(CI.lotsumbol,'Y',null,SP.lotnumber),'**NULL**'),
min((select count(1)
   from orderhdr
  where loadno=OH.loadno
    and ((shipto=OH.shipto)
     or  (shiptoname=OH.shiptoname
    and   shiptoaddr1=OH.shiptoaddr1)))) shipto_order_count,
sum(nvl(zlbl.uom_qty_conv(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Case'),'CS')),0)),
sum(nvl(zlbl.uom_qty_conv(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Case'),'CS')),0)),
sum(nvl(zlbl.uom_qty_conv(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Roll'),'ROLL')),0)),
sum(nvl(zlbl.uom_qty_conv(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Roll'),'ROLL')),0)),
sum(nvl(zlbl.uom_qty_conv(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Drum'),'DRUM')),0)),
sum(nvl(zlbl.uom_qty_conv(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Drum'),'DRUM')),0)),
sum(nvl(zlbl.uom_qty_conv(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Bag'),'BAG')),0)),
sum(nvl(zlbl.uom_qty_conv(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Bag'),'BAG')),0)),
nvl(SP.orderlot,'(none)')
from
    orderhdr OH,
    consignee CN,
    consignee CNS,
    carrier CR,
    custitem CI,
    customer CU,
    orderdtl OD,
    shippingplate SP,
    facility FAC,
    loads LD,
    orderdtlbolcomments ODC,
    shipmenttypes ST,
    shipmentterms STRM
where
    nvl(OH.consignee,OH.shipto) = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.custid = CU.custid(+) and
    OH.orderid = OD.orderid and
    OH.shipid = OD.shipid and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OD.custid = CI.custid and
    SP.item = CI.item and
    OD.orderid = ODC.orderid(+) and
    OD.shipid = ODC.shipid(+) and
    OD.item = ODC.item(+) and
    OD.orderid = SP.orderid and
    OD.shipid = SP.shipid and
    OD.item = SP.orderitem and
    SP.type in ('F','P') and
    nvl(OD.lotnumber,'(none)') = nvl(SP.orderlot,'(none)') and
    nvl(OD.lotnumber,'(none)') = nvl(ODC.lotnumber(+),'(none)') and
    OH.shiptype = ST.code (+) and
    OH.shipterms = STRM.code (+) and
    (OH.orderstatus in ('5','6','7','8','9') or
     (OH.orderstatus in ('A','R') and
      OH.ordertype in ('T','C','U')))
group by
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
        OH.HDRPASSTHRUCHAR03,
        OH.DATESHIPPED,
        OD.QTYORDER,
        OD.QTYENTERED,
        OD.UOMENTERED,
	  OD.CUBEORDER,
        OD.WEIGHTORDER,
	  CI.primarychemcode,
        CI.baseuom,
        CI.SECONDARYCHEMCODE,
CI.TERTIARYCHEMCODE,
CI.QUATERNARYCHEMCODE,
CI.IMOPRIMARYCHEMCODE,
CI.IMOSECONDARYCHEMCODE,
CI.IMOTERTIARYCHEMCODE,
CI.IMOQUATERNARYCHEMCODE,
CI.IATAPRIMARYCHEMCODE,
CI.IATASECONDARYCHEMCODE,
CI.IATATERTIARYCHEMCODE,
CI.IATAQUATERNARYCHEMCODE,
OH.cod,
OH.amtcod,
OH.shiptype,
OH.companycheckok,
OH.CONSIGNEE,
OH.SHIPTO,
LD.LOADSTATUS,
LD.STATUSUPDATE,
OD.QTYPICK,
OD.WEIGHTPICK,
OD.CUBEPICK,
nvl(SP.orderlot,'(none)');

comment on table bolrpt_picked is '$Id$';

create or replace view bolrpt_sp
(
       SP_orderid,
       SP_shipid,
       SP_item,
       SP_lotnumber,
       SP_orderlotnotnull,
       SP_useritem1,
       SP_useritem2,
       SP_useritem3,
       SP_serialnumber,
       SP_quantity,
       SP_weight,
       SP_quantity_case,
       SP_quantity_roll,
       SP_quantity_drum,
       SP_quantity_bag
)
as
select
       SP.orderid,
       SP.shipid,
       SP.item,
       nvl(decode(CI.lotsumbol,'Y',null,SP.lotnumber),'**NULL**'),
       nvl(SP.orderlot,'(none)'),
       SP.useritem1,
       SP.useritem2,
       SP.useritem3,
       SP.serialnumber,
       sum(SP.quantity),
       sum(SP.weight),
       sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
           nvl((select min(code) from unitsofmeasure where abbrev='Case'),'CS')),0)),
       sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
           nvl((select min(code) from unitsofmeasure where abbrev='Roll'),'ROLL')),0)),
       sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
           nvl((select min(code) from unitsofmeasure where abbrev='Drum'),'DRUM')),0)),
       sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
           nvl((select min(code) from unitsofmeasure where abbrev='Bag'),'BAG')),0))
from
    shippingplate SP,
    custitem CI
where
    SP.custid = CI.custid and
    SP.item = CI.item and
    SP.type in ('F','P')
group by
       SP.orderid,
       SP.shipid,
       SP.item,
       nvl(decode(CI.lotsumbol,'Y',null,SP.lotnumber),'**NULL**'),
       nvl(SP.orderlot,'(none)'),
       SP.useritem1,
       SP.useritem2,
       SP.useritem3,
       SP.serialnumber;

comment on table bolrpt_sp is '$Id$';

create or replace view bolrpt_expandedsp
(
       OH_orderid,
       OH_shipid,
       OH_entrydate,
       OH_apptdate,
       OH_shipdate,
       OH_po,
       OH_orderstatus,
       OH_billoflading,
       OH_arrivaldate,
       OH_loadno,
       OH_reference,
       CN_name,
       CN_addr1,
       CN_addr2,
       CN_city,
       CN_state,
       CN_postalcode,
       CN_countrycode,
       CN_contact,
       CR_name,
       CR_addr1,
       CR_addr2,
       CR_city,
       CR_state,
       CR_postalcode,
       CR_countrycode,
       CR_contact,
       CAR_name,
       CAR_contact,
       CR_scac,
       CU_custid,
       CU_name,
       CU_addr1,
       CU_addr2,
       CU_city,
       CU_state,
       CU_postalcode,
       CU_countrycode,
       CU_contact,
       OD_orderid,
       OD_shipid,
       OD_item,
       SP_item,
       OD_qtyship,
       OD_weightship,
       OD_lotnumber,
       OD_lotnumber_null,
       FAC_name,
       FAC_addr1,
       FAC_addr2,
       FAC_city,
       FAC_state,
       FAC_postalcode,
       FAC_countrycode,
       LD_trailer,
       LD_seal,
       LD_prono,
       ODC_item,
       CI_descr,
       CI_hazardous,
       CI_lotsumbol,
       ST_abbrev,
       STRM_abbrev,
       PO_NUMBER,
       DATE_SHIPPED,
       QTY_ORDERED,
       QTY_ENTERED,
       UOM_ENTERED,
	 OD_CUBEORDER,
       OD_CUBESHIP,
       OD_WEIGHTORDER,
       CHEMCODE,
       BASEUOM,
       SECONDARYCHEMCODE,
TERTIARYCHEMCODE,
QUATERNARYCHEMCODE,
IMOPRIMARYCHEMCODE,
IMOSECONDARYCHEMCODE,
IMOTERTIARYCHEMCODE,
IMOQUATERNARYCHEMCODE,
IATAPRIMARYCHEMCODE,
IATASECONDARYCHEMCODE,
IATATERTIARYCHEMCODE,
IATAQUATERNARYCHEMCODE,
COD, COD_AMOUNT,
OH_SHIPTYPE,
OH_COMPANYCHECKOK,
       GROSSWEIGHT,
OH_CONSIGNEE,
OH_SHIPTO,
LD_LOADSTATUS,
LD_STATUSUPDATE,
OD_qtypick,
OD_weightpick,
OD_cubepick,
SP_lotnumber,
SHIPTO_ORDER_COUNT,
LD_OB_ARRIVALDATE,
OD_QTYSHIP_CASE,
OD_QTYPICK_CASE,
OD_QTYSHIP_ROLL,
OD_QTYPICK_ROLL,
OD_QTYSHIP_DRUM,
OD_QTYPICK_DRUM,
OD_QTYSHIP_BAG,
OD_QTYPICK_BAG,
SP_ORDERLOTNOTNULL,
sp_useritem1,
sp_useritem2,
sp_useritem3,
sp_expirationdate,
sp_manufacturedate
)
as
select
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shiptoname,null,CNS.contact, OH.shiptocontact),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       decode(OH.shipterms,
                'PPD', CU.contact,
                'COL', CN.contact,
                '3RD',
                  decode(OH.billtocontact,null,CN.contact,OH.billtocontact),
                CU.contact),
       CR.name,
       CR.contact,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       CU.contact,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       sum(SP.quantity),
       sum(SP.weight),
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
        OH.HDRPASSTHRUCHAR03,
        OH.DATESHIPPED,
        OD.QTYORDER,
        OD.QTYENTERED,
        OD.UOMENTERED,
	  OD.CUBEORDER,
       sum(zci.item_cube(SP.custid,SP.item,SP.unitofmeasure) * SP.quantity),
        OD.WEIGHTORDER,
	  CI.primarychemcode,
        CI.baseuom,
        CI.SECONDARYCHEMCODE,
CI.TERTIARYCHEMCODE,
CI.QUATERNARYCHEMCODE,
CI.IMOPRIMARYCHEMCODE,
CI.IMOSECONDARYCHEMCODE,
CI.IMOTERTIARYCHEMCODE,
CI.IMOQUATERNARYCHEMCODE,
CI.IATAPRIMARYCHEMCODE,
CI.IATASECONDARYCHEMCODE,
CI.IATATERTIARYCHEMCODE,
CI.IATAQUATERNARYCHEMCODE,
OH.cod,
OH.amtcod,
OH.shiptype,
OH.companycheckok,
sum(SP.weight + (zlbl.uom_qty_conv(od.custid,sp.item,SP.quantity,od.uom,ci.baseuom) * nvl(ci.tareweight,0))),
OH.CONSIGNEE,
OH.SHIPTO,
LD.LOADSTATUS,
LD.STATUSUPDATE,
OD.QTYPICK,
OD.WEIGHTPICK,
OD.CUBEPICK,
nvl(decode(CI.lotsumbol,'Y',null,SP.lotnumber),'**NULL**'),
min((select count(1)
   from orderhdr
  where loadno=OH.loadno
    and ((shipto=OH.shipto)
     or  (shiptoname=OH.shiptoname
    and   shiptoaddr1=OH.shiptoaddr1)))) shipto_order_count,
zld.outbound_arrivaldate(LD.loadno),
sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Case'),'CS')),0)),
sum(nvl(zbut.translate_uom_function(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Case'),'CS')),0)),
sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Roll'),'ROLL')),0)),
sum(nvl(zbut.translate_uom_function(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Roll'),'ROLL')),0)),
sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Drum'),'DRUM')),0)),
sum(nvl(zbut.translate_uom_function(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Drum'),'DRUM')),0)),
sum(nvl(zbut.translate_uom_function(SP.custid,SP.item,SP.quantity,SP.unitofmeasure,
    nvl((select min(code) from unitsofmeasure where abbrev='Bag'),'BAG')),0)),
sum(nvl(zbut.translate_uom_function(OD.custid,OD.item,OD.qtypick,OD.uom,
    nvl((select min(code) from unitsofmeasure where abbrev='Bag'),'BAG')),0)),
nvl(SP.orderlot,'(none)'),
SP.useritem1,
SP.useritem2,
SP.useritem3,
trunc(SP.expirationdate),
trunc(SP.manufacturedate)
from
    orderhdr OH,
    consignee CN,
    consignee CNS,
    carrier CR,
    custitem CI,
    customer CU,
    orderdtl OD,
    shippingplate SP,
    facility FAC,
    loads LD,
    orderdtlbolcomments ODC,
    shipmenttypes ST,
    shipmentterms STRM
where
    nvl(OH.consignee,OH.shipto) = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.custid = CU.custid(+) and
    OH.orderid = OD.orderid and
    OH.shipid = OD.shipid and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OD.custid = CI.custid and
    SP.item = CI.item and
    OD.orderid = ODC.orderid(+) and
    OD.shipid = ODC.shipid(+) and
    OD.item = ODC.item(+) and
    OD.orderid = SP.orderid and
    OD.shipid = SP.shipid and
    OD.item = SP.orderitem and
    SP.type in ('F','P') and
    nvl(OD.lotnumber,'(none)') = nvl(SP.orderlot,'(none)') and
    nvl(OD.lotnumber,'(none)') = nvl(ODC.lotnumber(+),'(none)') and
    OH.shiptype = ST.code (+) and
    OH.shipterms = STRM.code (+) and
    (OH.orderstatus in ('8','9') or
     (OH.orderstatus in ('A','R') and
      OH.ordertype in ('T','C','U')))
group by
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shiptoname,null,CNS.contact, OH.shiptocontact),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       decode(OH.shipterms,
                'PPD', CU.contact,
                'COL', CN.contact,
                '3RD',
                  decode(OH.billtocontact,null,CN.contact,OH.billtocontact),
                CU.contact),
       CR.name,
       CR.contact,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       CU.contact,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
        OH.HDRPASSTHRUCHAR03,
        OH.DATESHIPPED,
        OD.QTYORDER,
        OD.QTYENTERED,
        OD.UOMENTERED,
	  OD.CUBEORDER,
        OD.WEIGHTORDER,
	  CI.primarychemcode,
        CI.baseuom,
        CI.SECONDARYCHEMCODE,
CI.TERTIARYCHEMCODE,
CI.QUATERNARYCHEMCODE,
CI.IMOPRIMARYCHEMCODE,
CI.IMOSECONDARYCHEMCODE,
CI.IMOTERTIARYCHEMCODE,
CI.IMOQUATERNARYCHEMCODE,
CI.IATAPRIMARYCHEMCODE,
CI.IATASECONDARYCHEMCODE,
CI.IATATERTIARYCHEMCODE,
CI.IATAQUATERNARYCHEMCODE,
OH.cod,
OH.amtcod,
OH.shiptype,
OH.companycheckok,
OH.CONSIGNEE,
OH.SHIPTO,
LD.LOADSTATUS,
LD.STATUSUPDATE,
OD.QTYPICK,
OD.WEIGHTPICK,
OD.CUBEPICK,
zld.outbound_arrivaldate(LD.loadno),
nvl(SP.orderlot,'(none)'),
SP.useritem1,
SP.useritem2,
SP.useritem3,
trunc(SP.expirationdate),
trunc(SP.manufacturedate);

comment on table bolrpt_expandedsp is '$Id$';        

exit;

