CREATE OR REPLACE VIEW BOLRPT_FREIGHT
(
OH_ORDERID, 
OH_SHIPID,
OH_ENTRYDATE,
OH_APPTDATE,
OH_SHIPDATE, 
OH_PO,
OH_ORDERSTATUS,
OH_BILLOFLADING,
OH_ARRIVALDATE, 
OH_LOADNO,
OH_REFERENCE,
OH_COD,
OH_COD_AMOUNT,
OH_SHIPTYPE,
OH_INTERLINECARRIER,
OH_COMPANYCHECKOK,
OH_TRANSAPPTDATE,
OH_DELIVERYAPTCONFNAME,
OH_PASSTHRUCHAR01,
OH_PASSTHRUCHAR02,
OH_PASSTHRUCHAR09,
OH_PASSTHRUCHAR10, 
OH_PASSTHRUCHAR12,
OH_PASSTHRUCHAR15,
OH_CONSIGNEE,
CN_NAME,
CN_ADDR1, 
CN_ADDR2,
CN_CITY,
CN_STATE,
CN_POSTALCODE, 
CN_COUNTRYCODE,
CR_NAME,
CR_ADDR1,
CR_ADDR2, 
CR_CITY,
CR_STATE,
CR_POSTALCODE,
CR_COUNTRYCODE, 
CAR_NAME,
CAR_SCAC,
CU_CUSTID,
CU_NAME, 
CU_ADDR1,
CU_ADDR2,
CU_CITY,
CU_STATE, 
CU_POSTALCODE,
CU_COUNTRYCODE,
OD_ITEM,
OD_LOTNUMBER, 
OD_LOTNUMBER_NULL,
OD_QTYORDER,
OD_WEIGHTORDER,
OD_QTYSHIP,
OD_WEIGHTSHIP,
OD_UOM,
OD_DTLPASSTHRUCHAR01,
OD_CONSIGNEESKU, 
FAC_NUM, 
FAC_NAME,
FAC_ADDR1, 
FAC_ADDR2,
FAC_CITY,
FAC_STATE,
FAC_POSTALCODE, 
FAC_COUNTRYCODE,
LD_TRAILER,
LD_SEAL,
LD_PRONO, 
ODC_ITEM,
ITM_DESCR, 
ST_ABBREV,
STRM_ABBREV ) AS select  
OH.orderid,  
OH.shipid,  
OH.entrydate,  
OH.apptdate,  
OH.shipdate,  
OH.po,  
OH.orderstatus,  
OH.billoflading,  
OH.arrivaldate,  
OH.loadno,  
OH.reference,  
OH.cod,  
OH.amtcod,  
OH.shiptype,  
OH.interlinecarrier,  
OH.companycheckok,  
OH.transapptdate,  
OH.deliveryaptconfname,  
OH.HDRPASSTHRUCHAR01,  
OH.HDRPASSTHRUCHAR02,  
OH.HDRPASSTHRUCHAR09,  
OH.HDRPASSTHRUCHAR10,  
OH.HDRPASSTHRUCHAR12,  
OH.HDRPASSTHRUCHAR15,
OH.CONSIGNEE,  
decode(OH.shiptoname,null,CNS.name,OH.shiptoname),  
decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),  
decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),  
decode(OH.shiptoname,null,CNS.city, OH.shiptocity),  
decode(OH.shiptoname,null,CNS.state, OH.shiptostate),  
decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),  
decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.name,CNPPD.name),  
'COL', CN.name,  
'3RD',  
decode(OH.billtoname,null,CN.name,OH.billtoname),  
CU.name),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.addr1,CNPPD.addr1),  
'COL', CN.addr1,  
'3RD',  
decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),  
CU.addr1),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.addr2,CNPPD.addr2),  
'COL', CN.addr2,  
'3RD',  
decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),  
CU.addr2),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.city,CNPPD.city),  
'COL', CN.city,  
'3RD',  
decode(OH.billtoname,null,CN.city, OH.billtocity),  
CU.city),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.state,CNPPD.state),  
'COL', CN.state,  
'3RD',  
decode(OH.billtoname,null,CN.state,OH.billtostate),  
CU.state),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.postalcode,CNPPD.postalcode),  
'COL', CN.postalcode,  
'3RD',  
decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),  
CU.postalcode),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.countrycode,CNPPD.countrycode),  
'COL', CN.countrycode,  
'3RD',  
decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),  
CU.countrycode),  
CR.name,  
CR.scac,  
CU.custid,  
CU.name,  
CU.addr1,  
CU.addr2,  
CU.city,  
CU.state,  
CU.postalcode,  
CU.countrycode,  
OD.item,  
OD.lotnumber,  
nvl(OD.lotnumber,'**NULL**'),  
OD.qtyorder,  
OD.weightorder,  
OD.qtyship,  
OD.weightship,
OD.UOM,
OD.DTLPASSTHRUCHAR01,  
OD.CONSIGNEESKU,  
FAC.facility,  
FAC.name,  
FAC.addr1,  
FAC.addr2,  
FAC.city,  
FAC.state,  
FAC.postalcode,  
FAC.countrycode,  
LD.trailer,  
LD.seal,  
LD.prono,  
ODC.item,  
NMFC.descr,  
ST.abbrev,  
STRM.abbrev  
from  
orderhdr OH,  
consignee CN,  
consignee CNS,  
carrier CR,  
NMFCLASSCODES NMFC,  
customer CU,  
orderdtl OD,  
facility FAC,  
loads LD,  
orderdtlbolcomments ODC,  
shipmenttypes ST,  
shipmentterms STRM,  
consignee CNPPD  
where  
nvl(OH.consignee,OH.shipto) = CN.consignee(+) and  
OH.shipto = CNS.consignee(+) and  
OH.carrier = CR.carrier(+) and  
OH.custid = CU.custid and  
OH.orderid = OD.orderid and  
OH.shipid = OD.shipid and  
OH.fromfacility = FAC.facility and  
OH.loadno = LD.loadno(+) and  
OD.item = NMFC.nmfc and  
OD.orderid = ODC.orderid(+) and  
OD.shipid = ODC.shipid(+) and  
OD.item = ODC.item(+) and  
nvl(od.lotnumber,'**NULL**') = nvl(odc.lotnumber (+),'**NULL**') and
OH.shiptype = ST.code (+) and  
OH.shipterms = STRM.code (+) and  
OH.ordertype = 'F' and  
OD.linestatus <> 'X' and  
CU.billfreightto = CNPPD.consignee(+)
union
select  
OH.orderid,  
OH.shipid,  
OH.entrydate,  
OH.apptdate,  
OH.shipdate,  
OH.po,  
OH.orderstatus,  
OH.billoflading,  
OH.arrivaldate,  
OH.loadno,  
OH.reference,  
OH.cod,  
OH.amtcod,  
OH.shiptype,  
OH.interlinecarrier,  
OH.companycheckok,  
OH.transapptdate,  
OH.deliveryaptconfname,  
OH.HDRPASSTHRUCHAR01,  
OH.HDRPASSTHRUCHAR02,  
OH.HDRPASSTHRUCHAR09,  
OH.HDRPASSTHRUCHAR10,  
OH.HDRPASSTHRUCHAR12,  
OH.HDRPASSTHRUCHAR15,
OH.CONSIGNEE,  
decode(OH.shiptoname,null,CNS.name,OH.shiptoname),  
decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),  
decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),  
decode(OH.shiptoname,null,CNS.city, OH.shiptocity),  
decode(OH.shiptoname,null,CNS.state, OH.shiptostate),  
decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),  
decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.name,CNPPD.name),  
'COL', CN.name,  
'3RD',  
decode(OH.billtoname,null,CN.name,OH.billtoname),  
CU.name),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.addr1,CNPPD.addr1),  
'COL', CN.addr1,  
'3RD',  
decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),  
CU.addr1),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.addr2,CNPPD.addr2),  
'COL', CN.addr2,  
'3RD',  
decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),  
CU.addr2),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.city,CNPPD.city),  
'COL', CN.city,  
'3RD',  
decode(OH.billtoname,null,CN.city, OH.billtocity),  
CU.city),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.state,CNPPD.state),  
'COL', CN.state,  
'3RD',  
decode(OH.billtoname,null,CN.state,OH.billtostate),  
CU.state),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.postalcode,CNPPD.postalcode),  
'COL', CN.postalcode,  
'3RD',  
decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),  
CU.postalcode),  
decode(OH.shipterms,  
'PPD', decode(CNPPD.consignee,null,CU.countrycode,CNPPD.countrycode),  
'COL', CN.countrycode,  
'3RD',  
decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),  
CU.countrycode),  
CR.name,  
CR.scac,  
CU.custid,  
CU.name,  
CU.addr1,  
CU.addr2,  
CU.city,  
CU.state,  
CU.postalcode,  
CU.countrycode,  
OD.item,  
OD.lotnumber,  
nvl(OD.lotnumber,'**NULL**'),  
OD.qtyorder,  
OD.weightorder,  
OD.qtyship,  
OD.weightship,
OD.UOM,
OD.DTLPASSTHRUCHAR01,  
OD.CONSIGNEESKU,  
FAC.facility,  
FAC.name,  
FAC.addr1,  
FAC.addr2,  
FAC.city,  
FAC.state,  
FAC.postalcode,  
FAC.countrycode,  
LD.trailer,  
LD.seal,  
LD.prono,  
ODC.item,  
CI.descr,  
ST.abbrev,  
STRM.abbrev  
from  
orderhdr OH,  
consignee CN,  
consignee CNS,  
carrier CR,  
custitem CI,  
customer CU,  
orderdtl OD,  
facility FAC,  
loads LD,  
orderdtlbolcomments ODC,  
shipmenttypes ST,  
shipmentterms STRM,  
consignee CNPPD  
where  
nvl(OH.consignee,OH.shipto) = CN.consignee(+) and  
OH.shipto = CNS.consignee(+) and  
OH.carrier = CR.carrier(+) and  
OH.custid = CU.custid and  
OH.orderid = OD.orderid and  
OH.shipid = OD.shipid and  
OH.fromfacility = FAC.facility and  
OH.loadno = LD.loadno(+) and
OD.custid = CI.custid and
OD.item = CI.item and  
OD.orderid = ODC.orderid(+) and  
OD.shipid = ODC.shipid(+) and  
OD.item = ODC.item(+) and  
nvl(od.lotnumber,'**NULL**') = nvl(odc.lotnumber (+),'**NULL**') and
OH.shiptype = ST.code (+) and  
OH.shipterms = STRM.code (+) and  
OH.ordertype = 'O' and  
OD.linestatus <> 'X' and  
CU.billfreightto = CNPPD.consignee(+);

comment on table BOLRPT_FREIGHT is '$Id: bolrptfreightview.sql 8179 2012-03-23 18:40:50Z eric $';
exit;
