create or replace view dre_bolrptview as
select OH_ORDERID,
OH_SHIPID,
OH_ENTRYDATE,
OH_APPTDATE,
OH_SHIPDATE,
OH_PO,
OH_ORDERSTATUS,
OH_BILLOFLADING,
OH_ARRIVALDATE,
OH_LOADNO,
OH_REFERENCE,
CN_NAME,
CN_ADDR1,
CN_ADDR2,
CN_CITY,
CN_STATE,
CN_POSTALCODE,
CN_COUNTRYCODE,
CR_NAME,
CR_ADDR1,
CR_ADDR2,
CR_CITY,
CR_STATE,
CR_POSTALCODE,
CR_COUNTRYCODE,
CAR_NAME,
CR_SCAC,
CU_CUSTID,
CU_NAME,
CU_ADDR1,
CU_ADDR2,
CU_CITY,
CU_STATE,
CU_POSTALCODE,
CU_COUNTRYCODE,
OD_ORDERID,
OD_SHIPID,
OD_ITEM,
SP_ITEM,
OD_QTYSHIP,
OD_WEIGHTSHIP,
OD_LOTNUMBER,
OD_LOTNUMBER_NULL,
FAC_NAME,
FAC_ADDR1,
FAC_ADDR2,
FAC_CITY,
FAC_STATE,
FAC_POSTALCODE,
FAC_COUNTRYCODE,
LD_TRAILER,
LD_SEAL,
LD_PRONO,
ODC_ITEM,
CI_DESCR,
CI_HAZARDOUS,
CI_LOTSUMBOL,
ST_ABBREV,
STRM_ABBREV,
PO_NUMBER,
DATE_SHIPPED,
QTY_ORDERED,
QTY_ENTERED,
UOM_ENTERED,
OH_CONSIGNEE,
OH_SHIPTO
from bolrpt
union 
select 
c.orderid   as oh_orderid,
c.shipid    as oh_shipid,
c.entrydate as OH_ENTRYDATE,
c.apptdate as OH_APPTDATE,
c.shipdate as OH_SHIPDATE,
c.po as OH_PO,
c.orderstatus as OH_ORDERSTATUS,
c.billoflading as OH_BILLOFLADING,
c.arrivaldate as OH_ARRIVALDATE,
c.loadno    as OH_LOADNO,
c.reference as OH_REFERENCE,
decode(c.shiptoname ,null ,k.name ,c.shiptoname) as CN_NAME, 
decode(c.shiptoname ,null ,k.addr1 ,c.shiptoaddr1) as CN_ADDR1, 
decode(c.shiptoname ,null ,k.addr2 ,c.shiptoaddr2) as CN_ADDR2, 
decode(c.shiptoname ,null ,k.city ,c.shiptocity) as CN_CITY, 
decode(c.shiptoname ,null ,k.state ,c.shiptostate) as CN_STATE, 
decode(c.shiptoname ,null ,k.postalcode ,c.shiptopostalcode) as CN_POSTALCODE, 
decode(c.shiptoname ,null ,k.countrycode ,c.shiptocountrycode) as CN_COUNTRYCODE, 
decode(c.shipterms,
                'PPD', e.name,
                'COL', j.name,
                '3RD',
                  decode(c.billtoname,null,j.name,c.billtoname),
                e.name) as CR_NAME,
decode(c.shipterms,
                'PPD', e.addr1,
                'COL', j.addr1,
                '3RD',
                  decode(c.billtoname,null,j.addr1,c.billtoaddr1),
                e.addr1) as CR_ADDR1,
decode(c.shipterms,
                'PPD', e.addr2,
                'COL', j.addr2,
                '3RD',
                  decode(c.billtoname,null,j.addr2,c.billtoaddr2),
                e.addr2) as CR_ADDR2,
decode(c.shipterms,
                'PPD', e.city,
                'COL', j.city,
                '3RD',
                  decode(c.billtoname,null,j.city, c.billtocity),
                e.city) as CR_CITY,
decode(c.shipterms,
                'PPD', e.state,
                'COL', j.state,
                '3RD',
                  decode(c.billtoname,null,j.state,c.billtostate),
                e.state) as CR_STATE,
decode(c.shipterms,
                'PPD', e.postalcode,
                'COL', j.postalcode,
                '3RD',
                  decode(c.billtoname,null,j.postalcode,c.billtopostalcode),
                e.postalcode) as CR_POSTALCODE,
decode(c.shipterms,
                'PPD', e.countrycode,
                'COL', j.countrycode,
                '3RD',
decode(c.billtoname,null,j.countrycode,c.billtocountrycode),
		e.countrycode) as CR_CONTRYCODE,
g.name as CAR_NAME,
g.scac as CR_SCAC,
e.custid as CU_CUSTID,
e.name as CU_NAME,
e.addr1 as CU_ADDR1,
e.addr2 as CU_ADDR2,
e.city as CU_CITY,
e.state as CU_STATE,
e.postalcode as CU_POSTALCODE,
e.countrycode as CU_COUNTRYCODE,
a.orderid as OD_ORDERID,
a.shipid as OD_SHIPID,
a.item	   as od_item,
a.item	   as sp_item,
a.qtyentered - nvl(a.qtyship,0) as od_qtyship,
a.weightorder - nvl(a.weightship,0) as od_weightship,
'PRE-ORDER                     ' as OD_LOTNUMBER,
'PRE-ORDER                     ' as OD_LOTNUMBER_NULL,
d.name as FAC_NAME,
d.addr1 as FAC_ADDR1,
d.addr2 as FAC_ADDR2,
d.city as FAC_CITY,
d.state as FAC_STATE,
d.postalcode as FAC_POSTALCODE,
d.countrycode as FAC_COUNTRYCODE,
f.trailer as LD_TRAILER,
f.seal as LD_SEAL,
f.prono as LD_PRONO,
null as ODC_ITEM,
b.descr 	   as ci_descr,
b.hazardous as ci_hazardous,
null as CI_LOTSUMBOL,
h.abbrev as ST_ABBREV,
i.abbrev as STRM_ABBREV,
null as PO_NUMBER,
sysdate as DATE_SHIPPED,
0 as QTY_ORDERED,
0 as QTY_ENTERED,
null as UOM_ENTERED,
c.consignee as OH_CONSIGNEE,
c.shipto as OH_SHIPTO
from orderdtl a, custitem b, orderhdr c, facility d, customer e, loads f, carrier g,
	shipmenttypes h, shipmentterms i, consignee j, consignee k
     where 	nvl(c.consignee,c.shipto) = j.consignee(+) and
    	    	c.shipto = k.consignee(+) and  
		a.custid = b.custid and
		a.item    = b.item and
		a.orderid = c.orderid and
		a.shipid  = c.shipid and
		c.fromfacility = d.facility (+) and
	        c.custid = e.custid and
		c.loadno = f.loadno (+) and
		c.shiptype = h.code (+) and
    		c.shipterms = i.code (+) and
		c.carrier = g.carrier(+) and
		a.qtyentered - nvl(a.qtyship,0) > 0 ;

comment on table dre_bolrptview is '$Id$';

exit;

