CREATE OR REPLACE VIEW DRE_INVITEMRPT_RNWL
(INVOICE,
 ACTIVITYDATE,
 ACTIVITY,
 CALCEDUOM, 
 BILLEDRATE,
 BILLEDQTY,
 BILLEDAMT,
 WEIGHT,
 GROSS,
 ENTEREDQTY)
AS 
SELECT "INVITEMRPT"."INVOICE",
       "INVITEMRPT"."ACTIVITYDATE",
       "INVITEMRPT"."ACTIVITY",
       "INVITEMRPT"."CALCEDUOM",
       "INVITEMRPT"."BILLEDRATE",
       SUM("INVITEMRPT"."BILLEDQTY"),
       SUM("INVITEMRPT"."BILLEDAMT"),
       SUM("INVITEMRPT"."WEIGHT"),
       SUM("INVITEMRPT"."GROSS"),
       SUM("INVITEMRPT"."ENTEREDQTY")	
  FROM "ALPS"."DRE_INVITEMRPT" "INVITEMRPT"
 GROUP BY "INVITEMRPT"."INVOICE",
          "INVITEMRPT"."ACTIVITYDATE",
          "INVITEMRPT"."ACTIVITY",
          "INVITEMRPT"."CALCEDUOM",
          "INVITEMRPT"."BILLEDRATE";
exit;