CREATE OR REPLACE VIEW DRE_BOLRPT_PRELIM2
(OH_ORDERID, OH_SHIPID, OD_ITEM, OD_LOTNUMBER, OD_LOTNUMBER_NULL, 
 FAC_NAME, FAC_ADDR1, FAC_ADDR2, FAC_CITY, FAC_STATE, 
 FAC_POSTALCODE, CN_NAME, CN_ADDR1, CN_ADDR2, CN_CITY, 
 CN_STATE, CN_POSTALCODE, CN_COUNTRYCODE, LD_TRAILER, LD_SEAL, 
 CR_NAME, CR_ADDR1, CR_ADDR2, CR_CITY, CR_STATE, 
 CR_POSTALCODE, CR_COUNTRYCODE, CU_NAME, CU_ADDR1, CU_ADDR2, 
 CU_CITY, CU_STATE, CU_POSTALCODE, CU_COUNTRYCODE, CR_SCAC, 
 OH_PO, CI_HAZARDOUS, CI_DESCR, OH_LOADNO, STRM_ABBREV, 
 OH_REFERENCE, ST_ABBREV, CAR_NAME, COD_AMOUNT, CUSTID, 
 FAC_NUM, OH_ENTRYDATE, OH_ARRIVALDATE, OH_SHIPDATE, CHEMCODE, 
 BASEUOM, DOTBOLCOMMENT, OH_SHIPTYPE, IATABOLCOMMENT, IMOBOLCOMMENT, 
 BOLITMCOMMENT, OH_COMPANYCHECKOK, OH_PRONO, MFG_DATE, OD_QTY_ORDER, 
 OD_WEIGHTORDER, GROSSWEIGHT, OD_CUBE_ORDER, SP_USERITEM1, LINEORDER,
 OH_CONSIGNEE, OH_SHIPTO)
AS 
select brp.oh_orderid,
       brp.oh_shipid,
       brp.od_item,
       brp.od_lotnumber,
       brp.od_lotnumber_null,
       brp.fac_name,
       brp.fac_addr1,
       brp.fac_addr2,
       brp.fac_city,
       brp.fac_state,
       brp.fac_postalcode,
       brp.cn_name,
       brp.cn_addr1,
       brp.cn_addr2,
       brp.cn_city,
       brp.cn_state,
       brp.cn_postalcode,
       brp.cn_countrycode,
       brp.ld_trailer,
       brp.ld_seal,
       brp.cr_name,
       brp.cr_addr1,
       brp.cr_addr2,
       brp.cr_city,
       brp.cr_state,
       brp.cr_postalcode,
       brp.cr_countrycode,
       brp.cu_name,
       brp.cu_addr1,
       brp.cu_addr2,
       brp.cu_city,
       brp.cu_state,
       brp.cu_postalcode,
       brp.cu_countrycode,
       brp.cr_scac,
       brp.oh_po,
       brp.ci_hazardous,
       brp.ci_descr,
       brp.oh_loadno,
       brp.strm_abbrev,
       brp.oh_reference,
       brp.st_abbrev,
       brp.car_name,
       brp.cod_amount,
       brp.custid,
       brp.fac_num,
       brp.oh_entrydate,
       brp.oh_arrivaldate,
       brp.oh_shipdate,
       brp.chemcode,
       brp.baseuom,
       cc.dotbolcomment,
       brp.oh_shiptype,
       cc.iatabolcomment,
       cc.imobolcomment,
       nvl((select drb.bolitmcomment
              from dre_rpt_bolitmcmtv4b drb
             where brp.oh_orderid=drb.orderid
               and brp.oh_shipid=drb.shipid
               and brp.od_item=drb.item
               and brp.od_lotnumber_null=drb.lotnumber),' ') as bolitmcomment,
       brp.oh_companycheckok,
       brp.oh_prono,
       max(brp.mfg_date) mfg_date,
       sum(brp.od_qty_order) od_qty_order,
       sum(brp.od_weightorder) od_weightorder,
       sum(brp.grossweight) grossweight,
       sum(brp.od_cube_order) od_cube_order,
       brp.sp_useritem1,
       brp.lineorder,
       brp.OH_CONSIGNEE,
       brp.OH_SHIPTO
  from (dre_bolrpt_prelim brp left outer join
        chemicalcodes cc on brp.chemcode=cc.chemcode)
 group by brp.oh_orderid,
       brp.oh_shipid,
       brp.od_item,
       brp.od_lotnumber,
       brp.od_lotnumber_null,
       brp.fac_name,
       brp.fac_addr1,
       brp.fac_addr2,
       brp.fac_city,
       brp.fac_state,
       brp.fac_postalcode,
       brp.cn_name,
       brp.cn_addr1,
       brp.cn_addr2,
       brp.cn_city,
       brp.cn_state,
       brp.cn_postalcode,
       brp.cn_countrycode,
       brp.ld_trailer,
       brp.ld_seal,
       brp.cr_name,
       brp.cr_addr1,
       brp.cr_addr2,
       brp.cr_city,
       brp.cr_state,
       brp.cr_postalcode,
       brp.cr_countrycode,
       brp.cu_name,
       brp.cu_addr1,
       brp.cu_addr2,
       brp.cu_city,
       brp.cu_state,
       brp.cu_postalcode,
       brp.cu_countrycode,
       brp.cr_scac,
       brp.oh_po,
       brp.ci_hazardous,
       brp.ci_descr,
       brp.oh_loadno,
       brp.strm_abbrev,
       brp.oh_reference,
       brp.st_abbrev,
       brp.car_name,
       brp.cod_amount,
       brp.custid,
       brp.fac_num,
       brp.oh_entrydate,
       brp.oh_arrivaldate,
       brp.oh_shipdate,
       brp.chemcode,
       brp.baseuom,
       cc.dotbolcomment,
       brp.oh_shiptype,
       cc.iatabolcomment,
       cc.imobolcomment,
       brp.oh_companycheckok,
       brp.oh_prono,
       brp.sp_useritem1,
       brp.lineorder,
       brp.OH_CONSIGNEE,
       brp.OH_SHIPTO
 order by brp.oh_orderid,
       brp.oh_shipid,
       brp.od_item,
       brp.od_lotnumber,
       brp.od_lotnumber_null;
comment on table DRE_BOLRPT_PRELIM2 is '$Id$';
exit;
