create or replace view dre_asofsummaryview as
SELECT 
    ASOFINVENTORY.FACILITY, ASOFINVENTORY.CUSTID, ASOFINVENTORY.ITEM, nvl(sum(ASOFINVENTORY.ADJUSTMENT), 0) as CURRENTQTY,
    nvl(sum(nvl(ASOFINVENTORY.WEIGHTADJUSTMENT,(zci.item_weight(ASOFINVENTORY.custid,ASOFINVENTORY.item,ASOFINVENTORY.uom) * ASOFINVENTORY.ADJUSTMENT))), 0) AS CURRENTWEIGHT,
    nvl(ASOFINVENTORY.LOTNUMBER,'NONE') as LOTNUMBER, ASOFINVENTORY.EFFDATE,
    nvl(INVENTORYSTATUS.ABBREV, decode(ASOFINVENTORY.INVSTATUS,'AV','Available','Unavailable')) as INVSTATUS, 1 as truelink,
    dre_asofinvactlotPKG.get_addlinfo(ASOFINVENTORY.CUSTID,ASOFINVENTORY.ITEM,ASOFINVENTORY.LOTNUMBER) as ADDLINFO,
    dre_asofinvactlotPKG.get_useritem(ASOFINVENTORY.CUSTID,ASOFINVENTORY.ITEM,ASOFINVENTORY.LOTNUMBER) as USERITEM,
    dre_asofinvactlotPKG.get_expdate(ASOFINVENTORY.CUSTID,ASOFINVENTORY.ITEM,ASOFINVENTORY.LOTNUMBER) as EXPDATE,
    dre_asofinvactlotPKG.get_mfgdate(ASOFINVENTORY.CUSTID,ASOFINVENTORY.ITEM,ASOFINVENTORY.LOTNUMBER) as MFGDATE,
    CI.DESCR
FROM ASOFINVENTORYDTL ASOFINVENTORY, INVENTORYSTATUS, CUSTITEM CI
where ASOFINVENTORY.inventoryclass = 'RG'
and ASOFINVENTORY.INVSTATUS = INVENTORYSTATUS.CODE (+)
and ASOFINVENTORY.CUSTID = CI.CUSTID
and ASOFINVENTORY.ITEM = CI.ITEM
group by
ASOFINVENTORY.FACILITY, ASOFINVENTORY.CUSTID, ASOFINVENTORY.ITEM, nvl(ASOFINVENTORY.LOTNUMBER,'NONE'),
	ASOFINVENTORY.EFFDATE, INVENTORYSTATUS.ABBREV, decode(ASOFINVENTORY.INVSTATUS,'AV','Available','Unavailable'),
  1, ASOFINVENTORY.LOTNUMBER,CI.DESCR
union
SELECT 
    ASOFINVENTORY.FACILITY, ASOFINVENTORY.CUSTID, ASOFINVENTORY.ITEM, nvl(sum(ASOFINVENTORY.ADJUSTMENT), 0) as CURRENTQTY,
    nvl(sum(nvl(ASOFINVENTORY.WEIGHTADJUSTMENT,(zci.item_weight(ASOFINVENTORY.custid,ASOFINVENTORY.item,ASOFINVENTORY.uom) * ASOFINVENTORY.ADJUSTMENT))), 0) AS CURRENTWEIGHT,
    nvl(ASOFINVENTORY.LOTNUMBER,'NONE') as LOTNUMBER, ASOFINVENTORY.EFFDATE,
    decode(ASOFINVENTORY.INVSTATUS,'AV','Unavailable',nvl(INVENTORYSTATUS.ABBREV,'Unavailable')) as INVSTATUS, 1 as truelink,
    dre_asofinvactlotPKG.get_addlinfo(ASOFINVENTORY.CUSTID,ASOFINVENTORY.ITEM,ASOFINVENTORY.LOTNUMBER) as ADDLINFO,
    dre_asofinvactlotPKG.get_useritem(ASOFINVENTORY.CUSTID,ASOFINVENTORY.ITEM,ASOFINVENTORY.LOTNUMBER) as USERITEM,
    dre_asofinvactlotPKG.get_expdate(ASOFINVENTORY.CUSTID,ASOFINVENTORY.ITEM,ASOFINVENTORY.LOTNUMBER) as EXPDATE,
    dre_asofinvactlotPKG.get_mfgdate(ASOFINVENTORY.CUSTID,ASOFINVENTORY.ITEM,ASOFINVENTORY.LOTNUMBER) as MFGDATE,
    CI.DESCR
FROM ASOFINVENTORYDTL  ASOFINVENTORY, INVENTORYSTATUS, CUSTITEM CI
where ASOFINVENTORY.inventoryclass <> 'RG'
and ASOFINVENTORY.INVSTATUS = INVENTORYSTATUS.CODE (+)
and ASOFINVENTORY.CUSTID = CI.CUSTID
and ASOFINVENTORY.ITEM = CI.ITEM
group by
ASOFINVENTORY.FACILITY, ASOFINVENTORY.CUSTID, ASOFINVENTORY.ITEM, nvl(ASOFINVENTORY.LOTNUMBER,'NONE'),
	ASOFINVENTORY.EFFDATE, decode(ASOFINVENTORY.INVSTATUS,'AV','Unavailable',nvl(INVENTORYSTATUS.ABBREV,'Unavailable')),
	1, ASOFINVENTORY.LOTNUMBER,CI.DESCR
union
select
    rh.tofacility, rh.custid, rd.item, nvl(sum(rd.qtyentered),0) as currentqty, nvl(sum(rd.weightorder),0) as currentweight,
    nvl(rd.lotnumber,'NONE') as lotnumber, trunc(oh.entrydate) as effdate, 'Arrived' as invstatus, 1 as truelink,
    dre_asofinvactlotPKG.get_addlinfo(rh.CUSTID,rd.ITEM,rd.LOTNUMBER) as ADDLINFO,
    dre_asofinvactlotPKG.get_useritem(rh.CUSTID,rd.ITEM,rd.LOTNUMBER) as USERITEM,
    dre_asofinvactlotPKG.get_expdate(rh.CUSTID,rd.ITEM,rd.LOTNUMBER) as EXPDATE,
    dre_asofinvactlotPKG.get_mfgdate(rh.CUSTID,rd.ITEM,rd.LOTNUMBER) as MFGDATE,
    ci.descr
from RECEIVERHDRVIEW rh, RECEIVERDTLVIEW rd, custitem ci, orderhdr oh
where rh.ordertype = 'R'
and rh.orderstatus = 'A'
and rh.orderid = rd.orderid
and rh.shipid = rd.shipid
and rh.custid = ci.custid
and rd.item = ci.item
and rh.ORDERHDRROWID = oh.rowid
group by
rh.tofacility, rh.custid, rd.item, nvl(rd.lotnumber,'NONE'), trunc(oh.entrydate), rd.lotnumber, ci.descr;
exit;
