create or replace view hppacklisthdr
(
       OH_orderid,
       OH_shipid,
       OH_entrydate,
       OH_apptdate,
       OH_shipdate,
       OH_po,
       OH_orderstatus,
       OH_billoflading,
       OH_arrivaldate,
       OH_loadno,
       OH_reference,
       OH_carrier,
       CN_name,
       CN_addr1,
       CN_addr2,
       CN_city,
       CN_state,
       CN_postalcode,
       CN_countrycode,
       CN_phone,
       CAR_name,
       CAR_scac,
       CU_name,
       CU_addr1,
       CU_addr2,
       CU_city,
       CU_state,
       CU_postalcode,
       CU_countrycode,
       FAC_name,
       FAC_addr1,
       FAC_addr2,
       FAC_city,
       FAC_state,
       FAC_postalcode,
       FAC_countrycode,
       LD_trailer,
       LD_seal,
       LD_prono,
       ST_abbrev,
       STRM_abbrev,
       OH_tax,
       OH_shipping,
       OH_total,
       OH_dateshipped,
       OH_warehouse,
       OH_company,
       OH_hdrpassthruchar15,
       OH_hdrpassthruchar16,
       OH_hdrpassthruchar17,
       OH_hdrpassthruchar18,
       OH_hdrpassthruchar19,
       OH_lastpicklabel,
       OH_packlistshipdate
)
as
select
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       OH.carrier,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shiptoname,null,CNS.phone, OH.shiptophone),
       CR.name,
       CR.scac,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ST.abbrev,
       STRM.abbrev,
       OH.hdrpassthruchar01,
       OH.hdrpassthruchar02,
       OH.hdrpassthruchar03,
       OH.dateshipped,
       OH.hdrpassthruchar06,
       OH.hdrpassthruchar05,
       OH.hdrpassthruchar15,
       OH.hdrpassthruchar16,
       OH.hdrpassthruchar17,
       OH.hdrpassthruchar18,
       OH.hdrpassthruchar19,
       zoe.last_pick_label(OH.orderid,OH.shipid),
       OH.packlistshipdate
from
    orderhdr OH,
    consignee CN,
    consignee CNS,
    carrier CR,
    customer CU,
    facility FAC,
    loads LD,
    shipmenttypes ST,
    shipmentterms STRM
where
    nvl(OH.consignee,OH.shipto) = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.custid = CU.custid(+) and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OH.shiptype = ST.code (+) and
    OH.shipterms = STRM.code (+) and
    (OH.orderstatus = '8' or
    OH.orderstatus = '9');

comment on table hppacklisthdr is '$Id$';

exit;

