create or replace view laboractivityview
(
    activity_type,
    name_id,
    event,
    evt_descr,
    task_time,
    task_time_text,
    beg_time,
    end_time,
    facility,
    facility_name,
    custid,
    cust_name,
    equip_code,
    equip_descr,
    qty,
    uom,
    uom_descr,
    base_qty,
    base_uom,
    base_uom_descr,
    weight,
    weight_per_hour,
    cube,
    cube_per_hour,
    units_per_hour,
    goal_per_hour,
    percent_goal,
    goal_uom,
    goal_uom_descr,
    order_id,
    ship_id,
    order_text,
    other_data,
    location,
    lpid,
    item,
    item_descr,
	employeecost,
	equipmentcost
)
as
select decode(UHV.EVENT,
          'DKLD','Loading',
          'DKUL','Loading',
          'LPLD','Loading',
          'LPUL','Loading',
          'LGIN','Login',
          'BADT','Picking',
          'BAPK','Picking',
          'CLIP','Picking',
          'CLPK','Picking',
          'CSPK','Picking',
          'MIPK','Picking',
          'PICK','Picking',
          'PKME','Picking',
          'PKNO','Picking',
          'PKOV','Picking',
          'SCPK','Picking',
          'SOPK','Picking',
          'STPK','Picking',
          'SYPK','Picking',
          'STGP',decode(UHV.etc,'RPPK','Replenishment','Picking'),
          'RPPK','Replenishment',
          'FGDR','Production',
          'SPTR','Production',
          'SPWK','Production',
          'WIPR','Production',
          'LPPA','Putaway',
          'PUTR','Putaway',
          'PUWK','Putaway',
          '1LIP','Receiving',
          '1STP','Receiving',
          'ALIP','Receiving',
          'ASNR','Receiving',
          'BPAL','Receiving',
          'BURT','Receiving',
          'BUUL','Receiving',
          'DRTN','Receiving',
          'DTRT','Receiving',
          'DUNK','Receiving',
          'RETR','Receiving',
          'RLPW','Receiving',
          'Other'),
       UHV.NAMEID,
       UHV.EVENT,
       UHV.EVENTABBREV,
       (UHV.ENDTIME - UHV.BEGTIME) * (60 * 60 * 24),
       to_char(floor((UHV.ENDTIME - UHV.BEGTIME) * 24),'00')||':'||
         trim(to_char(mod(floor((UHV.ENDTIME - UHV.BEGTIME) * 24 * 60), 60),'00'))||':'||
         trim(to_char(mod((UHV.ENDTIME - UHV.BEGTIME) * 24 * 60 * 60, 60),'00')),
       UHV.BEGTIME,
       UHV.ENDTIME,
       UHV.FACILITY,
       FA.NAME,
       UHV.CUSTID,
       CU.NAME,
       UHV.EQUIPMENT,
       UHV.EQUIPMENTABBREV,
       nvl(UHV.UNITS,0),
       UHV.UOM,
       UM1.ABBREV,
       nvl(zbut.translate_uom_function(UHV.CUSTID,UHV.ITEM,UHV.UNITS,UHV.UOM,CIT.BASEUOM),0),
       CIT.BASEUOM,
       UM2.ABBREV,
       UHV.WEIGHT,
       DECODE(UHV.ENDTIME - UHV.BEGTIME,0,0,to_number(to_char(UHV.WEIGHT / ((UHV.ENDTIME - UHV.BEGTIME) * (24)),'999999999999990.99'))),
       UHV.CUBE,
       DECODE(UHV.ENDTIME - UHV.BEGTIME,0,0,to_number(to_char(UHV.CUBE / ((UHV.ENDTIME - UHV.BEGTIME) * (24)),'999999999999990.99'))),
       DECODE(UHV.ENDTIME - UHV.BEGTIME,0,0,to_number(to_char(nvl(decode(GT.MEASURE,
       null,zbut.translate_uom_function(UHV.CUSTID,UHV.ITEM,UHV.UNITS,UHV.UOM,CIT.BASEUOM),'WGHT',UHV.WEIGHT,'CUBE',UHV.CUBE,
	     zbut.translate_uom_function(UHV.CUSTID,UHV.ITEM,UHV.UNITS,UHV.UOM,GT.UOM)),0) / ((UHV.ENDTIME - UHV.BEGTIME) * (24)),'999999999999990.99'))),
       NVL(GT.QTYPERHOUR,0),
       DECODE(NVL(GT.QTYPERHOUR,0),0,0,DECODE(UHV.ENDTIME - UHV.BEGTIME,0,0,to_number(to_char((nvl(
         decode(GT.MEASURE,'WGHT',UHV.WEIGHT,'CUBE',UHV.CUBE,zbut.translate_uom_function(UHV.CUSTID,UHV.ITEM,UHV.UNITS,UHV.UOM,GT.UOM)),0) * 100) /
         ((UHV.ENDTIME - UHV.BEGTIME) * 24 * GT.QTYPERHOUR),'999999999999990.99')))),
       decode(GT.MEASURE,'WGHT','-','CUBE','-',GT.UOM),
       decode(GT.MEASURE,'WGHT','Weight','CUBE','Cube',UM3.ABBREV),
       UHV.ORDERID,
       UHV.SHIPID,
       decode(nvl(UHV.ORDERID,0),0,'None',UHV.ORDERID||'-'||UHV.SHIPID),
       UHV.ETC,
       UHV.LOCATION,
       UHV.LPID,
       UHV.ITEM,
       CIT.DESCR,
	   UHV.EMPLOYEECOST,
	   UHV.EQUIPMENTCOST
  FROM userhistoryactivityview UHV,
       customer CU,
       custitem CIT,
       facility FA,
       goaltime GT,
       unitsofmeasure UM1,
       unitsofmeasure UM2,
       unitsofmeasure UM3
 WHERE UHV.CUSTID = CU.CUSTID(+)
   AND UHV.CUSTID = CIT.CUSTID(+)
   AND UHV.ITEM = CIT.ITEM(+)
   AND UHV.FACILITY = FA.FACILITY(+)
   AND UHV.FACILITY = GT.FACILITY(+)
   AND UHV.CUSTID = GT.CUSTID(+)
   AND UHV.EVENT = GT.CATEGORY(+)
   AND UHV.UOM = UM1.CODE(+)
   AND CIT.BASEUOM = UM2.CODE(+)
   AND GT.UOM = UM3.CODE(+);

comment on table laboractivityview is '$Id$';

exit;
