create or replace view lbl_ucc128_plt_view
(
   lpid,
   sscc18,
   shiptoname,
   shiptoaddr1,
   shiptoaddr2,
   shiptocity,
   shiptostate,
   shiptopostalcode,
   shiptocountrycode,
   shiptoconcataddr,
   dc,
   carriername,
   carriercode,
   shipdate,
   orderid,
   shipid,
   item,
   wmit,
   po,
   reference,
   loadno,
   prono,
   bol,
   custname,
   custaddr1,
   custaddr2,
   custcity,
   custstate,
   custpostalcode,
   custcountrycode,
   custconcataddr,
   whsename,
   whseaddr1,
   whseaddr2,
   whsecity,
   whsestate,
   whsepostalcode,
   whsecountrycode,
   hdrpassthruchar01,
   hdrpassthruchar02,
   hdrpassthruchar03,
   hdrpassthruchar04,
   hdrpassthruchar05,
   hdrpassthruchar06,
   hdrpassthruchar07,
   hdrpassthruchar08,
   hdrpassthruchar09,
   hdrpassthruchar10,
   hdrpassthruchar11,
   hdrpassthruchar12,
   hdrpassthruchar13,
   hdrpassthruchar14,
   hdrpassthruchar15,
   hdrpassthruchar16,
   hdrpassthruchar17,
   hdrpassthruchar18,
   hdrpassthruchar19,
   hdrpassthruchar20,
   hdrpassthrunum01,
   hdrpassthrunum02,
   hdrpassthrunum03,
   hdrpassthrunum04,
   hdrpassthrunum05,
   hdrpassthrunum06,
   hdrpassthrunum07,
   hdrpassthrunum08,
   hdrpassthrunum09,
   hdrpassthrunum10
)
as
select distinct
   SP.lpid,
   zedi.get_sscc18_code(OH.custid,'1',SP.lpid),
   decode(CN.consignee, null, OH.shiptoname, CN.name),
   decode(CN.consignee, null, OH.shiptoaddr1, CN.addr1),
   decode(CN.consignee, null, OH.shiptoaddr2, CN.addr2),
   decode(CN.consignee, null, OH.shiptocity, CN.city),
   decode(CN.consignee, null, OH.shiptostate, CN.state),
   decode(CN.consignee, null, OH.shiptopostalcode, CN.postalcode),
   decode(CN.consignee, null, OH.shiptocountrycode, CN.countrycode),
   decode(CN.consignee, null, OH.shiptocity, CN.city)||', '||decode(CN.consignee, null,
     OH.shiptostate, CN.state)||' '||decode(CN.consignee, null, OH.shiptopostalcode,
     CN.postalcode)||' '||decode(CN.consignee, null, OH.shiptocountrycode, CN.countrycode),
   substr(decode(CN.consignee, null, OH.shiptoname, CN.name),
          instr(decode(CN.consignee, null, OH.shiptoname, CN.name),'DC',-1)),
   CA.name,
   CA.carrier,
   OH.shipdate,
   SP.orderid,
   SP.shipid,
   SP.item,
   nvl(OD.consigneesku, WM.wmit),
   OH.po,
   OH.reference,
   OH.loadno,
   L.prono,
   SP.orderid||'-'||SP.shipid,
   CU.name,
   CU.addr1,
   CU.addr2,
   CU.city,
   CU.state,
   CU.postalcode,
   CU.countrycode,
   CU.city||', '||CU.state||' '||CU.postalcode||' '||CU.countrycode,
   FA.name,
   FA.addr1,
   FA.addr2,
   FA.city,
   FA.state,
   FA.postalcode,
   FA.countrycode,
   OH.hdrpassthruchar01,
   OH.hdrpassthruchar02,
   OH.hdrpassthruchar03,
   OH.hdrpassthruchar04,
   OH.hdrpassthruchar05,
   OH.hdrpassthruchar06,
   OH.hdrpassthruchar07,
   OH.hdrpassthruchar08,
   OH.hdrpassthruchar09,
   OH.hdrpassthruchar10,
   OH.hdrpassthruchar11,
   OH.hdrpassthruchar12,
   OH.hdrpassthruchar13,
   OH.hdrpassthruchar14,
   OH.hdrpassthruchar15,
   OH.hdrpassthruchar16,
   OH.hdrpassthruchar17,
   OH.hdrpassthruchar18,
   OH.hdrpassthruchar19,
   OH.hdrpassthruchar20,
   OH.hdrpassthrunum01,
   OH.hdrpassthrunum02,
   OH.hdrpassthrunum03,
   OH.hdrpassthrunum04,
   OH.hdrpassthrunum05,
   OH.hdrpassthrunum06,
   OH.hdrpassthrunum07,
   OH.hdrpassthrunum08,
   OH.hdrpassthrunum09,
   OH.hdrpassthrunum10
from orderhdr OH,
     orderdtl OD,
     loads L,
     carrier CA,
     consignee CN,
     customer CU,
     facility FA,
     custitemwmitview WM,
     shippingplate SP
where OH.shipto = CN.consignee(+)
  and OH.orderid = SP.orderid
  and OH.shipid = SP.shipid
  and OH.ordertype = 'O'
  and SP.type in ('M','F','C')
  and SP.parentlpid is null
  and SP.loadno = L.loadno(+)
  and SP.orderid = OD.orderid(+)
  and SP.shipid = OD.shipid(+)
  and SP.orderitem = OD.item(+)
  and SP.custid = WM.custid(+)
  and SP.item = WM.item(+)
  and nvl(SP.orderlot,'<none>') = nvl(OD.lotnumber(+),'<none>')
  and OH.carrier = CA.carrier(+)
  and OH.custid = CU.custid(+)
  and OH.fromfacility = FA.facility(+);
  
comment on table lbl_ucc128_plt_view is '$Id';
  
--exit;


