CREATE OR REPLACE VIEW LBL_BURCOATFACT_VIEW
(SSCC, SSCCFMT, LPID, PICKTOLP, ORDERID, 
 SHIPID, LOADNO, WAVE, ITEM, ITEMDESCR, 
 QUANTITY, WEIGHT, SEQ, SEQOF, LBLTYPE, 
 CREATED, SHIPTONAME, SHIPTOCONTACT, SHIPTOADDR1, SHIPTOADDR2, 
 SHIPTOCITY, SHIPTOSTATE, SHIPTOZIP, SHIPTOCOUNTRYCODE, FROMFACILITY, 
 FROMADDR1, FROMADDR2, FROMCITY, FROMSTATE, FROMZIP, 
 SHIPFROMCOUNTRYCODE, PRO, BOL, PO, REFERENCE, 
 CARRIERNAME, SCAC, LOTNUMBER, SHIPPINGTYPE, CUSTID, 
 FACILITY, MARKFORNAME, STORENUM, MARKFORADDR1, MARKFORADDR2, 
 MARKFORCITY, MARKFORSTATE, MARKFORZIP, MARKFORCOUNTRYCODE, DEPARTMENT, 
 DIVISION, HDRPASSCHAR11, HDRPASSCHAR12, HDRPASSCHAR13, HDRPASSCHAR14, 
 HDRPASSCHAR15, HDRPASSCHAR16, HDRPASSCHAR17, HDRPASSCHAR18, HDRPASSCHAR19, 
 HDRPASSCHAR20, HDRPASSNUM01, HDRPASSNUM02, HDRPASSNUM03, HDRPASSNUM04, 
 HDRPASSNUM05, HDRPASSNUM06, HDRPASSNUM07, HDRPASSNUM08, HDRPASSNUM09, 
 HDRPASSNUM10, HDRPASSDATE01, HDRPASSDATE02, HDRPASSDATE03, HDRPASSDATE04, 
 HDRPASSDOLL01, HDRPASSDOLL02, UPCCODE, CUSTITEM, ITEMSIZE, 
 DTLPASSCHAR04, DTLPASSCHAR05, DTLPASSCHAR06, SIZELIST, QTYLIST, 
 DTLPASSCHAR09, DTLPASSCHAR10, DTLPASSCHAR11, DTLPASSCHAR12, DTLPASSCHAR13, 
 DTLPASSCHAR14, DTLPASSCHAR15, DTLPASSCHAR16, DTLPASSCHAR17, DTLPASSCHAR18, 
 DTLPASSCHAR19, DTLPASSCHAR20, DTLPASSNUM01, DTLPASSNUM02, DTLPASSNUM03, 
 DTLPASSNUM04, DTLPASSNUM05, DTLPASSNUM06, DTLPASSNUM07, DTLPASSNUM08, 
 DTLPASSNUM09, DTLPASSNUM10, DTLPASSDATE01, DTLPASSDATE02, DTLPASSDATE03, 
 DTLPASSDATE04, DTLPASSDOLL01, DTLPASSDOLL02, VENDORITEM, UPC, 
 ZIPCODEBAR, ZIPCODEHUMAN, STOREBARCODE, STOREHUMAN, VENDORBAR, 
 VENDORHUMAN, SHIPTOCSZ, SHIPFROMCSZ, CHANGED, LBLTYPEDESC)
AS 
SELECT
   sscc,
   ssccfmt,
   lpid,
   picktolp,
   orderid,
   shipid,
   loadno,
   wave,
   item,
   itemdescr,
   quantity,
   weight,
   seq,
   seqof,
   lbltype,
   created,
   shiptoname,
   shiptocontact,
   shiptoaddr1,
   shiptoaddr2,
   shiptocity,
   shiptostate,
   shiptozip,
   shiptocountrycode,
   fromfacility,
   fromaddr1,
   fromaddr2,
   fromcity,
   fromstate,
   fromzip,
   shipfromcountrycode,
   pro,
   bol,
   po,
   reference,
   carriername,
   scac,
   lotnumber,
   shippingtype,
   custid,
   facility,
   hdrpasschar01,
   hdrpasschar02,
   hdrpasschar03,
   hdrpasschar04,
   hdrpasschar05,
   hdrpasschar06,
   hdrpasschar07,
   hdrpasschar08,
   hdrpasschar09,
   hdrpasschar10,
   hdrpasschar11,
   hdrpasschar12,
   hdrpasschar13,
   hdrpasschar14,
   hdrpasschar15,
   hdrpasschar16,
   hdrpasschar17,
   hdrpasschar18,
   hdrpasschar19,
   hdrpasschar20,
   hdrpassnum01,
   hdrpassnum02,
   hdrpassnum03,
   hdrpassnum04,
   hdrpassnum05,
   hdrpassnum06,
   hdrpassnum07,
   hdrpassnum08,
   hdrpassnum09,
   hdrpassnum10,
   hdrpassdate01,
   hdrpassdate02,
   hdrpassdate03,
   hdrpassdate04,
   hdrpassdoll01,
   hdrpassdoll02,
   dtlpasschar01,
   dtlpasschar02,
   dtlpasschar03,
   dtlpasschar04,
   dtlpasschar05,
   dtlpasschar06,
   dtlpasschar07,
   dtlpasschar08,
   dtlpasschar09,
   dtlpasschar10,
   dtlpasschar11,
   dtlpasschar12,
   dtlpasschar13,
   dtlpasschar14,
   dtlpasschar15,
   dtlpasschar16,
   dtlpasschar17,
   dtlpasschar18,
   dtlpasschar19,
   dtlpasschar20,
   dtlpassnum01,
   dtlpassnum02,
   dtlpassnum03,
   dtlpassnum04,
   dtlpassnum05,
   dtlpassnum06,
   dtlpassnum07,
   dtlpassnum08,
   dtlpassnum09,
   dtlpassnum10,
   dtlpassdate01,
   dtlpassdate02,
   dtlpassdate03,
   dtlpassdate04,
   dtlpassdoll01,
   dtlpassdoll02,
   consigneesku,
   upc,
   zipcodebar,
   zipcodehuman,
   '91'||hdrpasschar05,
   '(91)'||hdrpasschar05,
   '90'||hdrpasschar01,
   '(90)'||hdrpasschar01,
   shiptocsz,
   shipfromcsz,
   changed,
   lbltypedesc
  from ucc_standard_labels;

exit;
