CREATE OR REPLACE VIEW LBL_AMAZONGEN_VIEW
(SSCC, SSCCFMT, LPID, PICKTOLP, ORDERID,
 SHIPID, LOADNO, WAVE, ITEM, ITEMDESCR,
 QUANTITY, WEIGHT, SEQ, SEQOF, LBLTYPE,
 CREATED, SHIPTONAME, SHIPTOCONTACT, SHIPTOADDR1, SHIPTOADDR2,
 SHIPTOCITY, SHIPTOSTATE, SHIPTOZIP, SHIPTOCOUNTRYCODE, FROMFACILITY,
 FROMADDR1, FROMADDR2, FROMCITY, FROMSTATE, FROMZIP,
 SHIPFROMCOUNTRYCODE, PRO, BOL, PO, REFERENCE,
 CARRIERNAME, SCAC, LOTNUMBER, SHIPPINGTYPE, CUSTID,
 FACILITY, MARKFORNAME, STORENUM, MARKFORADDR1, MARKFORADDR2,
 MARKFORCITY, MARKFORSTATE, MARKFORZIP, MARKFORCOUNTRYCODE, DEPARTMENT,
 DIVISION, HDRPASSCHAR11, HDRPASSCHAR12, HDRPASSCHAR13, HDRPASSCHAR14,
 HDRPASSCHAR15, HDRPASSCHAR16, HDRPASSCHAR17, HDRPASSCHAR18, HDRPASSCHAR19,
 HDRPASSCHAR20, HDRPASSNUM01, HDRPASSNUM02, HDRPASSNUM03, HDRPASSNUM04,
 HDRPASSNUM05, HDRPASSNUM06, HDRPASSNUM07, HDRPASSNUM08, HDRPASSNUM09,
 HDRPASSNUM10, HDRPASSDATE01, HDRPASSDATE02, HDRPASSDATE03, HDRPASSDATE04,
 HDRPASSDOLL01, HDRPASSDOLL02, UPCCODE, CUSTITEM, ITEMSIZE,
 DTLPASSCHAR04, STYLE, DTLPASSCHAR06, DTLPASSCHAR07, DTLPASSCHAR08,
 DTLPASSCHAR09, DTLPASSCHAR10, DTLPASSCHAR11, DTLPASSCHAR12, DTLPASSCHAR13,
 DTLPASSCHAR14, DTLPASSCHAR15, DTLPASSCHAR16, DTLPASSCHAR17, DTLPASSCHAR18,
 DTLPASSCHAR19, DTLPASSCHAR20, DTLPASSNUM01, DTLPASSNUM02, DTLPASSNUM03,
 DTLPASSNUM04, DTLPASSNUM05, DTLPASSNUM06, DTLPASSNUM07, DTLPASSNUM08,
 DTLPASSNUM09, DTLPASSNUM10, DTLPASSDATE01, DTLPASSDATE02, DTLPASSDATE03,
 DTLPASSDATE04, DTLPASSDOLL01, DTLPASSDOLL02, VENDORITEM, UPC,
 ZIPCODEBAR, ZIPCODEHUMAN, STOREBARCODE, STOREHUMAN, VENDORBAR,
 VENDORHUMAN, SHIPTOCSZ, SHIPFROMCSZ, CHANGED, LBLTYPEDESC,
 PART, CUSTNAME)
AS
SELECT
  U.sscc,
  U.ssccfmt,
  U.lpid,
  U.picktolp,
  U.orderid,
  U.shipid,
  U.loadno,
  U.wave,
  U.item,
  U.itemdescr,
  U.quantity,
  U.weight,
  U.seq,
  U.seqof,
  U.lbltype,
  U.created,
  U.shiptoname,
  U.shiptocontact,
  U.shiptoaddr1,
  U.shiptoaddr2,
  U.shiptocity,
  U.shiptostate,
  U.shiptozip,
  U.shiptocountrycode,
  U.fromfacility,
  U.fromaddr1,
  U.fromaddr2,
  U.fromcity,
  U.fromstate,
  U.fromzip,
  U.shipfromcountrycode,
  U.pro,
  U.bol,
  U.po,
  U.reference,
  U.carriername,
  U.scac,
  U.lotnumber,
  U.shippingtype,
  U.custid,
  U.facility,
  U.hdrpasschar01,
  U.hdrpasschar20,
  U.hdrpasschar03,
  U.hdrpasschar04,
  U.hdrpasschar05,
  U.hdrpasschar06,
  U.hdrpasschar07,
  U.hdrpasschar08,
  U.hdrpasschar08,
  U.hdrpasschar10,
  U.hdrpasschar11,
  U.hdrpasschar12,
  U.hdrpasschar13,
  U.hdrpasschar14,
  U.hdrpasschar15,
  U.hdrpasschar16,
  U.hdrpasschar17,
  U.hdrpasschar18,
  U.hdrpasschar19,
  U.hdrpasschar20,
  U.hdrpassnum01,
  U.hdrpassnum02,
  U.hdrpassnum03,
  U.hdrpassnum04,
  U.hdrpassnum05,
  U.hdrpassnum06,
  U.hdrpassnum07,
  U.hdrpassnum08,
  U.hdrpassnum09,
  U.hdrpassnum10,
  U.hdrpassdate01,
  U.hdrpassdate02,
  U.hdrpassdate03,
  U.hdrpassdate04,
  U.hdrpassdoll01,
  U.hdrpassdoll02,
  U.dtlpasschar01,
  U.dtlpasschar02,
  U.dtlpasschar03,
  U.dtlpasschar04,
  U.dtlpasschar05,
  U.dtlpasschar06,
  U.dtlpasschar07,
  U.dtlpasschar08,
  U.dtlpasschar09,
  U.dtlpasschar10,
  U.dtlpasschar11,
  U.dtlpasschar12,
  U.dtlpasschar13,
  U.dtlpasschar14,
  U.dtlpasschar15,
  U.dtlpasschar16,
  U.dtlpasschar17,
  U.dtlpasschar18,
  U.dtlpasschar19,
  U.dtlpasschar20,
  U.dtlpassnum01,
  U.dtlpassnum02,
  U.dtlpassnum03,
  U.dtlpassnum04,
  U.dtlpassnum05,
  U.dtlpassnum06,
  U.dtlpassnum07,
  U.dtlpassnum08,
  U.dtlpassnum09,
  U.dtlpassnum10,
  U.dtlpassdate01,
  U.dtlpassdate02,
  U.dtlpassdate03,
  U.dtlpassdate04,
  U.dtlpassdoll01,
  U.dtlpassdoll02,
  U.consigneesku,
  U.dtlpasschar01,
  U.zipcodebar,
  U.zipcodehuman,
  '91'||U.hdrpasschar20,
  '(91)'||U.hdrpasschar20,
  '90'||U.hdrpasschar01,
  '(90)'||U.hdrpasschar01,
  U.shiptocsz,
  U.shipfromcsz,
  U.changed,
  U.lbltypedesc,
  U.part,
  C.name
  from ucc_standard_labels U, customer C
    where U.custid = C.custid(+);

comment on table lbl_amazongen_view is '$Id';

exit;
