create or replace view ldarrivalorderview
(
   lpid,
   item,
   custid,
   facility,
   location,
   status,
   holdreason,
   unitofmeasure,
   quantity,
   type,
   serialnumber,
   lotnumber,
   creationdate,
   manufacturedate,
   expirationdate,
   expiryaction,
   lastcountdate,
   po,
   recmethod,
   condition,
   lastoperator,
   lasttask,
   fifodate,
   destlocation,
   destfacility,
   countryof,
   parentlpid,
   useritem1,
   useritem2,
   useritem3,
   disposition,
   lastuser,
   lastupdate,
   invstatus,
   qtyentered,
   itementered,
   uomentered,
   inventoryclass,
   loadno,
   stopno,
   shipno,
   orderid,
   shipid,
   weight,
   adjreason,
   qtyrcvd,
   controlnumber,
   qcdisposition,
   fromlpid,
   dropseq,
   fromshippinglpid,
   workorderseq,
   workordersubseq,
   qtytasked,
   childfacility,
   childitem,
   parentfacility,
   parentitem,
   prevlocation,
   custname,
   itemdescr,
   seq,
   seqof,
   dateprinted,
   timeprinted,
--PRN: 4889 Add reference field from orderhdr and itembc for the item barcode
   itembc,
   container,
--
   dtlpassthruchar01,
   dtlpassthruchar02,
   dtlpassthruchar03,
   dtlpassthruchar04,
   dtlpassthruchar05,
   dtlpassthruchar06,
   dtlpassthruchar07,
   dtlpassthruchar08,
   dtlpassthruchar09,
   dtlpassthruchar10
)
as
select
   PL.lpid,
   PL.item,
   PL.custid,
   PL.facility,
   PL.location,
   PL.status,
   PL.holdreason,
   PL.unitofmeasure,
   PL.quantity,
   PL.type,
   PL.serialnumber,
   PL.lotnumber,
   PL.creationdate,
   PL.manufacturedate,
   PL.expirationdate,
   PL.expiryaction,
   PL.lastcountdate,
   PL.po,
   PL.recmethod,
   PL.condition,
   PL.lastoperator,
   PL.lasttask,
   PL.fifodate,
   PL.destlocation,
   PL.destfacility,
   PL.countryof,
   PL.parentlpid,
   PL.useritem1,
   PL.useritem2,
   PL.useritem3,
   PL.disposition,
   PL.lastuser,
   PL.lastupdate,
   PL.invstatus,
   PL.qtyentered,
   PL.itementered,
   PL.uomentered,
   PL.inventoryclass,
   PL.loadno,
   PL.stopno,
   PL.shipno,
   PL.orderid,
   PL.shipid,
   PL.weight,
   PL.adjreason,
   PL.qtyrcvd,
   PL.controlnumber,
   PL.qcdisposition,
   PL.fromlpid,
   PL.dropseq,
   PL.fromshippinglpid,
   PL.workorderseq,
   PL.workordersubseq,
   PL.qtytasked,
   PL.childfacility,
   PL.childitem,
   PL.parentfacility,
   PL.parentitem,
   PL.prevlocation,
   CU.name,
   CI.descr,
   row_number() over (partition by PL.orderid, PL.shipid order by null),
   count(*) over (partition by PL.orderid, PL.shipid),
   to_char(sysdate, 'MM/DD/RR'),
   to_char(sysdate, 'HH:MI AM'),
--PRN: 4889 Add reference field from orderhdr and itembc for label.
   PL.item,
   oh.reference,
   OD.dtlpassthruchar01,
   OD.dtlpassthruchar02,
   OD.dtlpassthruchar03,
   OD.dtlpassthruchar04,
   OD.dtlpassthruchar05,
   OD.dtlpassthruchar06,
   OD.dtlpassthruchar07,
   OD.dtlpassthruchar08,
   OD.dtlpassthruchar09,
   OD.dtlpassthruchar10
from orderhdr oh,
     orderdtl OD,
     plate PL,
     customer CU,
     custitem CI
where CU.custid = PL.custid
  and CI.custid = PL.custid
  and CI.item = PL.item
  and oh.orderid(+) = PL.orderid
  and oh.shipid(+) = PL.shipid
  and OD.orderid(+) = PL.orderid
  and OD.shipid(+) = PL.shipid
  and OD.item(+) = PL.item
  and nvl(OD.lotnumber(+), '(none)') = nvl(PL.lotnumber,'(none)')
--
order by PL.lpid;

comment on table ldarrivalorderview is '$Id';

exit;
