CREATE OR REPLACE VIEW MBOLRPT ( OH_CUSTID,
OH_ORDERID, OH_SHIPID, OH_ENTRYDATE, OH_APPTDATE,
OH_SHIPDATE, OH_PO, OH_ORDERSTATUS, OH_BILLOFLADING,
OH_ARRIVALDATE, OH_LOADNO, OH_STOPNO, OH_REFERENCE,
CN_NAME, CN_ADDR1, CN_ADDR2, CN_CITY,
CN_STATE, CN_POSTALCODE, CN_COUNTRYCODE, CR_NAME,
CR_ADDR1, CR_ADDR2, CR_CITY, CR_STATE,
CR_POSTALCODE, CR_COUNTRYCODE, CR_SCAC, CU_NAME,
CU_ADDR1, CU_ADDR2, CU_CITY, CU_STATE,
CU_POSTALCODE, CU_COUNTRYCODE, FAC_NAME, FAC_ADDR1,
FAC_ADDR2, FAC_CITY, FAC_STATE, FAC_POSTALCODE,
FAC_COUNTRYCODE, LD_TRAILER, LD_SEAL, LD_PRONO,
LD_CARRIER, LD_CUBESHIP, BC_BOLCOMMENT, ST_SHIPTERM,
STYP_SHIPTYPE, ORDER_CARTONS, LD_OB_ARRIVALDATE,
SHIPTO_ORDER_COUNT
) AS select
       OH.custid,
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.stopno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.scac,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       nvl(LD.carrier,OH.carrier),
       LD.cubeship,
       BC.bolcomment,
       ST.descr,
       STYP.descr,
       ordercheckview_cartons(OH.orderid, OH.shipid),
       zld.outbound_arrivaldate(LD.loadno),
       (select count(1)
          from orderhdr
         where loadno=OH.loadno
           and ((shipto=OH.shipto)
            or  (shiptoname=OH.shiptoname
           and   shiptoaddr1=OH.shiptoaddr1))) shipto_order_count
from
    orderhdr OH,
    consignee CN,
    consignee CNS,
    carrier CR,
    customer CU,
    facility FAC,
    loads LD,
    loadsbolcommentsview BC,
    shipmentterms ST,
    shipmenttypes STYP
where
    OH.consignee = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.custid = CU.custid(+) and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OH.loadno = BC.loadno(+) and
    OH.shiptype = STYP.code(+) and
    OH.shipterms = ST.code(+)	and
    1 <
      (select count(1)
         from orderhdr
        where loadno = OH.loadno
          and custid = OH.custid);

comment on table MBOLRPT is '$Id$';
          
CREATE OR REPLACE VIEW UNI_MBOLRPT ( OH_CUSTID,
OH_ORDERID, OH_SHIPID, OH_ENTRYDATE, OH_APPTDATE,
OH_SHIPDATE, OH_PO, OH_ORDERSTATUS, OH_BILLOFLADING,
OH_ARRIVALDATE, OH_LOADNO, OH_STOPNO, OH_REFERENCE,
CN_NAME, CN_ADDR1, CN_ADDR2, CN_CITY,
CN_STATE, CN_POSTALCODE, CN_COUNTRYCODE, CR_NAME,
CR_ADDR1, CR_ADDR2, CR_CITY, CR_STATE,
CR_POSTALCODE, CR_COUNTRYCODE, CR_SCAC, CU_NAME,
CU_ADDR1, CU_ADDR2, CU_CITY, CU_STATE,
CU_POSTALCODE, CU_COUNTRYCODE, FAC_NAME, FAC_ADDR1,
FAC_ADDR2, FAC_CITY, FAC_STATE, FAC_POSTALCODE,
FAC_COUNTRYCODE, LD_TRAILER, LD_SEAL, LD_PRONO,
LD_CARRIER, LD_CUBESHIP, BC_BOLCOMMENT, ST_SHIPTERM,
STYP_SHIPTYPE, ORDER_CARTONS, SHIPTO_ORDER_COUNT
) AS select
       OH.custid,
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.stopno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.scac,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       nvl(LD.carrier,OH.carrier),
       LD.cubeship,
       BC.bolcomment,
       ST.descr,
       STYP.descr,
       ordercheckview_cartons(OH.orderid, OH.shipid),
       (select count(1)
          from orderhdr
         where loadno=OH.loadno
           and ((shipto=OH.shipto)
            or  (shiptoname=OH.shiptoname
           and   shiptoaddr1=OH.shiptoaddr1))) shipto_order_count
from
    orderhdr OH,
    consignee CN,
    consignee CNS,
    carrier CR,
    customer CU,
    facility FAC,
    loads LD,
    loadsbolcommentsview BC,
    shipmentterms ST,
    shipmenttypes STYP
where
    OH.consignee = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.custid = CU.custid(+) and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OH.loadno = BC.loadno(+) and
    OH.shiptype = STYP.code(+) and
    OH.shipterms = ST.code(+);

comment on table UNI_MBOLRPT is '$Id$';
          
 exit;
