
CREATE OR REPLACE VIEW PACAM_SHIPPINGPLATE_TYPEFPVIEW ( LPID, 
ITEM, CUSTID, FACILITY, LOCATION, 
STATUS, HOLDREASON, UNITOFMEASURE, QUANTITY, 
TYPE, FROMLPID, SERIALNUMBER, LOTNUMBER, 
PARENTLPID, USERITEM1, USERITEM2, USERITEM3, 
LASTUSER, LASTUPDATE, INVSTATUS, QTYENTERED, 
ORDERITEM, UOMENTERED, INVENTORYCLASS, LOADNO, 
STOPNO, SHIPNO, ORDERID, SHIPID, 
WEIGHT, UCC128, LABELFORMAT, TASKID, 
DROPSEQ, ORDERLOT, PICKUOM, PICKQTY, 
TRACKINGNO, CARTONSEQ, CHECKED, TOTELPID, 
CARTONTYPE, PICKEDFROMLOC, SHIPPINGCOST, CARRIERCODEUSED, 
SATDELIVERYUSED, OPENFACILITY, AUDITED, PREVLOCATION, 
FROMLPIDPARENT, RMATRACKINGNO, ACTUALCARRIER ) AS SELECT  
  LPID, ITEM, CUSTID,  
  FACILITY, LOCATION, STATUS,  
  HOLDREASON, UNITOFMEASURE, QUANTITY,  
  TYPE, FROMLPID, SERIALNUMBER,  
  LOTNUMBER, PARENTLPID, USERITEM1,  
  USERITEM2, USERITEM3, LASTUSER,  
  LASTUPDATE, INVSTATUS, QTYENTERED,  
  ORDERITEM, UOMENTERED, INVENTORYCLASS,  
  LOADNO, STOPNO, SHIPNO,  
  ORDERID, SHIPID, WEIGHT,  
  UCC128, LABELFORMAT, TASKID,  
  DROPSEQ, ORDERLOT, PICKUOM,  
  PICKQTY, TRACKINGNO, CARTONSEQ,  
  CHECKED, TOTELPID, CARTONTYPE,  
  PICKEDFROMLOC, SHIPPINGCOST, CARRIERCODEUSED,  
  SATDELIVERYUSED, OPENFACILITY, AUDITED,  
  PREVLOCATION, FROMLPIDPARENT, RMATRACKINGNO,  
  ACTUALCARRIER 
FROM  
  SHIPPINGPLATE 
WHERE TYPE in ('F','P');

comment on table PACAM_SHIPPINGPLATE_TYPEFPVIEW is '$Id$';

exit;
