create or replace view tasksview
(TASKID,                       
TASKTYPE,                     
FACILITY,                     
FROMSECTION,                  
FROMLOC,                      
FROMPROFILE,                  
TOSECTION,                    
TOLOC,                        
TOPROFILE,                    
TOUSERID,                     
CUSTID,                       
ITEM,                         
LPID,                         
UOM,                          
QTY,                          
LOCSEQ,                       
LOADNO,                       
STOPNO,                       
SHIPNO,                       
ORDERID,                      
SHIPID,                       
ORDERITEM,                    
ORDERLOT,                     
PRIORITY,                     
PREVPRIORITY,                 
CURRUSERID,                   
LASTUSER,                     
LASTUPDATE,                   
tasktypeabbrev,
priorityabbrev,
wave,
pickuom,
pickuomabbrev,
pickqty,
picktotype,
picktotypeabbrev,
cartontype,
cartontypeabbrev,
pickingzone,
weight,
cube,
staffhrs,
fmtstaffhrs,
tasksrowid,
apptdate,
carrier,
deliveryservice,
shiptoname,
weight_kgs,
orderstatus,
manual_picks_yn,
crush_factor,
uom_pick_seq
)
as
select
TASKID,
TASKTYPE,
FACILITY,
FROMSECTION,
FROMLOC,
FROMPROFILE,
TOSECTION,
TOLOC,
TOPROFILE,
TOUSERID,
tasks.CUSTID,
zbbb.tasksview_item(tasks.wave,tasks.taskid,tasks.tasktype,tasks.item),
LPID,
UOM,
QTY,                          
LOCSEQ,                       
tasks.LOADNO,
tasks.STOPNO,
tasks.SHIPNO,
tasks.ORDERID,
tasks.SHIPID,
ORDERITEM,
ORDERLOT,
tasks.PRIORITY,
PREVPRIORITY,
CURRUSERID,
tasks.LASTUSER,
tasks.LASTUPDATE,
tasktypes.abbrev,
taskpriorities.abbrev,
tasks.wave,
pickuom,
unitsofmeasure.abbrev,
pickqty,
picktotype,
picktotypes.abbrev,
cartontype,
cartontypes.abbrev,
pickingzone,
weight,
cube,
tasks.staffhrs,
substr(zlb.formatted_staffhrs(tasks.staffhrs),1,12),
tasks.rowid,
nvl(orderhdr.apptdate,ztm.subtask_min_apptdate(tasks.taskid)),
orderhdr.carrier,
orderhdr.deliveryservice,
decode(orderhdr.shiptoname, null, consignee.name, orderhdr.shiptoname),
zwt.from_lbs_to_kgs(tasks.custid,tasks.weight),
orderhdr.orderstatus,
nvl(orderhdr.manual_picks_yn,'N'),
ztk.task_crush_factor(tasks.taskid,tasks.tasktype,tasks.custid,tasks.item),
ztk.task_uom_pick_seq(tasks.tasktype,tasks.custid,tasks.pickuom)
from orderhdr, tasktypes, taskpriorities, unitsofmeasure,
  picktotypes, cartontypes, tasks, consignee
where tasks.tasktype = tasktypes.code(+)
and tasks.priority = taskpriorities.code(+)
and tasks.pickuom = unitsofmeasure.code(+)
and tasks.picktotype = picktotypes.code(+)
and tasks.cartontype = cartontypes.code(+)
and tasks.orderid = orderhdr.orderid(+)
and tasks.shipid = orderhdr.shipid(+)
and orderhdr.shipto = consignee.consignee(+);

comment on table tasksview is '$Id$';

exit;
