CREATE OR REPLACE VIEW ALPS.TMS_ACTUALSHIP_SHDR
(
    CUSTID,
    ORDERID,
    SHIPID,
    WAVE,
    LOADNO,
    SHIPMENT,
    SHIPMENTREFNUMQUALIFIER,
    SHIPMENTREFNUMVALUE,
    SHIPMENTREFNUM2VALUE,
    SERVICEPROVIDER,
    PRONO,
    FACILITY
)
AS
SELECT
OH.CUSTID,
OH.ORDERID,
OH.SHIPID,
OH.WAVE,
OH.LOADNO, /*Shipment: GC3 Load Number - Alpha*/
OH.TMS_SHIPMENT_ID,
'LD', /*ShipmentRefnumQualifier*/
OH.REFERENCE, /*ShipmentRefnumValue*/
(SELECT NVL(SUM(NVL(PH.OUTPALLETS,0)),0)
 FROM PALLETHISTORY PH
 WHERE PH.LOADNO=OH.LOADNO
 AND PH.CUSTID=OH.CUSTID
 AND PH.FACILITY=OH.FROMFACILITY
 AND PH.ORDERID=OH.ORDERID
 AND PH.SHIPID=OH.SHIPID),/*PalletCount*/
OH.CARRIER, /*ServiceProvider: Carrier Code*/
NVL(OH.PRONO,LD.PRONO),
OH.FROMFACILITY
FROM LOADS LD, ORDERHDR OH
WHERE LD.LOADNO=OH.LOADNO
AND (NVL(OH.LOADNO,0)=0
OR NOT EXISTS(SELECT OH1.CUSTID
              FROM ORDERHDR OH1
              WHERE OH1.TMS_SHIPMENT_ID = OH.TMS_SHIPMENT_ID
              AND OH1.LOADNO = OH.LOADNO
              AND OH1.ORDERID <> OH.ORDERID
              AND OH1.SHIPID <> OH.SHIPID
              AND OH1.ORDERSTATUS NOT IN ('9','X')));

comment on table TMS_ACTUALSHIP_SHDR is '$Id$';

CREATE OR REPLACE VIEW ALPS.TMS_ACTUALSHIP_STOP
(
    CUSTID,
    ORDERID,
    SHIPID,
    WAVE,
    LOADNO,
    STOPSEQUENCE,
    ARRIVALPLANNEDTIME,
    ARRIVALESTIMATEDTIME,
    ARRIVALACTUALTTIME,
    ISARRIVALPLANTIMEFIXED,
    DEPARTUREPLANNEDTIME,
    DEPARTUREESTIMATEDTIME,
    DEPARTUREACTUALTTIME,
    ISDEPARTUREPLANTIMEFIXED,
    STATUSUPDATE
)
AS
SELECT
OH.CUSTID,
OH.ORDERID,
OH.SHIPID,
OH.WAVE,
OH.LOADNO,
ROWNUM, /*StopSequence*/
NVL(TO_CHAR(OH.ARRIVALDATE,'YYYYMMDDHH24MISS'),' '), /*ArrivalPlannedTime*/
NVL(TO_CHAR(OH.ARRIVALDATE,'YYYYMMDDHH24MISS'),' '), /*ArrivalEstimatedTime*/
NVL(TO_CHAR(OH.ARRIVALDATE,'YYYYMMDDHH24MISS'),' '), /*ArrivalActualTime*/
' ', /*IsArrivalPlannedTimeFixed*/
NVL(TO_CHAR(OH.SHIPDATE,'YYYYMMDDHH24MISS'),' '), /*DeparturePlannedTime*/
NVL(TO_CHAR(OH.SHIPDATE,'YYYYMMDDHH24MISS'),' '), /*DepartureEstimatedTime*/
NVL(TO_CHAR(OH.DATESHIPPED,'YYYYMMDDHH24MISS'),' '), /*DepartureActualTime*/
' ', /*IsDeparturePlannedTimeFixed*/
NVL(TO_CHAR(OH.STATUSUPDATE,'YYYYMMDDHH24MISS'),' ')
FROM ORDERHDR OH;

comment on table TMS_ACTUALSHIP_STOP  is '$Id$';

CREATE OR REPLACE VIEW ALPS.TMS_ITEM_DTL
(
    CUSTID,
    ITEMDOMAIN,
    ITEM,
    ITEMNAME,
    DESCRIPTION,
    COMMODITY,
    NMFCARTICLE,
    NMFCCLASS,
    REFNUMVALUE,
    PACKAGEDITEMDOMAIN,
    PACKAGEDITEM,
    PACKAGEDITEMDESCRIPTION,
    ISHAZARDOUS
)
AS
SELECT
CI.CUSTID,
CI.CUSTID,
CI.ITEM, /* Item Code */
CI.ITEM, /* Item Code */
CI.DESCR, /* Item Description 1 */
CI.TMS_COMMODITY_CODE, /* Commodity */
CI.NMFC, /* NMFC Article */
LTRIM(TO_CHAR(ROUND(NCC.CLASS,1),'9999.9')), /* Truck Load Freight Class */
CIA.ITEMALIAS, /* Domestic Service Freight Code */
CI.CUSTID,
CI.ITEM, /* Item Code */
CI.DESCR, /* Item Description 1 */
CI.HAZARDOUS /* Hazardous? */
FROM CUSTITEM CI,
NMFCLASSCODES NCC,
CUSTITEMALIAS CIA
WHERE CI.NMFC=NCC.NMFC(+)
AND CI.CUSTID=CIA.CUSTID(+)
AND CI.ITEM=CIA.ITEM(+);

comment on table TMS_ITEM_DTL  is '$Id$';

CREATE OR REPLACE VIEW ALPS.TMS_ORDERREL_DTL
(
    CUSTID,
    ORDERID,
    SHIPID,
    LOADNO,
    GENERICSTATUSUPDATEDOMAIN,
    GENERICSTATUSUPDATE,
    STATUSVALUE,
    REFERENCE,
hdrpassthruchar01,
hdrpassthruchar02,
hdrpassthruchar03,
hdrpassthruchar04,
hdrpassthruchar05,
hdrpassthruchar06,
hdrpassthruchar07,
hdrpassthruchar08,
hdrpassthruchar09,
hdrpassthruchar10,
hdrpassthruchar11,
hdrpassthruchar12,
hdrpassthruchar13,
hdrpassthruchar14,
hdrpassthruchar15,
hdrpassthruchar16,
hdrpassthruchar17,
hdrpassthruchar18,
hdrpassthruchar19,
hdrpassthruchar20,
hdrpassthrunum01,
hdrpassthrunum02,
hdrpassthrunum03,
hdrpassthrunum04,
hdrpassthrunum05,
hdrpassthrunum06,
hdrpassthrunum07,
hdrpassthrunum08,
hdrpassthrunum09,
hdrpassthrunum10,
hdrpassthrudate01,
hdrpassthrudate02,
hdrpassthrudate03,
hdrpassthrudate04,
hdrpassthrudoll01,
hdrpassthrudoll02
)
AS
SELECT
OH.CUSTID,
OH.ORDERID,
OH.SHIPID,
OH.LOADNO,
OH.CUSTID,
OH.TMS_RELEASE_ID, /*DUNS Number*/
OH.ORDERSTATUS, /*WINS CommsID*/
OH.REFERENCE,
hdrpassthruchar01,
hdrpassthruchar02,
hdrpassthruchar03,
hdrpassthruchar04,
hdrpassthruchar05,
hdrpassthruchar06,
hdrpassthruchar07,
hdrpassthruchar08,
hdrpassthruchar09,
hdrpassthruchar10,
hdrpassthruchar11,
hdrpassthruchar12,
hdrpassthruchar13,
hdrpassthruchar14,
hdrpassthruchar15,
hdrpassthruchar16,
hdrpassthruchar17,
hdrpassthruchar18,
hdrpassthruchar19,
hdrpassthruchar20,
hdrpassthrunum01,
hdrpassthrunum02,
hdrpassthrunum03,
hdrpassthrunum04,
hdrpassthrunum05,
hdrpassthrunum06,
hdrpassthrunum07,
hdrpassthrunum08,
hdrpassthrunum09,
hdrpassthrunum10,
hdrpassthrudate01,
hdrpassthrudate02,
hdrpassthrudate03,
hdrpassthrudate04,
hdrpassthrudoll01,
hdrpassthrudoll02
FROM ORDERHDR OH
WHERE OH.ORDERSTATUS IN ('2','4','5','6','7','8','9','X');

comment on table TMS_ORDERREL_DTL is '$Id$';

CREATE OR REPLACE VIEW ALPS.TMS_SHPEVNTSTAT_DTL
(
    CUSTID,
    ORDERID,
    SHIPID,
    SERVICEPROVIDERDOMAIN,
    SERVICEPROVIDERALIASVALUE,
    SHIPMENTREFNUMVALUE,
    STATUSCODE,
    EVENTDATE,
    STATUSREASONCODE,
    SSSTOPSEQUENCENUM,
    SSREMARKS
)
AS
SELECT
OH.CUSTID,
OH.ORDERID,
OH.SHIPID,
' ', /* WINS CommsID */
' ', /* Carrier"s SCAC */
' ', /* GC3 Load Number */
' ', /* Event Status Code */
' ', /* Date/Time */
' ', /* Event Reason Code */
' ', /* Consolidation Stop Number */
' ' /* Comments */
FROM ORDERHDR OH;

comment on table TMS_SHPEVNTSTAT_DTL  is '$Id$';

CREATE OR REPLACE VIEW ALPS.TMS_TRANSORDER_DTL
(
    CUSTID,
    ORDERID,
    SHIPID,
    WAVE,
    LOADNO,
    TRANSORDERDOMAIN,
    TRANSORDER,
    CONTACT,
    CONTACTEMAILADDRESS,
    INVOLVEDPARTY2LOCATION,
    CONTACT2,
    INVOLVEDPARTY3LOCATION,
    CONTACT3,
    PAYMETHODCODE,
    PLANNINGGROUP,
    ORDERTYPE,
    SERVICEPROVIDERDOMAIN,
    SERVICEPROVIDER,
    ORDERREFNUM1VALUE,
    ORDERREFNUM3VALUE,
    ORDERREFNUM4VALUE,
    ORDERREFNUM5VALUE,
    ORDERREFNUM6QUALIFIER,
    ORDERREFNUM6VALUE,
    ORDERREFNUM7QUALIFIER,
    ORDERREFNUM7VALUE,
    REMARKTEXT,
    BATCHBALANCEORDERTYPE,
    BATCHBALANCESCHEDULE,
    SPECIALSERVICE,
    SPECIALSERVICEDESC,
    ACCESSORIALCODE,
    TOTALNETWEIGHTVALUE,
    TOTALNETVOLUMEVALUE,
    ORDERREFNUM8VALUE,
    HDRPASSTHRUCHAR01,
    HDRPASSTHRUCHAR02,
    HDRPASSTHRUCHAR03,
    HDRPASSTHRUCHAR04,
    HDRPASSTHRUCHAR05,
    HDRPASSTHRUCHAR06,
    HDRPASSTHRUCHAR07,
    HDRPASSTHRUCHAR08,
    HDRPASSTHRUCHAR09,
    HDRPASSTHRUCHAR10,
    HDRPASSTHRUCHAR11,
    HDRPASSTHRUCHAR12,
    HDRPASSTHRUCHAR13,
    HDRPASSTHRUCHAR14,
    HDRPASSTHRUCHAR15,
    HDRPASSTHRUCHAR16,
    HDRPASSTHRUCHAR17,
    HDRPASSTHRUCHAR18,
    HDRPASSTHRUCHAR19,
    HDRPASSTHRUCHAR20,
    HDRPASSTHRUNUM01,
    HDRPASSTHRUNUM02,
    HDRPASSTHRUNUM03,
    HDRPASSTHRUNUM04,
    HDRPASSTHRUNUM05,
    HDRPASSTHRUNUM06,
    HDRPASSTHRUNUM07,
    HDRPASSTHRUNUM08,
    HDRPASSTHRUNUM09,
    HDRPASSTHRUNUM10,
    HDRPASSTHRUDATE01,
    HDRPASSTHRUDATE02,
    HDRPASSTHRUDATE03,
    HDRPASSTHRUDATE04,
    HDRPASSTHRUDOLL01,
    HDRPASSTHRUDOLL02
)
AS
SELECT
OH.CUSTID,
OH.ORDERID,
OH.SHIPID,
OH.WAVE,
OH.LOADNO,
UPPER(OH.CUSTID),
UPPER(OH.ORDERID||'-'||OH.SHIPID),/*Bill of Lading number*/
UPPER(OH.FROMFACILITY),/*GC3 value for contact gid.*/
' ',/*Planner's email address*/
' ',/*Storer name*/
UPPER(OH.FROMFACILITY),/*Storer name*/
UPPER(OH.CONSIGNEE),/*Bill to name*/
UPPER(OH.FROMFACILITY),/*Storer name*/
UPPER(OH.SHIPTERMS),/*Freight charge. You must cross reference with GC3 values.*/
UPPER(OH.CUSTID),/*Planning group. GC3 value for the storer.*/
UPPER(OH.FROMFACILITY),/*Order type gid. GC3 value for the campus.*/
CASE WHEN OH.CARRIER IS NULL THEN ' ' ELSE 'OHL' END,/*Service provider domain.*/
UPPER(C.SCAC),/*Service provider or carrier SCAC code.*/
UPPER(OH.PRIORITY),/*Order priority code.*/
UPPER(OH.CUSTID),/*WIS:DOM storer number*/
UPPER(OH.PO),/*Storer purchase order number*/
UPPER(OH.REFERENCE),/*Storer order reference number*/
' ',/*OrderRefnum6Qualifier*/
' ',/*OrderRefnum6Value*/
' ',/*OrderRefnum7Qualifier*/
' ',/*OrderRefnum7Value*/
OH.COMMENT1,/*Order comment*/
' ',/*BatchBalanceOrderType*/
' ',/*BatchBalanceSchedule*/
' ',/*SpecialService*/
' ',/*SpecialServiceDesc*/
' ',/*AccessorialCode*/
ROUND(OH.WEIGHTCOMMIT,5),/*Order gross weight*/
ROUND(OH.CUBECOMMIT,5),/*Order cubic feet*/
OH.HDRPASSTHRUCHAR03,/*Additional Customer PO Number*/
HDRPASSTHRUCHAR01,
HDRPASSTHRUCHAR02,
HDRPASSTHRUCHAR03,
HDRPASSTHRUCHAR04,
HDRPASSTHRUCHAR05,
HDRPASSTHRUCHAR06,
HDRPASSTHRUCHAR07,
HDRPASSTHRUCHAR08,
HDRPASSTHRUCHAR09,
HDRPASSTHRUCHAR10,
HDRPASSTHRUCHAR11,
HDRPASSTHRUCHAR12,
HDRPASSTHRUCHAR13,
HDRPASSTHRUCHAR14,
HDRPASSTHRUCHAR15,
HDRPASSTHRUCHAR16,
HDRPASSTHRUCHAR17,
HDRPASSTHRUCHAR18,
HDRPASSTHRUCHAR19,
HDRPASSTHRUCHAR20,
HDRPASSTHRUNUM01,
HDRPASSTHRUNUM02,
HDRPASSTHRUNUM03,
HDRPASSTHRUNUM04,
HDRPASSTHRUNUM05,
HDRPASSTHRUNUM06,
HDRPASSTHRUNUM07,
HDRPASSTHRUNUM08,
HDRPASSTHRUNUM09,
HDRPASSTHRUNUM10,
HDRPASSTHRUDATE01,
HDRPASSTHRUDATE02,
HDRPASSTHRUDATE03,
HDRPASSTHRUDATE04,
HDRPASSTHRUDOLL01,
HDRPASSTHRUDOLL02
FROM ORDERHDR OH,
     CARRIER C
WHERE OH.CARRIER = C.CARRIER
AND EXISTS(SELECT 1
           FROM ORDERDTL OD
           WHERE OH.ORDERID=OD.ORDERID
           AND OH.SHIPID=OD.SHIPID
           AND OH.CUSTID=OD.CUSTID
           AND OD.QTYCOMMIT<>0
           AND OD.LINESTATUS<>'X');

comment on table TMS_TRANSORDER_DTL  is '$Id$';

CREATE OR REPLACE VIEW ALPS.TMS_TRANSORDER_SU
(
    CUSTID,
    ORDERID,
    SHIPID,
    WAVE,
    LOADNO,
    SHIPUNITDOMAIN,
    SHIPUNIT,
    SHIPUNITSPEC,
    SHIPFROMLOCATION,
    SHIPTOLOCATION,
    SHIPTOLOCATIONNAME,
    SHIPTOLOCATIONADDRLINE1,
    SHIPTOLOCATIONADDRLINE2,
    SHIPTOLOCATIONCITY,
    SHIPTOLOCATIONPROVINCE,
    SHIPTOLOCATIONPOSTALCODE,
    SHIPTOLOCATIONCOUNTRYCODE,
    EARLYPICKUPDATE,
    LATEPICKUPDATE,
    EARLYDELIVERYDATE,
    LATEDELIVERYDATE,
    SHIPUNITWEIGHTVALUE,
    SHIPUNITVOLUMEVALUE,
    SHIPUNITNETWEIGHTVALUE,
    SHIPUNITNETVOLUMEVALUE,
    SHIPUNITLENGTHVALUE,
    SHIPUNITWIDTHVALUE,
    SHIPUNITHEIGHTVALUE,
    PACKAGEDITEMREFDOMAIN,
    PACKAGEDITEMREF,
    PACKAGEDITEMDOMAIN,
    PACKAGEDITEM,
    PACKAGEDESCRIPTION,
    PACKAGESHIPUNITWEIGHTVAL,
    PACKAGESHIPUNITVOLUMEVAL,
    ITEMDOMAIN,
    ITEM,
    ITEMNAME,
    ITEMDESCRIPTION,
    COMMODITY,
    NMFCARTICLE,
    NMFCCLASS,
    ITEMREFNUMQUALIFIER,
    ITEMREFNUMVALUE,
    LINENUMBER,
    ITEMWEIGHTVALUE,
    ITEMVOLUMEVALUE,
    PACKAGEDITEMCOUNT,
    PACKAGEDITEMSPEC,
    PACKAGEDITEMSPECCOUNT,
    WEIGHTPERSHIPUNITVALUE,
    VOLUMEPERSHIPUNITVALUE,
    SHIPUNITCOUNT,
    RELEASECOUNT,
    STATUSTYPEDOMAIN,
    STATUSVALUEDOMAIN
)
AS
SELECT
OH.CUSTID,
OH.ORDERID,
OH.SHIPID,
OH.WAVE,
OH.LOADNO,
UPPER(OH.CUSTID),
UPPER(OH.ORDERID||'-'||OH.SHIPID||'-'||LPAD(ROWNUM,3,'0')),/*WIS:DOM bill of lading number + sequence number*/
UPPER(OD.UOMENTERED),/*Shipping unit of measure description*/
UPPER(OD.FROMFACILITY),/*GC3 building number; cross reference with WIS:DOM number*/
UPPER(NVL(OH.SHIPTO,SUBSTR(OH.SHIPTONAME,1,3)||SUBSTR(OH.SHIPTOADDR1,1,2)||SUBSTR(OH.SHIPTOPOSTALCODE,1,5))),/*Consignee code in WIS:DOM*/
UPPER(OH.SHIPTONAME),
UPPER(OH.SHIPTOADDR1),
UPPER(OH.SHIPTOADDR2),
UPPER(OH.SHIPTOCITY),
UPPER(OH.SHIPTOSTATE),
UPPER(OH.SHIPTOPOSTALCODE),
UPPER(OH.SHIPTOCOUNTRYCODE),
TO_CHAR(OH.APPTDATE,'YYYYMMDDHH24MISS'),/*Early pick up date*/
TO_CHAR(OH.APPTDATE,'YYYYMMDDHH24MISS'),/*Late pick up date*/
TO_CHAR(OH.ARRIVALDATE,'YYYYMMDDHH24MISS'),/*Early delivery date*/
TO_CHAR(OH.ARRIVALDATE,'YYYYMMDDHH24MISS'),/*Late delivery date*/
ROUND(ZCI.ITEM_WEIGHT(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*Shipping unit weight*/
ROUND(ZCI.ITEM_CUBE(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*Shipping unit cubic feet*/
ROUND(ZCI.ITEM_WEIGHT(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*Shipping unit weight*/
ROUND(ZCI.ITEM_CUBE(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*Shipping unit cubic feet*/
' ',/*Shipping unit length*/
' ',/*Shipping unit width*/
' ',/*Shipping unit height*/
UPPER(OH.CUSTID),/*Storer specific domain; from x-ref table*/
UPPER(OD.ITEM),/*Item number*/
UPPER(OH.CUSTID),/*PackagedItemDomain*/
UPPER(OD.ITEM),/*PackagedItem*/
UPPER(CI.DESCR),/*PackageDescription*/
ROUND(ZCU.EQUIV_UOM_QTY(OH.CUSTID,OD.ITEM,OD.UOM,OD.QTYCOMMIT,OD.UOMENTERED)*ZCI.ITEM_WEIGHT(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*PackageShipUnitWeightValue*/
ROUND(ZCU.EQUIV_UOM_QTY(OH.CUSTID,OD.ITEM,OD.UOM,OD.QTYCOMMIT,OD.UOMENTERED)*ZCI.ITEM_CUBE(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*PackageShipUnitVolumeValue*/
UPPER(OH.CUSTID),/*ItemDomain*/
UPPER(CI.ITEM),/*Item*/
UPPER(CI.ABBREV),/*ItemName*/
UPPER(CI.DESCR),/*ItemDescription*/
UPPER(NCC.ABBREV),/*Commodity*/
UPPER(CI.NMFC),/*NMFCArticle*/
UPPER(NCC.CLASS),/*NMFCClass*/
UPPER(CIA.ALIASDESC),/*ItemRefnumQualifier*/
UPPER(CIA.ITEMALIAS),/*ItemRefnumValue*/
ROWNUM,/*Order item sequence number*/
ROUND(ZCU.EQUIV_UOM_QTY(OH.CUSTID,OD.ITEM,OD.UOM,OD.QTYCOMMIT,OD.UOMENTERED)*ZCI.ITEM_WEIGHT(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*Item gross weight*/
ROUND(ZCU.EQUIV_UOM_QTY(OH.CUSTID,OD.ITEM,OD.UOM,OD.QTYCOMMIT,OD.UOMENTERED)*ZCI.ITEM_CUBE(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*Item cubic feet*/
ZCU.EQUIV_UOM_QTY(OH.CUSTID,OD.ITEM,OD.UOM,OD.QTYCOMMIT,OD.UOMENTERED),/*Quantity to ship*/
UPPER(OD.UOMENTERED),/*Shipping unit of measure description*/
ZCU.EQUIV_UOM_QTY(OH.CUSTID,OD.ITEM,OD.UOM,OD.QTYCOMMIT,OD.UOMENTERED),/*PackagedItemSpecCount*/
ROUND(ZCI.ITEM_WEIGHT(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*Shipping unit weight*/
ROUND(ZCI.ITEM_CUBE(OH.CUSTID,OD.ITEM,OD.UOMENTERED),5),/*Shipping unit cubic feet*/
ZCU.EQUIV_UOM_QTY(OH.CUSTID,OD.ITEM,OD.UOM,OD.QTYCOMMIT,OD.UOMENTERED),/*Quantity to ship*/
ZCU.EQUIV_UOM_QTY(OH.CUSTID,OD.ITEM,OD.UOM,OD.QTYCOMMIT,OD.UOMENTERED),/*ReleaseCount*/
UPPER(OH.CUSTID),/*StatusTypeDomain*/
UPPER(OH.CUSTID)/*StatusValueDomain*/
FROM ORDERHDR OH,
     ORDERDTL OD,
     CUSTITEM CI,
     NMFCLASSCODES NCC,
     CUSTITEMALIAS CIA
WHERE OH.ORDERID = OD.ORDERID
AND OH.SHIPID = OD.SHIPID
AND OH.CUSTID = OD.CUSTID
AND OD.CUSTID = CI.CUSTID
AND OD.ITEM = CI.ITEM
AND CI.NMFC = NCC.NMFC(+)
AND CI.CUSTID = CIA.CUSTID(+)
AND CI.ITEM = CIA.ITEM(+)
AND OD.QTYCOMMIT<>0
AND OD.LINESTATUS<>'X';

comment on table TMS_TRANSORDER_SU  is '$Id$';

exit;
