create or replace view wavesview
(
WAVE,
WAVESTATUS,
DESCR,
SCHEDRELEASE,
ACTUALRELEASE,
FACILITY,
LASTUSER,
LASTUPDATE,
WAVESTATUSABBREV,
staffhours,
fmtstaffhours,
cntorder,
qtyorder,
weightorder,
cubeorder,
qtycommit,
weightcommit,
cubecommit,
stageloc,
picktype,
taskpriority,
sortloc,
job,
childwave,
batchcartontype,
openfacility,
pctcomplete,
qtyhazardousorders,
qtyhotorders,
replanned,
tms_status,
master_wave,
combined_wave,
waves_rowid,
batch_pick_by_item_yn,
task_assignment_sequence,
consolidated
)
as
select
waves.WAVE,
waves.wavestatus,
waves.descr,
waves.schedrelease,
waves.actualrelease,
waves.facility,
waves.lastuser,
waves.lastupdate,
wavestatus.abbrev,
nvl(staffhrs,0),
substr(zlb.formatted_staffhrs(nvl(staffhrs,0)),1,12),
nvl(cntorder,0),
nvl(qtyorder,0),
nvl(weightorder,0),
nvl(cubeorder,0),
nvl(qtycommit,0),
nvl(weightcommit,0),
nvl(cubecommit,0),
waves.stageloc,
waves.picktype,
waves.taskpriority,
waves.sortloc,
waves.job,
waves.childwave,
waves.batchcartontype,
waves.openfacility,
decode(nvl(waves.qtyorder,0),0,0,(nvl(waves.qtyorder,0) - nvl(waves.qtycommit,0))
 / waves.qtyorder) * 100,
nvl(waves.qtyhazardousorders,0),
nvl(waves.qtyhotorders,0),
nvl(waves.replanned, 'O'),
nvl(waves.tms_status, 'X'),
master_wave,
nvl(waves.combined_wave,'N'),
waves.rowid,
nvl(waves.batch_pick_by_item_yn,'N'),
nvl(waves.task_assignment_sequence,'ITEM'),
waves.consolidated
from wavestatus, waves
where waves.wavestatus = wavestatus.code(+);

comment on table wavesview is '$Id$';

exit;
