create or replace view weber_eso_ordlbl_view
(
   lpid,
   sscc18,
   sscc18_formatted,
   scc14,
   scc14_formatted,
   shiptoname,
   shiptoaddr1,
   shiptoaddr2,
   shiptocity,
   shiptostate,
   shiptopostalcode,
   shiptopostalcode2,
   dc,
   carriername,
   carrierscac,
   shipdate,
   orderid,
   shipid,
   item1,
   item2,
   item3,
   item4,
   item5,
   item6,
   item7,
   item8,
   item9,
   item10,
   item11,
   item12,
   multipleitems,
   itemdescr1,
   itemdescr2,
   itemdescr3,
   itemdescr4,
   itemdescr5,
   itemdescr6,
   itemdescr7,
   itemdescr8,
   itemdescr9,
   itemdescr10,
   itemdescr11,
   itemdescr12,
   itemabbrev1,
   itemabbrev2,
   itemabbrev3,
   itemabbrev4,
   itemabbrev5,
   itemabbrev6,
   itemabbrev7,
   itemabbrev8,
   itemabbrev9,
   itemabbrev10,
   itemabbrev11,
   itemabbrev12,
   consigneeitem1,
   consigneeitem2,
   consigneeitem3,
   consigneeitem4,
   consigneeitem5,
   consigneeitem6,
   consigneeitem7,
   consigneeitem8,
   consigneeitem9,
   consigneeitem10,
   consigneeitem11,
   consigneeitem12,
   po,
   reference,
   loadno,
   prono,
   bol,
   custname,
   custaddr1,
   custaddr2,
   custcity,
   custstate,
   custpostalcode,
   whsename,
   whseaddr1,
   whseaddr2,
   whsecity,
   whsestate,
   whsepostalcode,
   qtyeaitem1,
   qtyeaitem2,
   qtyeaitem3,
   qtyeaitem4,
   qtyeaitem5,
   qtyeaitem6,
   qtyeaitem7,
   qtyeaitem8,
   qtyeaitem9,
   qtyeaitem10,
   qtyeaitem11,
   qtyeaitem12,
   qtycs,
   upc1,
   upc2,
   upc3,
   upc4,
   upc5,
   upc6,
   upc7,
   upc8,
   upc9,
   upc10,
   upc11,
   upc12,
   countryof1,
   countryof2,
   countryof3,
   countryof4,
   countryof5,
   countryof6,
   countryof7,
   countryof8,
   countryof9,
   countryof10,
   countryof11,
   countryof12,
   countryofabbrev1,
   countryofabbrev2,
   countryofabbrev3,
   countryofabbrev4,
   countryofabbrev5,
   countryofabbrev6,
   countryofabbrev7,
   countryofabbrev8,
   countryofabbrev9,
   countryofabbrev10,
   countryofabbrev11,
   countryofabbrev12,
   hdrpassthruchar01,
   hdrpassthruchar02,
   hdrpassthruchar03,
   hdrpassthruchar04,
   hdrpassthruchar05,
   hdrpassthruchar06,
   hdrpassthruchar07,
   hdrpassthruchar08,
   hdrpassthruchar09,
   hdrpassthruchar10,
   hdrpassthruchar11,
   hdrpassthruchar12,
   hdrpassthruchar13,
   hdrpassthruchar14,
   hdrpassthruchar15,
   hdrpassthruchar16,
   hdrpassthruchar17,
   hdrpassthruchar18,
   hdrpassthruchar19,
   hdrpassthruchar20,
   hdrpassthrunum01,
   hdrpassthrunum02,
   hdrpassthrunum03,
   hdrpassthrunum04,
   hdrpassthrunum05,
   hdrpassthrunum06,
   hdrpassthrunum07,
   hdrpassthrunum08,
   hdrpassthrunum09,
   hdrpassthrunum10,
   dtlpassthruchar01_1,
   dtlpassthruchar01_2,
   dtlpassthruchar01_3,
   dtlpassthruchar01_4,
   dtlpassthruchar01_5,
   dtlpassthruchar01_6,
   dtlpassthruchar01_7,
   dtlpassthruchar01_8,
   dtlpassthruchar01_9,
   dtlpassthruchar01_10,
   dtlpassthruchar01_11,
   dtlpassthruchar01_12,
   dtlpassthruchar06_1,
   dtlpassthruchar06_2,
   dtlpassthruchar06_3,
   dtlpassthruchar06_4,
   dtlpassthruchar06_5,
   dtlpassthruchar06_6,
   dtlpassthruchar06_7,
   dtlpassthruchar06_8,
   dtlpassthruchar06_9,
   dtlpassthruchar06_10,
   dtlpassthruchar06_11,
   dtlpassthruchar06_12,
   dtlpassthruchar07_1,
   dtlpassthruchar07_2,
   dtlpassthruchar07_3,
   dtlpassthruchar07_4,
   dtlpassthruchar07_5,
   dtlpassthruchar07_6,
   dtlpassthruchar07_7,
   dtlpassthruchar07_8,
   dtlpassthruchar07_9,
   dtlpassthruchar07_10,
   dtlpassthruchar07_11,
   dtlpassthruchar07_12,
   dtlpassthruchar10_1,
   dtlpassthruchar10_2,
   dtlpassthruchar10_3,
   dtlpassthruchar10_4,
   dtlpassthruchar10_5,
   dtlpassthruchar10_6,
   dtlpassthruchar10_7,
   dtlpassthruchar10_8,
   dtlpassthruchar10_9,
   dtlpassthruchar10_10,
   dtlpassthruchar10_11,
   dtlpassthruchar10_12,
   dtlpassthruchar11_1,
   dtlpassthruchar11_2,
   dtlpassthruchar11_3,
   dtlpassthruchar11_4,
   dtlpassthruchar11_5,
   dtlpassthruchar11_6,
   dtlpassthruchar11_7,
   dtlpassthruchar11_8,
   dtlpassthruchar11_9,
   dtlpassthruchar11_10,
   dtlpassthruchar11_11,
   dtlpassthruchar11_12,
   dtlpassthruchar12_1,
   dtlpassthruchar12_2,
   dtlpassthruchar12_3,
   dtlpassthruchar12_4,
   dtlpassthruchar12_5,
   dtlpassthruchar12_6,
   dtlpassthruchar12_7,
   dtlpassthruchar12_8,
   dtlpassthruchar12_9,
   dtlpassthruchar12_10,
   dtlpassthruchar12_11,
   dtlpassthruchar12_12,
   dtlpassthrunum01_1,
   dtlpassthrunum01_2,
   dtlpassthrunum01_3,
   dtlpassthrunum01_4,
   dtlpassthrunum01_5,
   dtlpassthrunum01_6,
   dtlpassthrunum01_7,
   dtlpassthrunum01_8,
   dtlpassthrunum01_9,
   dtlpassthrunum01_10,
   dtlpassthrunum01_11,
   dtlpassthrunum01_12,
   jcpbcstore,
   finaldestzip,
   seq,
   seqof,
   bigseq,
   bigseqof,
   item,
   itemdescr,
   itemabbrev,
   consigneeitem,
   qtyeaitem,
   countryofabbrev,
   dtlpassthruchar01,
   dtlpassthruchar02,
   dtlpassthruchar03,
   dtlpassthruchar06,
   dtlpassthruchar07,
   dtlpassthruchar10,
   dtlpassthruchar11,
   dtlpassthruchar12,
   dtlpassthrunum01,
   upc,
   countryof,
   sizename1,
   sizename2,
   sizename3,
   sizename4,
   sizename5,
   sizename6,
   sizename7,
   sizename8,
   sizename9,
   sizename10,
   sizename11,
   sizename12,
   sizename13,
   sizename14,
   sizename15,
   sizename16,
   sizename17,
   sizename18,
   sizeqty1,
   sizeqty2,
   sizeqty3,
   sizeqty4,
   sizeqty5,
   sizeqty6,
   sizeqty7,
   sizeqty8,
   sizeqty9,
   sizeqty10,
   sizeqty11,
   sizeqty12,
   sizeqty13,
   sizeqty14,
   sizeqty15,
   sizeqty16,
   sizeqty17,
   sizeqty18,
   type,
   statusupdate,
   custid,
   storecode,
   glncode,
   dunsnumber,
   conspassthruchar01,
   conspassthruchar02,
   conspassthruchar03,
   conspassthruchar04,
   conspassthruchar05,
   conspassthruchar06,
   conspassthruchar07,
   conspassthruchar08,
   conspassthruchar09,
   conspassthruchar10
)
as
select
   WT.lpid,
   WT.sscc18,
   '('||substr(WT.sscc18,1,2)||')'||substr(WT.sscc18,3),
   WT.scc14,
   '('||substr(WT.scc14,1,2)||')'||substr(WT.scc14,3),
   nvl(CO.name, OH.shiptoname),
   nvl(CO.addr1, OH.shiptoaddr1),
   nvl(CO.addr2, OH.shiptoaddr2),
   nvl(CO.city, OH.shiptocity),
   nvl(CO.state, OH.shiptostate),
   nvl(CO.postalcode, OH.shiptopostalcode),
   nvl(CO.postalcode, OH.shiptopostalcode),
   substr(decode(CO.consignee, null, OH.shiptoname, CO.name), instr(decode(
         CO.consignee, NULL, OH.shiptoname, CO.name),'DC',-1)),
   CA.name,
   CA.carrier,
   OH.shipdate,
   OH.orderid,
   OH.shipid,
   WT.item1,
   WT.item2,
   WT.item3,
   WT.item4,
   WT.item5,
   WT.item6,
   WT.item7,
   WT.item8,
   WT.item9,
   WT.item10,
   WT.item11,
   WT.item12,
   decode(WT.item2, null, null, 'Mixed'),
   WT.itemdescr1,
   WT.itemdescr2,
   WT.itemdescr3,
   WT.itemdescr4,
   WT.itemdescr5,
   WT.itemdescr6,
   WT.itemdescr7,
   WT.itemdescr8,
   WT.itemdescr9,
   WT.itemdescr10,
   WT.itemdescr11,
   WT.itemdescr12,
   WT.itemabbrev1,
   WT.itemabbrev2,
   WT.itemabbrev3,
   WT.itemabbrev4,
   WT.itemabbrev5,
   WT.itemabbrev6,
   WT.itemabbrev7,
   WT.itemabbrev8,
   WT.itemabbrev9,
   WT.itemabbrev10,
   WT.itemabbrev11,
   WT.itemabbrev12,
   WT.consigneeitem1,
   WT.consigneeitem2,
   WT.consigneeitem3,
   WT.consigneeitem4,
   WT.consigneeitem5,
   WT.consigneeitem6,
   WT.consigneeitem7,
   WT.consigneeitem8,
   WT.consigneeitem9,
   WT.consigneeitem10,
   WT.consigneeitem11,
   WT.consigneeitem12,
   OH.po,
   OH.reference,
   OH.loadno,
   OH.prono,
   OH.orderid || '-' || OH.shipid,
   rtrim(OH.hdrpassthruchar20),
   decode(OH.hdrpassthruchar20,'Rockport Kids','9345 Santa Anita Avenue','2 Germak Drive'),
   decode(OH.hdrpassthruchar20,'Rockport Kids',' ',' '),
   decode(OH.hdrpassthruchar20,'Rockport Kids','Rancho Cucamonga','Carteret'),
   decode(OH.hdrpassthruchar20,'Rockport Kids','CA','NJ'),
   decode(OH.hdrpassthruchar20,'Rockport Kids','91730','07008'),
   FA.name,
   FA.addr1,
   FA.addr2,
   FA.city,
   FA.state,
   FA.postalcode,
   WT.qtyeaitem1,
   WT.qtyeaitem2,
   WT.qtyeaitem3,
   WT.qtyeaitem4,
   WT.qtyeaitem5,
   WT.qtyeaitem6,
   WT.qtyeaitem7,
   WT.qtyeaitem8,
   WT.qtyeaitem9,
   WT.qtyeaitem10,
   WT.qtyeaitem11,
   WT.qtyeaitem12,
   decode(WT.type, 'C', 0, 1),
   WT.upc1,
   WT.upc2,
   WT.upc3,
   WT.upc4,
   WT.upc5,
   WT.upc6,
   WT.upc7,
   WT.upc8,
   WT.upc9,
   WT.upc10,
   WT.upc11,
   WT.upc12,
   WT.countryof1,
   WT.countryof2,
   WT.countryof3,
   WT.countryof4,
   WT.countryof5,
   WT.countryof6,
   WT.countryof7,
   WT.countryof8,
   WT.countryof9,
   WT.countryof10,
   WT.countryof11,
   WT.countryof12,
   WT.countryofabbrev1,
   WT.countryofabbrev2,
   WT.countryofabbrev3,
   WT.countryofabbrev4,
   WT.countryofabbrev5,
   WT.countryofabbrev6,
   WT.countryofabbrev7,
   WT.countryofabbrev8,
   WT.countryofabbrev9,
   WT.countryofabbrev10,
   WT.countryofabbrev11,
   WT.countryofabbrev12,
   rtrim(OH.hdrpassthruchar01),
   rtrim(OH.hdrpassthruchar02),
   rtrim(OH.hdrpassthruchar03),
   rtrim(OH.hdrpassthruchar04),
   rtrim(OH.hdrpassthruchar05),
   rtrim(OH.hdrpassthruchar06),
   rtrim(OH.hdrpassthruchar07),
   rtrim(OH.hdrpassthruchar08),
   rtrim(OH.hdrpassthruchar09),
   rtrim(OH.hdrpassthruchar10),
   rtrim(OH.hdrpassthruchar11),
   rtrim(OH.hdrpassthruchar12),
   rtrim(OH.hdrpassthruchar13),
   rtrim(OH.hdrpassthruchar14),
   rtrim(OH.hdrpassthruchar15),
   rtrim(OH.hdrpassthruchar16),
   rtrim(OH.hdrpassthruchar17),
   rtrim(OH.hdrpassthruchar18),
   rtrim(OH.hdrpassthruchar19),
   rtrim(OH.hdrpassthruchar20),
   OH.hdrpassthrunum01,
   OH.hdrpassthrunum02,
   OH.hdrpassthrunum03,
   OH.hdrpassthrunum04,
   OH.hdrpassthrunum05,
   OH.hdrpassthrunum06,
   OH.hdrpassthrunum07,
   OH.hdrpassthrunum08,
   OH.hdrpassthrunum09,
   OH.hdrpassthrunum10,
   WT.dtlpassthruchar01_1,
   WT.dtlpassthruchar01_2,
   WT.dtlpassthruchar01_3,
   WT.dtlpassthruchar01_4,
   WT.dtlpassthruchar01_5,
   WT.dtlpassthruchar01_6,
   WT.dtlpassthruchar01_7,
   WT.dtlpassthruchar01_8,
   WT.dtlpassthruchar01_9,
   WT.dtlpassthruchar01_10,
   WT.dtlpassthruchar01_11,
   WT.dtlpassthruchar01_12,
   WT.dtlpassthruchar06_1,
   WT.dtlpassthruchar06_2,
   WT.dtlpassthruchar06_3,
   WT.dtlpassthruchar06_4,
   WT.dtlpassthruchar06_5,
   WT.dtlpassthruchar06_6,
   WT.dtlpassthruchar06_7,
   WT.dtlpassthruchar06_8,
   WT.dtlpassthruchar06_9,
   WT.dtlpassthruchar06_10,
   WT.dtlpassthruchar06_11,
   WT.dtlpassthruchar06_12,
   WT.dtlpassthruchar07_1,
   WT.dtlpassthruchar07_2,
   WT.dtlpassthruchar07_3,
   WT.dtlpassthruchar07_4,
   WT.dtlpassthruchar07_5,
   WT.dtlpassthruchar07_6,
   WT.dtlpassthruchar07_7,
   WT.dtlpassthruchar07_8,
   WT.dtlpassthruchar07_9,
   WT.dtlpassthruchar07_10,
   WT.dtlpassthruchar07_11,
   WT.dtlpassthruchar07_12,
   WT.dtlpassthruchar10_1,
   WT.dtlpassthruchar10_2,
   WT.dtlpassthruchar10_3,
   WT.dtlpassthruchar10_4,
   WT.dtlpassthruchar10_5,
   WT.dtlpassthruchar10_6,
   WT.dtlpassthruchar10_7,
   WT.dtlpassthruchar10_8,
   WT.dtlpassthruchar10_9,
   WT.dtlpassthruchar10_10,
   WT.dtlpassthruchar10_11,
   WT.dtlpassthruchar10_12,
   WT.dtlpassthruchar11_1,
   WT.dtlpassthruchar11_2,
   WT.dtlpassthruchar11_3,
   WT.dtlpassthruchar11_4,
   WT.dtlpassthruchar11_5,
   WT.dtlpassthruchar11_6,
   WT.dtlpassthruchar11_7,
   WT.dtlpassthruchar11_8,
   WT.dtlpassthruchar11_9,
   WT.dtlpassthruchar11_10,
   WT.dtlpassthruchar11_11,
   WT.dtlpassthruchar11_12,
   WT.dtlpassthruchar12_1,
   WT.dtlpassthruchar12_2,
   WT.dtlpassthruchar12_3,
   WT.dtlpassthruchar12_4,
   WT.dtlpassthruchar12_5,
   WT.dtlpassthruchar12_6,
   WT.dtlpassthruchar12_7,
   WT.dtlpassthruchar12_8,
   WT.dtlpassthruchar12_9,
   WT.dtlpassthruchar12_10,
   WT.dtlpassthruchar12_11,
   WT.dtlpassthruchar12_12,
   WT.dtlpassthrunum01_1,
   WT.dtlpassthrunum01_2,
   WT.dtlpassthrunum01_3,
   WT.dtlpassthrunum01_4,
   WT.dtlpassthrunum01_5,
   WT.dtlpassthrunum01_6,
   WT.dtlpassthrunum01_7,
   WT.dtlpassthrunum01_8,
   WT.dtlpassthrunum01_9,
   WT.dtlpassthrunum01_10,
   WT.dtlpassthrunum01_11,
   WT.dtlpassthrunum01_12,
   '0' || rtrim(OH.hdrpassthruchar10),
   rtrim(OH.hdrpassthruchar04),
   WT.seq,
   WT.seqof,
   WT.bigseq,
   WT.bigseqof,
   WT.item,
   WT.itemdescr,
   WT.itemabbrev,
   WT.consigneeitem,
   WT.qtyeaitem,
   WT.countryofabbrev,
   WT.dtlpassthruchar01,
   WT.dtlpassthruchar02,
   WT.dtlpassthruchar03,
   WT.dtlpassthruchar06,
   WT.dtlpassthruchar07,
   WT.dtlpassthruchar10,
   WT.dtlpassthruchar11,
   WT.dtlpassthruchar12,
   WT.dtlpassthrunum01,
   WT.upc,
   WT.countryof,
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,1,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,5,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,9,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,13,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,17,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,21,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,25,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,29,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,33,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,37,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,41,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,45,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,49,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,53,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,57,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,61,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,65,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar02,69,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,1,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,5,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,9,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,13,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,17,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,21,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,25,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,29,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,33,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,37,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,41,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,45,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,49,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,53,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,57,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,61,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,65,4)),
   decode(WT.Type,'C',null, substr(WT.dtlpassthruchar03,69,4)),
   WT.type,
   OH.statusupdate,
   OH.custid,
   CO.storecode,
   CO.glncode,
   CO.dunsnumber,
   CO.conspassthruchar01,
   CO.conspassthruchar02,
   CO.conspassthruchar03,
   CO.conspassthruchar04,
   CO.conspassthruchar05,
   CO.conspassthruchar06,
   CO.conspassthruchar07,
   CO.conspassthruchar08,
   CO.conspassthruchar09,
   CO.conspassthruchar10
from weber_eso_ordlbl_table WT,
     orderhdr OH,
     carrier CA,
     consignee CO,
     facility FA
where OH.orderid = WT.orderid
  and OH.shipid = WT.shipid
  and OH.carrier = CA.carrier(+)
  and OH.shipto = CO.consignee(+)
  and OH.fromfacility = FA.facility;

comment on table weber_eso_ordlbl_view is '$Id$';

exit;
