CREATE OR REPLACE VIEW WEBORDERDTLVIEW ( ORDERID,
SHIPID, ITEM, LOTNUMBER, CUSTID,
ITEMDESCR, QTYORDER, QTYENTERED, QTYRCVD,
QTYSHIP, UOM, UOMABBREV, UOMENTERED,
UOMENTEREDABBREV, HAZARDOUS, ORDERTYPE, LINESTATUS,
ALIAS, PRODUCTGROUP, CONSIGNEESKU, COMMENT1,
DTLPASSTHRUCHAR01, DTLPASSTHRUCHAR02, DTLPASSTHRUCHAR03, DTLPASSTHRUCHAR04,
DTLPASSTHRUCHAR05, DTLPASSTHRUCHAR06, DTLPASSTHRUCHAR07, DTLPASSTHRUCHAR08,
DTLPASSTHRUCHAR09, DTLPASSTHRUCHAR10, DTLPASSTHRUCHAR11, DTLPASSTHRUCHAR12,
DTLPASSTHRUCHAR13, DTLPASSTHRUCHAR14, DTLPASSTHRUCHAR15, DTLPASSTHRUCHAR16,
DTLPASSTHRUCHAR17, DTLPASSTHRUCHAR18, DTLPASSTHRUCHAR19, DTLPASSTHRUCHAR20,
DTLPASSTHRUCHAR21, DTLPASSTHRUCHAR22, DTLPASSTHRUCHAR23, DTLPASSTHRUCHAR24,
DTLPASSTHRUCHAR25, DTLPASSTHRUCHAR26, DTLPASSTHRUCHAR27, DTLPASSTHRUCHAR28,
DTLPASSTHRUCHAR29, DTLPASSTHRUCHAR30, DTLPASSTHRUCHAR31, DTLPASSTHRUCHAR32,
DTLPASSTHRUCHAR33, DTLPASSTHRUCHAR34, DTLPASSTHRUCHAR35, DTLPASSTHRUCHAR36,
DTLPASSTHRUCHAR37, DTLPASSTHRUCHAR38, DTLPASSTHRUCHAR39, DTLPASSTHRUCHAR40,
DTLPASSTHRUDATE01, DTLPASSTHRUDATE02, DTLPASSTHRUDATE03, DTLPASSTHRUDATE04,
DTLPASSTHRUDOLL01, DTLPASSTHRUDOLL02, DTLPASSTHRUNUM01, DTLPASSTHRUNUM02,
DTLPASSTHRUNUM03, DTLPASSTHRUNUM04, DTLPASSTHRUNUM05, DTLPASSTHRUNUM06,
DTLPASSTHRUNUM07, DTLPASSTHRUNUM08, DTLPASSTHRUNUM09, DTLPASSTHRUNUM10,
DTLPASSTHRUNUM11, DTLPASSTHRUNUM12, DTLPASSTHRUNUM13, DTLPASSTHRUNUM14,
DTLPASSTHRUNUM15, DTLPASSTHRUNUM16, DTLPASSTHRUNUM17, DTLPASSTHRUNUM18,
DTLPASSTHRUNUM19, DTLPASSTHRUNUM20,
EXPANDED_WEBSYNAPSE_FIELDS
) as
 select
orderdtl.orderid,
orderdtl.shipid,
orderdtl.item,
orderdtl.lotnumber,
orderdtl.custid,
custitem.descr,
orderdtl.qtyorder,
orderdtl.qtyentered,
orderdtl.qtyrcvd,
orderdtl.qtyship,
orderdtl.uom,
substr(zit.uom_abbrev(orderdtl.uom),1,12),
orderdtl.uomentered,
substr(zit.uom_abbrev(orderdtl.uomentered),1,12),
substr(zci.hazardous_item(orderdtl.custid,orderdtl.item),1,1),
orderhdr.ordertype,
orderdtl.linestatus,
nvl(pkg_manage_orders.item_alias(orderdtl.custid,orderdtl.item),' '),
custitem.productgroup,
orderdtl.consigneesku,
zbol.orderdtlcomments(orderdtl.rowid),
orderdtl.dtlpassthruchar01,
orderdtl.dtlpassthruchar02,
orderdtl.dtlpassthruchar03,
orderdtl.dtlpassthruchar04,
orderdtl.dtlpassthruchar05,
orderdtl.dtlpassthruchar06,
orderdtl.dtlpassthruchar07,
orderdtl.dtlpassthruchar08,
orderdtl.dtlpassthruchar09,
orderdtl.dtlpassthruchar10,
orderdtl.dtlpassthruchar11,
orderdtl.dtlpassthruchar12,
orderdtl.dtlpassthruchar13,
orderdtl.dtlpassthruchar14,
orderdtl.dtlpassthruchar15,
orderdtl.dtlpassthruchar16,
orderdtl.dtlpassthruchar17,
orderdtl.dtlpassthruchar18,
orderdtl.dtlpassthruchar19,
orderdtl.dtlpassthruchar20,
orderdtl.dtlpassthruchar21,
orderdtl.dtlpassthruchar22,
orderdtl.dtlpassthruchar23,
orderdtl.dtlpassthruchar24,
orderdtl.dtlpassthruchar25,
orderdtl.dtlpassthruchar26,
orderdtl.dtlpassthruchar27,
orderdtl.dtlpassthruchar28,
orderdtl.dtlpassthruchar29,
orderdtl.dtlpassthruchar30,
orderdtl.dtlpassthruchar31,
orderdtl.dtlpassthruchar32,
orderdtl.dtlpassthruchar33,
orderdtl.dtlpassthruchar34,
orderdtl.dtlpassthruchar35,
orderdtl.dtlpassthruchar36,
orderdtl.dtlpassthruchar37,
orderdtl.dtlpassthruchar38,
orderdtl.dtlpassthruchar39,
orderdtl.dtlpassthruchar40,
to_char(orderdtl.dtlpassthrudate01,'MMDDYYYY'),
to_char(orderdtl.dtlpassthrudate02,'MMDDYYYY'),
to_char(orderdtl.dtlpassthrudate03,'MMDDYYYY'),
to_char(orderdtl.dtlpassthrudate04,'MMDDYYYY'),
orderdtl.dtlpassthrudoll01,
orderdtl.dtlpassthrudoll02,
orderdtl.dtlpassthrunum01,
orderdtl.dtlpassthrunum02,
orderdtl.dtlpassthrunum03,
orderdtl.dtlpassthrunum04,
orderdtl.dtlpassthrunum05,
orderdtl.dtlpassthrunum06,
orderdtl.dtlpassthrunum07,
orderdtl.dtlpassthrunum08,
orderdtl.dtlpassthrunum09,
orderdtl.dtlpassthrunum10,
orderdtl.dtlpassthrunum11,
orderdtl.dtlpassthrunum12,
orderdtl.dtlpassthrunum13,
orderdtl.dtlpassthrunum14,
orderdtl.dtlpassthrunum15,
orderdtl.dtlpassthrunum16,
orderdtl.dtlpassthrunum17,
orderdtl.dtlpassthrunum18,
orderdtl.dtlpassthrunum19,
orderdtl.dtlpassthrunum20,
nvl(orderhdr.expanded_websynapse_fields,'N')
from orderhdr, orderdtl, custitem
where orderhdr.orderid = orderdtl.orderid
  and orderhdr.shipid = orderdtl.shipid
  and orderdtl.custid = custitem.custid
  and orderdtl.item = custitem.item;

comment on table WEBORDERDTLVIEW is '$Id$';

exit;

