CREATE OR REPLACE VIEW ZEN_RPT_BOLRPT
(
       OH_orderid,
       OH_shipid,
       OH_entrydate,
       OH_apptdate,
       OH_shipdate,
       OH_po,
       OH_orderstatus,
       OH_billoflading,
       OH_arrivaldate,
       OH_loadno,
       OH_reference,
       CN_name,
       CN_addr1,
       CN_addr2,
       CN_city,
       CN_state,
       CN_postalcode,
       CN_countrycode,
       CR_name,
       CR_addr1,
       CR_addr2,
       CR_city,
       CR_state,
       CR_postalcode,
       CR_countrycode,
       CAR_name,
       CR_scac,
       CU_custid,
       CU_name,
       CU_addr1,
       CU_addr2,
       CU_city,
       CU_state,
       CU_postalcode,
       CU_countrycode,
       OD_orderid,
       OD_shipid,
       OD_item,
       SP_item,
       OD_qtyship,
       OD_uomship,
       OD_weightship,
       OD_lotnumber,
       OD_lotnumber_null,
       FAC_name,
       FAC_addr1,
       FAC_addr2,
       FAC_city,
       FAC_state,
       FAC_postalcode,
       FAC_countrycode,
       LD_trailer,
       LD_seal,
       LD_prono,
       ODC_item,
       CI_descr,
       CI_hazardous,
       CI_lotsumbol,
       ST_abbrev,
       STRM_abbrev,
       PO_NUMBER,
       DATE_SHIPPED,
       QTY_ORDERED,
       QTY_ENTERED,
       UOM_ENTERED,
       OD_CUBEORDER,
       OD_CUBESHIP,
       OD_WEIGHTORDER,
       CHEMCODE,
       BASEUOMSHIP,
       BASEUOM,
       SECONDARYCHEMCODE,
       TERTIARYCHEMCODE,
       QUATERNARYCHEMCODE,
       IMOPRIMARYCHEMCODE,
       IMOSECONDARYCHEMCODE,
       IMOTERTIARYCHEMCODE,
       IMOQUATERNARYCHEMCODE,
       IATAPRIMARYCHEMCODE,
       IATASECONDARYCHEMCODE,
       IATATERTIARYCHEMCODE,
       IATAQUATERNARYCHEMCODE,
       COD,
       COD_AMOUNT, 
       OH_SHIPTYPE,
       OH_COMPANYCHECKOK,
       GROSSWEIGHT,
       OH_CONSIGNEE,
       SP_QUANTITY,
       SP_WEIGHT,
       OH_SHIPTO
)
as
select
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       zlbl.uom_qty_conv(od.custid,sp.item,od.qtyship,od.uom,OD.UOMENTERED),
       OD.uom,
       OD.weightship,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
       OH.HDRPASSTHRUCHAR03,
       OH.DATESHIPPED,
       OD.QTYORDER,
       OD.QTYENTERED,
       OD.UOMENTERED,
       OD.CUBEORDER,
       sum(zlbl.uom_qty_conv(od.custid,sp.item,SP.quantity,od.uom,ci.baseuom) * CI.cube/1728), 
       OD.WEIGHTORDER,
       CI.primarychemcode,
       zlbl.uom_qty_conv(od.custid,sp.item,od.qtyship,od.uom,ci.baseuom), 
       CI.baseuom,
       CI.SECONDARYCHEMCODE,
       CI.TERTIARYCHEMCODE,
       CI.QUATERNARYCHEMCODE,
       CI.IMOPRIMARYCHEMCODE,
       CI.IMOSECONDARYCHEMCODE,
       CI.IMOTERTIARYCHEMCODE,
       CI.IMOQUATERNARYCHEMCODE,
       CI.IATAPRIMARYCHEMCODE,
       CI.IATASECONDARYCHEMCODE,
       CI.IATATERTIARYCHEMCODE,
       CI.IATAQUATERNARYCHEMCODE,
       OH.cod,
       OH.amtcod,
       OH.shiptype,
       OH.companycheckok,
       sum(SP.weight + (zlbl.uom_qty_conv(od.custid,sp.item,SP.quantity,od.uom,ci.baseuom) * nvl(ci.tareweight,0))),
       OH.CONSIGNEE,
       sum(sp.quantity),
       sum(sp.weight),
       OH.SHIPTO
from
    orderhdr OH,
    consignee CN,
    consignee CNS,
    carrier CR,
    custitem CI,
    customer CU,
    orderdtl OD,
    shippingplate SP,
    facility FAC,
    loads LD,
    orderdtlbolcomments ODC,
    shipmenttypes ST,
    shipmentterms STRM
where
    nvl(OH.consignee,OH.shipto) = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.custid = CU.custid(+) and
    OH.orderid = OD.orderid and
    OH.shipid = OD.shipid and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OD.custid = CI.custid and
    SP.item = CI.item and
    OD.orderid = ODC.orderid(+) and
    OD.shipid = ODC.shipid(+) and
    OD.item = ODC.item(+) and
    OD.orderid = SP.orderid and
    OD.shipid = SP.shipid and
    OD.item = SP.orderitem and
    SP.type in ('F','P') and
    SP.status = 'SH' and
    nvl(OD.lotnumber,'(none)') = nvl(SP.orderlot,'(none)') and
    nvl(OD.lotnumber,'(none)') = nvl(ODC.lotnumber(+),'(none)') and
    OH.shiptype = ST.code (+) and
    OH.shipterms = STRM.code (+) and
    (OH.orderstatus = '8' or
    OH.orderstatus = '9')
group by
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       OD.qtyship,
       OD.uom,
       OD.weightship,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
       OH.HDRPASSTHRUCHAR03,
       OH.DATESHIPPED,
       OD.QTYORDER,
       OD.QTYENTERED,
       OD.UOMENTERED,
       OD.CUBEORDER,
       OD.WEIGHTORDER,
       CI.primarychemcode,
       OD.custid,
       OD.uom,
       CI.baseuom,
       CI.SECONDARYCHEMCODE,
       CI.TERTIARYCHEMCODE,
       CI.QUATERNARYCHEMCODE,
       CI.IMOPRIMARYCHEMCODE,
       CI.IMOSECONDARYCHEMCODE,
       CI.IMOTERTIARYCHEMCODE,
       CI.IMOQUATERNARYCHEMCODE,
       CI.IATAPRIMARYCHEMCODE,
       CI.IATASECONDARYCHEMCODE,
       CI.IATATERTIARYCHEMCODE,
       CI.IATAQUATERNARYCHEMCODE,
       OH.cod,
       OH.amtcod,
       OH.shiptype,
       OH.companycheckok,
       OH.CONSIGNEE,
       OH.SHIPTO;

comment on table zen_rpt_bolrpt is '$Id$';        

exit;

