CREATE OR REPLACE VIEW ZEN_RPT_CONSOLBOLRPT
(
       OH_orderid,
       OH_shipid,
       OH_entrydate,
       OH_apptdate,
       OH_shipdate,
       OH_po,
       OH_orderstatus,
       OH_billoflading,
       OH_arrivaldate,
       OH_loadno,
       OH_reference,
       CN_id,
       CN_name,
       CN_addr1,
       CN_addr2,
       CN_city,
       CN_state,
       CN_postalcode,
       CN_postalcode_short,
       CN_countrycode,
       CR_name,
       CR_addr1,
       CR_addr2,
       CR_city,
       CR_state,
       CR_postalcode,
       CR_countrycode,
       CAR_name,
       CR_scac,
       CU_custid,
       CU_name,
       CU_addr1,
       CU_addr2,
       CU_city,
       CU_state,
       CU_postalcode,
       CU_countrycode,
       OD_orderid,
       OD_shipid,
       OD_item,
       SP_item,
       OD_qtyship,
       OD_uomship,
       OD_weightship,
       OD_cubeship,
       OD_lotnumber,
       OD_lotnumber_null,
       FAC_name,
       FAC_addr1,
       FAC_addr2,
       FAC_city,
       FAC_state,
       FAC_postalcode,
       FAC_countrycode,
       LD_trailer,
       LD_seal,
       LD_prono,
       ODC_item,
       CI_descr,
       CI_hazardous,
       CI_lotsumbol,
       ST_abbrev,
       STRM_abbrev,
       PO_NUMBER,
       DATE_SHIPPED,
       QTY_ORDERED,
       QTY_ENTERED,
       UOM_ENTERED,
       OD_CUBEORDER,
       OD_WEIGHTORDER,
       CHEMCODE,
       BASEUOMSHIP,
       BASEUOM,
       SECONDARYCHEMCODE,
       TERTIARYCHEMCODE,
       QUATERNARYCHEMCODE,
       IMOPRIMARYCHEMCODE,
       IMOSECONDARYCHEMCODE,
       IMOTERTIARYCHEMCODE,
       IMOQUATERNARYCHEMCODE,
       IATAPRIMARYCHEMCODE,
       IATASECONDARYCHEMCODE,
       IATATERTIARYCHEMCODE,
       IATAQUATERNARYCHEMCODE,
       COD,
       COD_AMOUNT, 
       OH_SHIPTYPE,
       OH_COMPANYCHECKOK,
       GROSSWEIGHT,
       OH_CONSIGNEE,
       SP_QUANTITY,
       SP_WEIGHT,
       SP_CUBE,
       OH_SHIPTO,
       OH_HDRPASSTHRUCHAR01,
       PCS_QTY,
       CTN_QTY,
       CI_ITMPASSTHRUNUM01,
       OD_DTLPASSTHRUCHAR01,
       OH_HDRPASSTHRUCHAR02,
       OH_SHIPTERMS,
       ITMPASSTHRUPCS_QTY,
       ITMPASSTHRUCTN_QTY,
       OH_HDRPASSTHRUNUM01,
       ORDERHDRBOLCOMMENTS
)
as
select
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.consignee,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       substr(decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),1,5),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       zlbl.uom_qty_conv(od.custid,sp.item,od.qtyship,od.uom,OD.UOMENTERED),
       OD.uom,
       OD.weightship,
       OD.cubeship,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
       OH.HDRPASSTHRUCHAR03,
       OH.DATESHIPPED,
       OD.QTYORDER,
       OD.QTYENTERED,
       OD.UOMENTERED,
       OD.CUBEORDER,
       OD.WEIGHTORDER,
       CI.primarychemcode,
       zlbl.uom_qty_conv(od.custid,sp.item,od.qtyship,od.uom,ci.baseuom), 
       CI.baseuom,
       CI.SECONDARYCHEMCODE,
       CI.TERTIARYCHEMCODE,
       CI.QUATERNARYCHEMCODE,
       CI.IMOPRIMARYCHEMCODE,
       CI.IMOSECONDARYCHEMCODE,
       CI.IMOTERTIARYCHEMCODE,
       CI.IMOQUATERNARYCHEMCODE,
       CI.IATAPRIMARYCHEMCODE,
       CI.IATASECONDARYCHEMCODE,
       CI.IATATERTIARYCHEMCODE,
       CI.IATAQUATERNARYCHEMCODE,
       OH.cod,
       OH.amtcod,
       OH.shiptype,
       OH.companycheckok,
       sum(SP.weight) + (zlbl.uom_qty_conv(od.custid,sp.item,sum(SP.quantity),od.uom,ci.baseuom) * nvl(ci.tareweight,0)),
       OH.CONSIGNEE,
       sum(sp.quantity),
       sum(sp.weight),
       zlbl.uom_qty_conv(od.custid,sp.item,sum(SP.quantity),od.uom,ci.baseuom) * CI.cube/1728, 
       OH.SHIPTO,
       OH.HDRPASSTHRUCHAR01,
       decode(od.uom,'PCS',sum(sp.quantity),nvl(zlbl.uom_qty_conv(od.custid,sp.item,sum(sp.quantity),od.uom,'PCS'),0)),
       decode(od.uom,'CTN',sum(sp.quantity),nvl(zlbl.uom_qty_conv(od.custid,sp.item,sum(sp.quantity),od.uom,'CTN'),0)),
       CI.itmpassthrunum01,
       OD.dtlpassthruchar01,
       OH.HDRPASSTHRUCHAR02,
       OH.SHIPTERMS,
       decode(CI.itmpassthrunum01,null,null,0,null,decode(od.uom,'PCS',sum(sp.quantity),sum(sp.quantity)*CI.itmpassthrunum01)),
       decode(CI.itmpassthrunum01,null,null,0,null,decode(od.uom,'CTN',sum(sp.quantity),sum(sp.quantity)/CI.itmpassthrunum01)),
       OH.HDRPASSTHRUNUM01,
       zbol.orderhdrbolcomments(OH.orderid,OH.shipid)
from
    shippingplate SP,
    orderhdr OH,
    orderdtl OD,
    orderdtlbolcomments ODC,
    customer CU,
    consignee CN,
    consignee CNS,
    carrier CR,
    custitem CI,
    facility FAC,
    loads LD,
    shipmenttypes ST,
    shipmentterms STRM
where
    SP.orderid = OH.orderid and
    SP.shipid = OH.shipid and
    OD.orderid = OH.orderid and
    OD.shipid = OH.shipid and
    SP.status = 'SH' and
    SP.orderitem = OD.item and
    nvl(SP.orderlot,'(none)') = nvl(OD.lotnumber,'(none)') and
    SP.type in ('F','P') and
    OD.orderid = ODC.orderid(+) and
    OD.shipid = ODC.shipid(+) and
    OD.item = ODC.item(+) and
    nvl(OD.lotnumber,'(none)') = nvl(ODC.lotnumber(+),'(none)') and
    OH.custid = CU.custid and
    nvl(OH.consignee,OH.shipto) = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OD.custid = CI.custid and
    SP.item = CI.item and
    OH.shiptype = ST.code (+) and
    OH.shipterms = STRM.code (+) and
    (OH.orderstatus = '8' or
    OH.orderstatus = '9')
group by
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.consignee,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       substr(decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),1,5),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', CN.name,
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', CN.addr1,
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', CN.addr2,
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', CN.city,
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', CN.state,
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', CN.postalcode,
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', CN.countrycode,
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       OD.qtyship,
       OD.uom,
       OD.weightship,
       OD.cubeship,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
       OH.HDRPASSTHRUCHAR03,
       OH.DATESHIPPED,
       OD.QTYORDER,
       OD.QTYENTERED,
       OD.UOMENTERED,
       OD.CUBEORDER,
       CI.cube,
       OD.WEIGHTORDER,
       CI.primarychemcode,
       OD.custid,
       OD.uom,
       CI.baseuom,
       CI.SECONDARYCHEMCODE,
       CI.TERTIARYCHEMCODE,
       CI.QUATERNARYCHEMCODE,
       CI.IMOPRIMARYCHEMCODE,
       CI.IMOSECONDARYCHEMCODE,
       CI.IMOTERTIARYCHEMCODE,
       CI.IMOQUATERNARYCHEMCODE,
       CI.IATAPRIMARYCHEMCODE,
       CI.IATASECONDARYCHEMCODE,
       CI.IATATERTIARYCHEMCODE,
       CI.IATAQUATERNARYCHEMCODE,
       OH.cod,
       OH.amtcod,
       OH.shiptype,
       OH.companycheckok,
       ci.tareweight,
       OH.CONSIGNEE,
       OH.SHIPTO,
       OH.HDRPASSTHRUCHAR01,
       CI.itmpassthrunum01,
       OD.dtlpassthruchar01,
       OH.HDRPASSTHRUCHAR02,
       OH.SHIPTERMS,
       OH.HDRPASSTHRUNUM01,
       zbol.orderhdrbolcomments(OH.orderid,OH.shipid);

comment on table zen_rpt_consolbolrpt is '$Id$';        

CREATE OR REPLACE VIEW ZEN_RPT_CONSOLBOLRPT_BROY
(
       OH_orderid,
       OH_shipid,
       OH_entrydate,
       OH_apptdate,
       OH_shipdate,
       OH_po,
       OH_orderstatus,
       OH_billoflading,
       OH_arrivaldate,
       OH_loadno,
       OH_reference,
       CN_id,
       CN_name,
       CN_addr1,
       CN_addr2,
       CN_city,
       CN_state,
       CN_postalcode,
       CN_postalcode_short,
       CN_countrycode,
       CR_name,
       CR_addr1,
       CR_addr2,
       CR_city,
       CR_state,
       CR_postalcode,
       CR_countrycode,
       CAR_name,
       CR_scac,
       CU_custid,
       CU_name,
       CU_addr1,
       CU_addr2,
       CU_city,
       CU_state,
       CU_postalcode,
       CU_countrycode,
       OD_orderid,
       OD_shipid,
       OD_item,
       SP_item,
       OD_qtyship,
       OD_uomship,
       OD_weightship,
       OD_cubeship,
       OD_lotnumber,
       OD_lotnumber_null,
       FAC_name,
       FAC_addr1,
       FAC_addr2,
       FAC_city,
       FAC_state,
       FAC_postalcode,
       FAC_countrycode,
       LD_trailer,
       LD_seal,
       LD_prono,
       ODC_item,
       CI_descr,
       CI_hazardous,
       CI_lotsumbol,
       ST_abbrev,
       STRM_abbrev,
       PO_NUMBER,
       DATE_SHIPPED,
       QTY_ORDERED,
       QTY_ENTERED,
       UOM_ENTERED,
       OD_CUBEORDER,
       OD_WEIGHTORDER,
       CHEMCODE,
       BASEUOMSHIP,
       BASEUOM,
       SECONDARYCHEMCODE,
       TERTIARYCHEMCODE,
       QUATERNARYCHEMCODE,
       IMOPRIMARYCHEMCODE,
       IMOSECONDARYCHEMCODE,
       IMOTERTIARYCHEMCODE,
       IMOQUATERNARYCHEMCODE,
       IATAPRIMARYCHEMCODE,
       IATASECONDARYCHEMCODE,
       IATATERTIARYCHEMCODE,
       IATAQUATERNARYCHEMCODE,
       COD,
       COD_AMOUNT, 
       OH_SHIPTYPE,
       OH_COMPANYCHECKOK,
       GROSSWEIGHT,
       OH_CONSIGNEE,
       SP_QUANTITY,
       SP_WEIGHT,
       SP_CUBE,
       OH_SHIPTO,
       OH_HDRPASSTHRUCHAR01,
       PCS_QTY,
       CTN_QTY,
       CI_ITMPASSTHRUNUM01,
       OD_DTLPASSTHRUCHAR01,
       OH_HDRPASSTHRUCHAR02,
       OH_SHIPTERMS,
       ITMPASSTHRUPCS_QTY,
       ITMPASSTHRUCTN_QTY,
       OD_DTLPASSTHRUCHAR03,
       OD_DTLPASSTHRUNUM01
)
as
select
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.consignee,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1,OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2,OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city,OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state,OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode,OH.shiptopostalcode),
       substr(decode(OH.shiptoname,null,CNS.postalcode,OH.shiptopostalcode),1,5),
       decode(OH.shiptoname,null,CNS.countrycode,OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', decode(OH.billtoname,null,CN.name,OH.billtoname),
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', decode(OH.billtoname,null,CN.city,OH.billtocity),
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', decode(OH.billtoname,null,CN.state,OH.billtostate),
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       zlbl.uom_qty_conv(od.custid,sp.item,od.qtyship,od.uom,OD.UOMENTERED),
       OD.uom,
       OD.weightship,
       OD.cubeship,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
       OH.HDRPASSTHRUCHAR03,
       OH.DATESHIPPED,
       OD.QTYORDER,
       OD.QTYENTERED,
       OD.UOMENTERED,
       OD.CUBEORDER,
       OD.WEIGHTORDER,
       CI.primarychemcode,
       zlbl.uom_qty_conv(od.custid,sp.item,od.qtyship,od.uom,ci.baseuom), 
       CI.baseuom,
       CI.SECONDARYCHEMCODE,
       CI.TERTIARYCHEMCODE,
       CI.QUATERNARYCHEMCODE,
       CI.IMOPRIMARYCHEMCODE,
       CI.IMOSECONDARYCHEMCODE,
       CI.IMOTERTIARYCHEMCODE,
       CI.IMOQUATERNARYCHEMCODE,
       CI.IATAPRIMARYCHEMCODE,
       CI.IATASECONDARYCHEMCODE,
       CI.IATATERTIARYCHEMCODE,
       CI.IATAQUATERNARYCHEMCODE,
       OH.cod,
       OH.amtcod,
       OH.shiptype,
       OH.companycheckok,
       sum(SP.weight) + (zlbl.uom_qty_conv(od.custid,sp.item,sum(sp.quantity),od.uom,ci.baseuom) * nvl(ci.tareweight,0)),
       OH.CONSIGNEE,
       sum(sp.quantity),
       sum(sp.weight),
       zlbl.uom_qty_conv(od.custid,sp.item,sum(SP.quantity),od.uom,ci.baseuom) * CI.cube/1728, 
       OH.SHIPTO,
       OH.HDRPASSTHRUCHAR01,
       decode(od.uom,'PCS',sum(sp.quantity),nvl(zlbl.uom_qty_conv(od.custid,sp.item,sum(sp.quantity),od.uom,'PCS'),0)),
       decode(od.uom,'CTN',sum(sp.quantity),nvl(zlbl.uom_qty_conv(od.custid,sp.item,sum(sp.quantity),od.uom,'CTN'),0)),
       CI.itmpassthrunum01,
       OD.dtlpassthruchar01,
       OH.HDRPASSTHRUCHAR02,
       OH.SHIPTERMS,
       decode(CI.itmpassthrunum01,null,null,0,null,decode(od.uom,'PCS',sum(sp.quantity),sum(sp.quantity)*CI.itmpassthrunum01)),
       decode(CI.itmpassthrunum01,null,null,0,null,decode(od.uom,'CTN',sum(sp.quantity),sum(sp.quantity)/CI.itmpassthrunum01)),
       OD.dtlpassthruchar03,
       OD.dtlpassthrunum01
from
    shippingplate SP,
    orderhdr OH,
    orderdtl OD,
    orderdtlbolcomments ODC,
    customer CU,
    consignee CN,
    consignee CNS,
    carrier CR,
    custitem CI,
    facility FAC,
    loads LD,
    shipmenttypes ST,
    shipmentterms STRM
where SP.orderid = OH.orderid and
    SP.shipid = OH.shipid and
    OD.orderid = OH.orderid and
    OD.shipid = OH.shipid and
    SP.status = 'SH' and
    SP.orderitem = OD.item and
    nvl(SP.orderlot,'(none)') = nvl(OD.lotnumber,'(none)') and
    SP.type in ('F','P') and
    OD.orderid = ODC.orderid(+) and
    OD.shipid = ODC.shipid(+) and
    OD.item = ODC.item(+) and
    nvl(OD.lotnumber,'(none)') = nvl(ODC.lotnumber(+),'(none)') and
    OH.custid = CU.custid and
    nvl(OH.consignee,OH.shipto) = CN.consignee(+) and
    OH.shipto = CNS.consignee(+) and
    OH.carrier = CR.carrier(+) and
    OH.fromfacility = FAC.facility(+) and
    OH.loadno = LD.loadno(+) and
    OD.custid = CI.custid and
    SP.item = CI.item and
    OH.shiptype = ST.code (+) and
    OH.shipterms = STRM.code (+) and
    (OH.orderstatus = '8' or
    OH.orderstatus = '9')
group by
       OH.orderid,
       OH.shipid,
       OH.entrydate,
       OH.apptdate,
       OH.shipdate,
       OH.po,
       OH.orderstatus,
       OH.billoflading,
       OH.arrivaldate,
       OH.loadno,
       OH.reference,
       decode(OH.shiptoname,null,CNS.consignee,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.name,OH.shiptoname),
       decode(OH.shiptoname,null,CNS.addr1, OH.shiptoaddr1),
       decode(OH.shiptoname,null,CNS.addr2, OH.shiptoaddr2),
       decode(OH.shiptoname,null,CNS.city, OH.shiptocity),
       decode(OH.shiptoname,null,CNS.state, OH.shiptostate),
       decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),
       substr(decode(OH.shiptoname,null,CNS.postalcode, OH.shiptopostalcode),1,5),
       decode(OH.shiptoname,null,CNS.countrycode, OH.shiptocountrycode),
       decode(OH.shipterms,
                'PPD', CU.name,
                'COL', decode(OH.billtoname,null,CN.name,OH.billtoname),
                '3RD',
                  decode(OH.billtoname,null,CN.name,OH.billtoname),
                CU.name),
       decode(OH.shipterms,
                'PPD', CU.addr1,
                'COL', decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                '3RD',
                  decode(OH.billtoname,null,CN.addr1,OH.billtoaddr1),
                CU.addr1),
       decode(OH.shipterms,
                'PPD', CU.addr2,
                'COL', decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                '3RD',
                  decode(OH.billtoname,null,CN.addr2,OH.billtoaddr2),
                CU.addr2),
       decode(OH.shipterms,
                'PPD', CU.city,
                'COL', decode(OH.billtoname,null,CN.city,OH.billtocity),
                '3RD',
                  decode(OH.billtoname,null,CN.city, OH.billtocity),
                CU.city),
       decode(OH.shipterms,
                'PPD', CU.state,
                'COL', decode(OH.billtoname,null,CN.state,OH.billtostate),
                '3RD',
                  decode(OH.billtoname,null,CN.state,OH.billtostate),
                CU.state),
       decode(OH.shipterms,
                'PPD', CU.postalcode,
                'COL', decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                '3RD',
                  decode(OH.billtoname,null,CN.postalcode,OH.billtopostalcode),
                CU.postalcode),
       decode(OH.shipterms,
                'PPD', CU.countrycode,
                'COL', decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                '3RD',
                  decode(OH.billtoname,null,CN.countrycode,OH.billtocountrycode),
                CU.countrycode),
       CR.name,
       CR.scac,
       CU.custid,
       CU.name,
       CU.addr1,
       CU.addr2,
       CU.city,
       CU.state,
       CU.postalcode,
       CU.countrycode,
       OD.orderid,
       OD.shipid,
       OD.item,
       SP.item,
       OD.qtyship,
       OD.uom,
       OD.weightship,
       OD.cubeship,
       decode(CI.lotsumbol,'Y',null,SP.lotnumber),
       nvl(SP.orderlot,'**NULL**'),
       FAC.name,
       FAC.addr1,
       FAC.addr2,
       FAC.city,
       FAC.state,
       FAC.postalcode,
       FAC.countrycode,
       LD.trailer,
       LD.seal,
       LD.prono,
       ODC.item,
       CI.descr,
       CI.hazardous,
       CI.lotsumbol,
       ST.abbrev,
       STRM.abbrev,
       OH.HDRPASSTHRUCHAR03,
       OH.DATESHIPPED,
       OD.QTYORDER,
       OD.QTYENTERED,
       OD.UOMENTERED,
       OD.CUBEORDER,
       CI.cube,
       OD.WEIGHTORDER,
       CI.primarychemcode,
       OD.custid,
       OD.uom,
       CI.baseuom,
       CI.SECONDARYCHEMCODE,
       CI.TERTIARYCHEMCODE,
       CI.QUATERNARYCHEMCODE,
       CI.IMOPRIMARYCHEMCODE,
       CI.IMOSECONDARYCHEMCODE,
       CI.IMOTERTIARYCHEMCODE,
       CI.IMOQUATERNARYCHEMCODE,
       CI.IATAPRIMARYCHEMCODE,
       CI.IATASECONDARYCHEMCODE,
       CI.IATATERTIARYCHEMCODE,
       CI.IATAQUATERNARYCHEMCODE,
       OH.cod,
       OH.amtcod,
       OH.shiptype,
       OH.companycheckok,
       ci.tareweight,
       OH.CONSIGNEE,
       OH.SHIPTO,
       OH.HDRPASSTHRUCHAR01,
       CI.itmpassthrunum01,
       OD.dtlpassthruchar01,
       OH.HDRPASSTHRUCHAR02,
       OH.SHIPTERMS,
       OD.dtlpassthruchar03,
       OD.dtlpassthrunum01;
       
comment on table zen_rpt_consolbolrpt_broy is '$Id$';        

exit;

