drop view ber_hlhgirlscoutactivityrptvw;


create view ber_hlhgirlscoutactivityrptvw as
SELECT DISTINCT SHIPPINGPLATE.QUANTITY, SHIPPINGPLATE.TRACKINGNO, ORDERHDR.CUSTID, 
	ORDERHDR.PO, ORDERHDR.SHIPTONAME, ORDERDTL.LASTUPDATE, ORDERHDR.SHIPTOCITY, 
	ORDERHDR.SHIPTOSTATE, ORDERHDR.SHIPTOPOSTALCODE, CUSTITEM.DESCR, ORDERHDR.SHIPTYPE, 
	CUSTOMER.NAME, ORDERHDR.ORDERID, SHIPPINGPLATE.INVENTORYCLASS
FROM   	ALPS.BER_LF_HEADER ORDERHDR, ALPS.ORDERDTL ORDERDTL, ALPS.CUSTOMER CUSTOMER,
	ALPS.SHIPPINGPLATE SHIPPINGPLATE, ALPS.CUSTITEM CUSTITEM
 WHERE  ((ORDERHDR.CUSTID=ORDERDTL.CUSTID) AND (ORDERHDR.ORDERID=ORDERDTL.ORDERID)) AND 
	(ORDERHDR.CUSTID=CUSTOMER.CUSTID) AND (((ORDERDTL.ITEM=SHIPPINGPLATE.ITEM) AND
 	(ORDERDTL.CUSTID=SHIPPINGPLATE.CUSTID)) AND (ORDERDTL.ORDERID=SHIPPINGPLATE.ORDERID)) AND 
	((SHIPPINGPLATE.CUSTID=CUSTITEM.CUSTID) AND (SHIPPINGPLATE.ITEM=CUSTITEM.ITEM));

comment on table ber_hlhgirlscoutactivityrptvw is '$Id: ber_hlgirlscoutactivityrptvw.sql 1 2005-05-26 12:20:03Z ed $';

exit;
