--
-- $Id$
--
CREATE TABLE ALPS.TMSPLANSHIP_RELTOIP 
(
    TRANSMISSIONCREATEDATETIME    DATE             NULL,
    SENDERTRANSMISSIONNO          NUMBER           NULL,
    REFERENCETRANSMISSIONNO       NUMBER           NULL,
    RELEASE                       VARCHAR2(40)     NULL,
    INVOLVEDPARTYQUALIFIER        VARCHAR2(40)     NULL,
    LOCATIONREFDOMAINNAME         VARCHAR2(20)     NULL,
    LOCATIONREF                   VARCHAR2(40)     NULL,
    CONTACTREFDOMAINNAME          VARCHAR2(20)     NULL,
    CONTACTREF                    VARCHAR2(40)     NULL,
    CONTACTTRANSACTIONCODE        VARCHAR2(40)     NULL,
    CONTACTEMAILADDRESS           VARCHAR2(40)     NULL,
    CONTACTLANGUAGESPOKEN         VARCHAR2(40)     NULL,
    ISPRIMARYCONTACT              VARCHAR2(1)      NULL,
    COMMETHODRANK                 NUMBER           NULL,
    CONTACTREFCOMMETHOD           VARCHAR2(40)     NULL,
    EXPECTEDRESPONSEDURATIONVALUE NUMBER           NULL,
    EXPECTEDRESPONSEDURATIONUOM   VARCHAR2(20)     NULL,
    COMMETHOD                     VARCHAR2(40)     NULL
);
exit;
