--
-- $Id$
--
CREATE TABLE ALPS.TMSPLANSHIP_RELSTAT 
(
    TRANSMISSIONCREATEDATETIME  DATE             NULL,
    SENDERTRANSMISSIONNO        NUMBER           NULL,
    REFERENCETRANSMISSIONNO     NUMBER           NULL,
    RELEASE                     VARCHAR2(40)     NULL,
    STATUSTYPEDOMAINNAME        VARCHAR2(20)     NULL,
    STATUSTYPE                  VARCHAR2(60)     NULL,
    STATUSVALUEDOMAINNAME       VARCHAR2(20)     NULL,
    STATUSVALUE                 VARCHAR2(60)     NULL
);
exit;
