--
-- $Id$
--
CREATE TABLE ALPS.TMSPLANSHIP_RELREFNUM 
(
    TRANSMISSIONCREATEDATETIME DATE             NULL,
    SENDERTRANSMISSIONNO       NUMBER           NULL,
    REFERENCETRANSMISSIONNO    NUMBER           NULL,
    RELEASE                    VARCHAR2(40)     NULL,
    RELEASEREFNUMDOMAINNAME    VARCHAR2(20)     NULL,
    RELEASEREFNUM              VARCHAR2(40)     NULL,
    RELEASEREFNUMVALUE         VARCHAR2(40)     NULL
);
exit;
