--
-- $Id$
--
CREATE TABLE ALPS.TMSPLANSHIP_SHIPHDR2 
(
    TRANSMISSIONCREATEDATETIME DATE             NULL,
    SENDERTRANSMISSIONNO       NUMBER           NULL,
    REFERENCETRANSMISSIONNO    NUMBER           NULL,
    ISAUTOMERGECONSOLIDATE     VARCHAR2(1)      NULL,
    PERSPECTIVE                VARCHAR2(10)     NULL,
    ITINERARYDOMAINNAME        VARCHAR2(20)     NULL,
    ITINERARY                  VARCHAR2(40)     NULL,
    PARENTLEGDOMAINNAME        VARCHAR2(20)     NULL,
    PARENTLEG                  VARCHAR2(40)     NULL,
    SHIPMENTASWORK             VARCHAR2(1)      NULL,
    FEASIBILITY                VARCHAR2(20)     NULL,
    CHECKTIMECONSTRAINT        VARCHAR2(1)      NULL,
    CHECKCOSTCONSTRAINT        VARCHAR2(1)      NULL,
    CHECKCAPACITYCONSTRAINT    VARCHAR2(1)      NULL,
    WEIGHTCODE                 VARCHAR2(1)      NULL,
    RULE7                      VARCHAR2(1)      NULL,
    SHIPMENTRELEASED           VARCHAR2(1)      NULL,
    DIMWEIGHTVALUE             FLOAT(5)         NULL,
    DIMWEIGHTUOM               VARCHAR2(10)     NULL,
    ISPRELOAD                  VARCHAR2(1)      NULL,
    BULKPLANDOMAINNAME         VARCHAR2(20)     NULL,
    BULKPLAN                   VARCHAR2(40)     NULL,
    INTRAILERBUILD             VARCHAR2(1)      NULL
);
exit;
