--
-- $Id$
--
CREATE TABLE ALPS.TMSPLANSHIP_RELTORN 
(
    TRANMISSIONCREATEDATETIME DATE             NULL,
    SENDERTRANSMISSIONNO      NUMBER           NULL,
    REFERENCETRANSMISSIONNO   NUMBER           NULL,
    RELEASE                   VARCHAR2(40)     NULL,
    REFNUMQUALIFIERDOMAINNAME VARCHAR2(20)     NULL,
    REFNUMQUALIFIER           VARCHAR2(40)     NULL,
    REFNUMVALUE               VARCHAR2(40)     NULL
);
exit;
