--
-- $Id$
--
CREATE TABLE ALPS.TMSPLANSHIP_SHIPUNIT 
(
    TRANSMISSIONCREATEDATETIME DATE             NULL,
    SENDERTRANSMISSIONNO       NUMBER           NULL,
    REFERENCETRANSMISSIONNO    NUMBER           NULL,
    SHIPUNITDOMAINNAME         VARCHAR2(20)     NULL,
    SHIPUNIT                   VARCHAR2(40)     NULL,
    SHIPUNITSPECDOMAINNAME     VARCHAR2(20)     NULL,
    SHIPUNITSPEC               VARCHAR2(40)     NULL,
    SHIPTOLOCATIONDOMAINNAME   VARCHAR2(20)     NULL,
    SHIPTOLOCATION             VARCHAR2(40)     NULL,
    WEIGHTVALUE                FLOAT(5)         NULL,
    WEIGHTUOM                  VARCHAR2(20)     NULL,
    VOLUMEVALUE                FLOAT(5)         NULL,
    VOLUMEUOM                  VARCHAR2(20)     NULL,
    UNITNETWEIGHTVALUE         FLOAT(5)         NULL,
    UNITNETWEIGHTUOM           VARCHAR2(20)     NULL,
    UNITNETVOLUMEVALUE         FLOAT(5)         NULL,
    UNITNETVOLUMEUOM           VARCHAR2(20)     NULL,
    LENGTHVALUE                FLOAT(5)         NULL,
    LENGTHUOM                  VARCHAR2(20)     NULL,
    WIDTHVALUE                 FLOAT(5)         NULL,
    WIDTHUOM                   VARCHAR2(20)     NULL,
    HEIGHTVALUE                FLOAT(5)         NULL,
    HEIGHTUOM                  VARCHAR2(20)     NULL,
    SHIPUNITCOUNT              NUMBER           NULL,
    RELEASESHIPUNITDOMAINNAME  VARCHAR2(20)     NULL,
    RELEASESHIPUNIT            VARCHAR2(40)     NULL,
    RECEIVEDNETWEIGHTVALUE     FLOAT(5)         NULL,
    RECEIVEDNETWEIGHTUOM       VARCHAR2(20)     NULL,
    RECEIVEDNETVOLUMEVALUE     FLOAT(5)         NULL,
    RECEIVEDNETVOLUMEUOM       VARCHAR2(20)     NULL
);
exit;
