--
-- $Id: alter_tbl_user_profile_02.sql 3006 2008-08-13 20:43:33Z ed $
--
ALTER TABLE ALPS.TBL_USER_PROFILE
MODIFY(FAX_AREA  NULL);


ALTER TABLE ALPS.TBL_USER_PROFILE
MODIFY(FAX_NUMBER  NULL);


ALTER TABLE ALPS.TBL_USER_PROFILE
MODIFY(PHONE_AREA  NULL);


ALTER TABLE ALPS.TBL_USER_PROFILE
MODIFY(PHONE_NUMBER  NULL);


exit;
