--
-- $Id$
--

DROP TABLE PALLETINVENTORY CASCADE CONSTRAINTS ; 

CREATE TABLE PALLETINVENTORY ( 
  CUSTID      VARCHAR2 (10)  NOT NULL, 
  FACILITY    VARCHAR2 (3)  NOT NULL, 
  PALLETTYPE  VARCHAR2 (12)  NOT NULL, 
  CNT         NUMBER (7)    NOT NULL
   ); 


CREATE UNIQUE INDEX PALLETINVENTORY_UNIQUE ON 
  PALLETINVENTORY(CUSTID, FACILITY, PALLETTYPE) ; 


exit;