create table BILL_3LINX_BASE
(ORDERID NUMBER(9) not null
,SHIPID NUMBER(2) not null
,CUSTID VARCHAR2(10) not null
,item varchar2(50)
,PARENTLPID VARCHAR2(15)
,TRACKINGNO VARCHAR2(30)
,QUANTITY NUMBER
);
