--
-- $Id$
--
CREATE TABLE CONSUMEHISTORY
(
  CUSTID      VARCHAR2(10)  NOT NULL,
  FACILITY    VARCHAR2(3)   NOT NULL,
  ORDERID     NUMBER(9)     NOT NULL,
  SHIPID      NUMBER(2)     NOT NULL,
  OWNER       VARCHAR2(10)  NOT NULL,
  item varchar2(50)  NOT NULL,
  LOCATION    VARCHAR2(10)  NOT NULL,
  QTY         NUMBER(7),
  LASTUSER    VARCHAR2(12),
  LASTUPDATE  DATE
);

CREATE UNIQUE INDEX CONSUMEHISTORY_UNIQUE ON CONSUMEHISTORY
  (CUSTID, FACILITY, ORDERID, SHIPID, ITEM, LASTUPDATE);

exit;
