--
-- $Id$
--
CREATE TABLE ALPS.CUSTWORKORDER ( 
SEQ NUMBER(16, 0) NOT NULL,
CUSTID VARCHAR2(10) NOT NULL,
item varchar2(50) NOT NULL,
REQUESTEDQTY NUMBER(16, 0) NOT NULL,
STATUS CHAR(1) NOT NULL
) ;
exit;