--
-- $Id$
--
CREATE TABLE CUSTITEMLOT (
  CUSTID      VARCHAR2(10) NOT NULL,
	item varchar2(50) NOT NULL,
	LOTNUMBER   VARCHAR2(30) NOT NULL,
  COFAFORMAT  VARCHAR2(255),
  LASTUSER    VARCHAR2(12),
	LASTUPDATE  DATE
);

CREATE UNIQUE INDEX CUSTITEMLOT_UNIQUE ON CUSTITEMLOT (CUSTID, ITEM, LOTNUMBER);

exit;
