--
-- $Id$
--
CREATE TABLE CUSTWORKORDERINSTRUCTIONS (
  SEQ NUMBER(8, 0) NOT NULL,
  SUBSEQ NUMBER(8, 0) NOT NULL,
  PARENT NUMBER(8, 0),
  ACTION VARCHAR2(2),
  NOTES LONG,
  TITLE VARCHAR2(35),
  QTY NUMBER(8, 0),
  COMPONENT VARCHAR2(20),
  DESTFACILITY VARCHAR2(3),
  DESTLOCATION VARCHAR2(10),
  DESTLOCTYPE VARCHAR2(12),
  STATUS CHAR(1),
  COMPLETEDQTY NUMBER(8,0)
); 
exit;
