--
-- $Id$
--
create table CUSTPRODUCTGROUP
(CUSTID VARCHAR2(10) not null
,PRODUCTGROUP VARCHAR2(4) not null
,DESCR VARCHAR2(32) not null
,ABBREV VARCHAR2(12)
,RATEGROUP VARCHAR2(10)
,LOTREQUIRED VARCHAR2(1)
,LOTRFTAG VARCHAR2(3)
,SERIALREQUIRED VARCHAR2(1)
,SERIALRFTAG VARCHAR2(3)
,USER1REQUIRED VARCHAR2(1)
,USER1RFTAG VARCHAR2(5)
,USER2REQUIRED VARCHAR2(1)
,USER2RFTAG VARCHAR2(5)
,USER3REQUIRED VARCHAR2(1)
,USER3RFTAG VARCHAR2(5)
,MFGDATEREQUIRED VARCHAR2(1)
,EXPDATEREQUIRED VARCHAR2(1)
,NODAMAGED VARCHAR2(1)
,COUNTRYREQUIRED VARCHAR2(1)
,BACKORDER VARCHAR2(2)
,ALLOWSUB VARCHAR2(1)
,INVSTATUSIND VARCHAR2(1)
,INVSTATUS VARCHAR2(255)
,INVCLASSIND VARCHAR2(1)
,INVENTORYCLASS VARCHAR2(255)
,QTYTYPE VARCHAR2(1)
,VARIANCEPCT NUMBER(3)
,SUBSLPRSNREQUIRED CHAR(1)
,FIFOWINDOWDAYS NUMBER(3)
,MAXQTYOF1 VARCHAR2(1)
,LOTFMTRULEID VARCHAR2(10)
,LOTFMTACTION VARCHAR2(1)
,SERIALFMTRULEID VARCHAR2(10)
,SERIALFMTACTION VARCHAR2(1)
,USER1FMTRULEID VARCHAR2(10)
,USER1FMTACTION VARCHAR2(1)
,USER2FMTRULEID VARCHAR2(10)
,USER2FMTACTION VARCHAR2(1)
,USER3FMTRULEID VARCHAR2(10)
,USER3FMTACTION VARCHAR2(1)
,LASTUSER VARCHAR2(12)
,LASTUPDATE DATE
);
exit;
