--
-- $Id$
--
create table deletedplate
(
   lpid              varchar2(15) not null,
   item varchar2(50),
   custid            varchar2(10),
   facility          varchar2(3),
   location          varchar2(10),
   status            varchar2(2),
   holdreason        varchar2(2),
   unitofmeasure     varchar2(4),
   quantity          number(7),
   type              varchar2(2),
   serialnumber      varchar2(30),
   lotnumber         varchar2(30),
   creationdate      date,
   manufacturedate   date,
   expirationdate    date,
   expiryaction      varchar2(2),
   lastcountdate     date,
   po                varchar2(10),
   recmethod         varchar2(2),
   condition         varchar2(2),
   lastoperator      varchar2(12),
   lasttask          varchar2(2),
   fifodate          date,
   destlocation      varchar2(10),
   destfacility      varchar2(3),
   countryof         varchar2(3),
   parentlpid        varchar2(15),
   useritem1         varchar2(20),
   useritem2         varchar2(20),
   useritem3         varchar2(20),
   disposition       varchar2(4),
   lastuser          varchar2(12),
   lastupdate        date,
   invstatus         varchar2(2),
   qtyentered        number(7),
   itementered       varchar2(20),
   uomentered        varchar2(4),
   inventoryclass    varchar2(2),
   loadno            number(7),
   stopno            number(7),
   shipno            number(7),
   orderid           number(7),
   shipid            number(2),
   weight            number(10,4)
);
exit;
