--
-- $Id$
--

DROP TABLE LASTTMSCUST_ALL CASCADE CONSTRAINTS ; 

CREATE TABLE LASTTMSCUST_ALL ( 
  CODE        VARCHAR2 (12)  NOT NULL, 
  DESCR       VARCHAR2 (32)  NOT NULL, 
  ABBREV      VARCHAR2 (12)  NOT NULL, 
  DTLUPDATE   VARCHAR2 (1), 
  LASTUSER    VARCHAR2 (12), 
  LASTUPDATE  DATE)
   TABLESPACE USERS NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 10240
   NEXT 10240
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 121
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE UNIQUE INDEX LASTTMSCUST_ALL_IDX ON 
  LASTTMSCUST_ALL(CODE) 
  TABLESPACE USERS PCTFREE 10  STORAGE(INITIAL 10240 NEXT 10240 PCTINCREASE 50 ) 
; 



DROP TABLE LASTTMS_ALL CASCADE CONSTRAINTS ; 

CREATE TABLE LASTTMS_ALL ( 
  CODE        VARCHAR2 (12)  NOT NULL, 
  DESCR       VARCHAR2 (32)  NOT NULL, 
  ABBREV      VARCHAR2 (12)  NOT NULL, 
  DTLUPDATE   VARCHAR2 (1), 
  LASTUSER    VARCHAR2 (12), 
  LASTUPDATE  DATE)
   TABLESPACE USERS NOLOGGING 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 10240
   NEXT 10240
   PCTINCREASE 50
   MINEXTENTS 1
   MAXEXTENTS 121
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE UNIQUE INDEX LASTTMS_ALL_IDX ON 
  LASTTMS_ALL(CODE) 
  TABLESPACE USERS PCTFREE 10  STORAGE(INITIAL 10240 NEXT 10240 PCTINCREASE 50 ) 
; 
exit;