--
-- $Id$
--
CREATE TABLE LAWSONDTLEX_DBARAID
(
  SESSIONID   VARCHAR2(8 BYTE),
  DAIDCMPNY   VARCHAR2(4 BYTE),
  DAIDCSTMR   NUMBER(9),
  DAIDTRNSTY  VARCHAR2(1 BYTE),
  DAIDINVC    VARCHAR2(22 BYTE),
  DAIDPRGSQN  NUMBER(9),
  DAIDGLCMPN  NUMBER(4),
  DAIDACCUNT  VARCHAR2(15 BYTE),
  DAIDACCNT   VARCHAR2(9 BYTE),
  DAIDSBACCT  NUMBER(4),
  DAIDORGAMT  NUMBER(18,2),
  DAIDUNITS   NUMBER(15,2),
  DAIDDSCRPT  VARCHAR2(30 BYTE),
  DAIDACTVTY  VARCHAR2(15 BYTE),
  DAIDACCCTG  VARCHAR2(5 BYTE),
  DAIDTXCD    VARCHAR2(10 BYTE),
  DAIDORGTXB  NUMBER(18,2),
  DAIDJBSQNB  NUMBER(10),
  DAIDTXPNT   NUMBER(1),
  DAIDLNTYP   NUMBER(1),
  DAIDWEIGHT  NUMBER(9,3),
  DAIDICNCD   NUMBER(8),
  DAIDSPLQTY  NUMBER(13)
);

exit;