--
-- $Id$
--
DROP TABLE PURGETABLELIST;

CREATE TABLE PURGETABLELIST (
  PARENTTABLE VARCHAR2(30) NOT NULL,
  CHILDTABLE  VARCHAR2(30),
  KEYFIELD1 VARCHAR2(30),
  KEYFIELD2 VARCHAR2(30),
  KEYFIELD3 VARCHAR2(30),
  DESCR VARCHAR2(255),
  lastuser varchar2(12),
  lastupdate date
);


CREATE UNIQUE INDEX ALPS.purgetablelist_parent_idx ON ALPS.PURGETABLELIST (
   PARENTTABLE,CHILDTABLE);

exit;
