--
-- $Id$
--
DROP TABLE PURGERULES;

CREATE TABLE PURGERULES (
  TABLENAME  VARCHAR2(30) NOT NULL,
  RULE1FIELD VARCHAR2(30),
  RULE1OPERATOR VARCHAR2(2),
  RULE1VALUE VARCHAR2(100),
  RULE2FIELD VARCHAR2(30),
  RULE2OPERATOR VARCHAR2(2),
  RULE2VALUE VARCHAR2(100),
  RULE3FIELD VARCHAR2(30),
  RULE3OPERATOR VARCHAR2(2),
  RULE3VALUE VARCHAR2(100),
  BASEDONFIELD  VARCHAR2(30),
  FUNCTIONNAME VARCHAR2(30),
  FACILITYFIELD VARCHAR2(30),
  CUSTIDFIELD VARCHAR2(30),
  DESCR VARCHAR2(255),
  lastuser varchar2(12),
  lastupdate date
);

CREATE UNIQUE INDEX ALPS.PURGERULES ON ALPS.PURGERULES (
   TABLENAME,
   RULE1FIELD,
   RULE1OPERATOR,
   RULE1VALUE,
   RULE2FIELD,
   RULE2OPERATOR,
   RULE2VALUE,
   RULE3FIELD,
   RULE3OPERATOR,
   RULE3VALUE);

exit;
