--
-- $Id$
--
DROP TABLE purgerulesdtl;

CREATE TABLE purgerulesdtl (
  TABLENAME  VARCHAR2(30) NOT NULL,
  RULE1FIELD VARCHAR2(30),
  RULE1OPERATOR VARCHAR2(2),
  RULE1VALUE VARCHAR2(100),
  RULE2FIELD VARCHAR2(30),
  RULE2OPERATOR VARCHAR2(2),
  RULE2VALUE VARCHAR2(100),
  RULE3FIELD VARCHAR2(30),
  RULE3OPERATOR VARCHAR2(2),
  RULE3VALUE VARCHAR2(100),
  CUSTID  VARCHAR2(10),
  FACILITY    VARCHAR2(4),
  DAYSTOKEEP NUMBER,
  lastuser varchar2(12),
  lastupdate date
);

CREATE UNIQUE INDEX ALPS.purgerulesdtl_idx ON ALPS.purgerulesdtl (
   TABLENAME,
   RULE1FIELD,
   RULE1OPERATOR,
   RULE1VALUE,
   RULE2FIELD,
   RULE2OPERATOR,
   RULE2VALUE,
   RULE3FIELD,
   RULE3OPERATOR,
   RULE3VALUE,
   CUSTID,
   FACILITY);

exit;
