--
-- $Id$
--
create table shippingplatehistory (
   lpid              varchar2(15),
   whenoccurred      date,
   item varchar2(50),
   custid            varchar2(10),
   facility          varchar2(3),
   location          varchar2(10),
   status            varchar2(2),
   holdreason        varchar2(2),
   unitofmeasure     varchar2(4),
   quantity          number(7),
   type              varchar2(2),
   fromlpid          varchar2(15),
   serialnumber      varchar2(30),
   lotnumber         varchar2(30),
   parentlpid        varchar2(15),
   useritem1         varchar2(20),
   useritem2         varchar2(20),
   useritem3         varchar2(20),
   lastuser          varchar2(12),
   lastupdate        date,
   invstatus         varchar2(2),
   qtyentered        number(7),
   orderitem varchar2(50),
   uomentered        varchar2(4),
   inventoryclass    varchar2(2),
   loadno            number(7),
   stopno            number(7),
   shipno            number(7),
   orderid           number(7),
   shipid            number(2),
   weight            number(10,4),
   ucc128            varchar2(20),
   taskid            number(15),
   orderlot          varchar2(30),
   pickuom           varchar2(4),
   pickqty           number(7),
   trackingno        varchar2(20),
   cartonseq         number(4),
   totelpid          varchar2(15),
   cartontype        varchar2(4),
   pickedfromloc     varchar2(10),
   shippingcost      number(10,2),
   carriercodeused   varchar2(10),
   satdeliveryused   varchar2(1),
   openfacility      varchar2(3)
);

exit;
