--
-- $Id$
--

DROP TABLE TBL_TRANSACTION_LOGS CASCADE CONSTRAINTS ; 

CREATE TABLE TBL_TRANSACTION_LOGS ( 
  NAMEID      VARCHAR2 (15)  NOT NULL, 
  EVENT       VARCHAR2 (200)  NOT NULL, 
  EVENT_TIME  VARCHAR2 (25)  DEFAULT TO_CHAR(SYSDATE, 'MM-DD-YYYY HH24:MI:SS') NOT NULL ) ; 

exit;