--
-- $Id$
--

DROP TABLE TBL_USER_PREFERENCES CASCADE CONSTRAINTS ; 

CREATE TABLE TBL_USER_PREFERENCES ( 
  NAMEID          VARCHAR2 (12)  NOT NULL, 
  INVENTORY_SORT  VARCHAR2 (200), 
  ORDER_COLUMNS   VARCHAR2 (200), 
  ORDER_SORT      VARCHAR2 (200) ) ; 

exit;