--
-- $Id$
--

DROP TABLE TBL_USER_PERMISSIONS CASCADE CONSTRAINTS ; 

CREATE TABLE TBL_USER_PERMISSIONS ( 
  NAMEID  VARCHAR2 (12)  NOT NULL, 
  ACTION  NUMBER (4)    NOT NULL, 
  DOMAIN  VARCHAR2 (20)  NOT NULL, 
  CONSTRAINT PRIMARY_KEY_1_1
  PRIMARY KEY ( NAMEID, ACTION, DOMAIN ) ) ; 

exit;