--
-- $Id$
--

DROP TABLE TBL_USER_FACILITIES CASCADE CONSTRAINTS ; 

CREATE TABLE TBL_USER_FACILITIES ( 
  NAMEID       VARCHAR2 (12)  NOT NULL, 
  FACILITY_ID  VARCHAR2 (3)  NOT NULL, 
  LAST_USER    VARCHAR2 (12)  NOT NULL, 
  LAST_UPDATE  DATE          DEFAULT sysdate NOT NULL ) ; 

exit;