--
-- $Id$
--

DROP TABLE TBL_COMPANIES CASCADE CONSTRAINTS ;

CREATE TABLE TBL_COMPANIES ( 
  COMPANY_ID       NUMBER        NOT NULL, 
  COMPANY_NAME     VARCHAR2 (100)  NOT NULL, 
  SYNAPSE_PROFILE  VARCHAR2 (20) ) ; 

ALTER TABLE TBL_COMPANIES ADD  CONSTRAINT TBL_COMPANIES_UK
 UNIQUE (COMPANY_NAME) ;
 
 exit;



