--
-- $Id$
--

DROP TABLE TBL_LKUP_PERMISSIONS CASCADE CONSTRAINTS ; 

CREATE TABLE TBL_LKUP_PERMISSIONS ( 
  ACTION_ID        NUMBER (4)    NOT NULL, 
  ACTION_LABEL_ID  NUMBER (4)    NOT NULL, 
  CONSTRAINT ACTION_KEY_1
  PRIMARY KEY ( ACTION_ID ) ) ; 

exit;