--
-- $Id$
--

DROP TABLE TBL_GLOBAL_LABEL_REPOSITORY CASCADE CONSTRAINTS ; 

CREATE TABLE TBL_GLOBAL_LABEL_REPOSITORY ( 
  LABEL_ID             NUMBER (4)    NOT NULL, 
  LABEL_TYPE_ID        NUMBER (4)    DEFAULT 1 NOT NULL, 
  LABEL_DISPLAY_ORDER  NUMBER (2)    DEFAULT 1, 
  EN                   VARCHAR2 (150)  NOT NULL, 
  FR                   VARCHAR2 (150), 
  FR_VERIFIED          NUMBER (1)    DEFAULT 0 NOT NULL, 
  CONSTRAINT CONS_TBL_GLBL_LBL_RPSTRY_1
  PRIMARY KEY ( LABEL_ID ) ) ; 
  
  exit;

