--
-- $Id$
--

DROP TABLE TBL_LKUP_LABEL_TYPES CASCADE CONSTRAINTS ; 

CREATE TABLE TBL_LKUP_LABEL_TYPES ( 
  LABEL_TYPE_ID           NUMBER (4)    NOT NULL, 
  LABEL_TYPE_DESCRIPTION  VARCHAR2 (50)  NOT NULL, 
  REC_ADD_DATE            DATE, 
  SITE_RELATED            NUMBER (4)    DEFAULT 0, 
  CONSTRAINT CONS_TBL_LKUP_LBTYP_1
  PRIMARY KEY ( LABEL_TYPE_ID ) ) ; 


exit;