--
-- $Id$
--

DROP TABLE TBL_USER_PROFILE CASCADE CONSTRAINTS ; 

CREATE TABLE TBL_USER_PROFILE ( 
  NAMEID             VARCHAR2 (12)  NOT NULL, 
  FIRST_NAME         VARCHAR2 (50)  NOT NULL, 
  LAST_NAME          VARCHAR2 (50)  NOT NULL, 
  EMAIL_ADDRESS      VARCHAR2 (50)  NOT NULL, 
  CELLPHONE_AREA     VARCHAR2 (10), 
  CELLPHONE_NUMBER   VARCHAR2 (10), 
  FAX_AREA           VARCHAR2 (10)  NOT NULL, 
  FAX_NUMBER         VARCHAR2 (10)  NOT NULL, 
  PHONE_AREA         VARCHAR2 (10)  NOT NULL, 
  PHONE_NUMBER       VARCHAR2 (10)  NOT NULL, 
  USER_TYPE          NUMBER (10)   DEFAULT 0 NOT NULL, 
  GROUP_ID           NUMBER (10)   NOT NULL, 
  ASSIGNED_CUSTOMER  VARCHAR2 (10)  NOT NULL, 
  DELETE_FLAG        NUMBER (10)   DEFAULT 0 NOT NULL, 
  USER_STATUS        NUMBER (10)   DEFAULT 1 NOT NULL, 
  PASSWORD           VARCHAR2 (25)  NOT NULL, 
  LOGIN_ATTEMPTS     VARCHAR2 (10)  DEFAULT 0 NOT NULL, 
  DOB                VARCHAR2 (25), 
  LANGUAGE           VARCHAR2 (25) ) ; 

ALTER TABLE TBL_USER_PROFILE ADD  CONSTRAINT TBL_USER_PROF_UK
 UNIQUE (NAMEID) ;

exit;

