--
-- $ID: TEMP_INVENTORY_ADJUSTMENT.SQL 1 2011-12-06 12:20:03Z JAMAL $
--
CREATE TABLE TEMP_INVENTORY_ADJUSTMENT ( 
 ADJUSTED              CHAR (1) DEFAULT 'N'
,LPID                  VARCHAR2 (15)
,CUSTID                VARCHAR2 (10)
,ITEM                  VARCHAR2 (20)
,INVENTORYCLASS        VARCHAR2 (2)
,INVSTATUS             VARCHAR2 (2)
,LOTNUMBER             VARCHAR2 (30)
,SERIALNUMBER          VARCHAR2 (30)
,USERITEM1             VARCHAR2 (20)
,USERITEM2             VARCHAR2 (20)
,USERITEM3             VARCHAR2 (20)
,LOCATION              VARCHAR2 (10)
,EXPIRATIONDATE        DATE DEFAULT NULL
,QTY                   NUMBER (7)
,ORIG_CUSTID           VARCHAR2 (10)
,ORIG_ITEM             VARCHAR2 (20)
,ORIG_INVENTORYCLASS   VARCHAR2 (2)
,ORIG_INVSTATUS        VARCHAR2 (2)
,ORIG_LOTNUMBER        VARCHAR2 (30)
,ORIG_SERIALNUMBER     VARCHAR2 (30)
,ORIG_USERITEM1        VARCHAR2 (20)
,ORIG_USERITEM2        VARCHAR2 (20)
,ORIG_USERITEM3        VARCHAR2 (20)
,ORIG_LOCATION         VARCHAR2 (10)
,ORIG_EXPIRATIONDATE   DATE DEFAULT NULL
,ORIG_QTY              NUMBER (7)
,FACILITY              VARCHAR2 (3)
,ADJREASON             VARCHAR2 (2)
,USERID                VARCHAR2 (12)
,TASKTYPE              VARCHAR2 (2)
,WEIGHT                NUMBER (17,8)
,ORIG_WEIGHT           NUMBER (17,8)
,MFGDATE               DATE DEFAULT NULL
,ORIG_MFGDATE          DATE DEFAULT NULL
,ANVDATE               DATE DEFAULT NULL
,ORIG_ANVDATE          DATE DEFAULT NULL
,CUSTREFERENCE         VARCHAR2 (32) DEFAULT NULL
,TASKS_OK              VARCHAR2 (10) DEFAULT NULL
,SUPPRESS_EDI_YN       VARCHAR2 (1) DEFAULT 'N'
,ERRMSG                VARCHAR2 (4000) DEFAULT NULL);