--
-- $Id$
--

DROP TABLE TMSFACILITYGROUP CASCADE CONSTRAINTS ; 

CREATE TABLE TMSFACILITYGROUP ( 
  CODE        VARCHAR2 (12)  NOT NULL, 
  DESCR       VARCHAR2 (32)  NOT NULL, 
  ABBREV      VARCHAR2 (12)  NOT NULL, 
  DTLUPDATE   VARCHAR2 (1), 
  LASTUSER    VARCHAR2 (12), 
  LASTUPDATE  DATE ) ; 


CREATE UNIQUE INDEX TMSFACILITYGROUP_IDX ON 
  TMSFACILITYGROUP(CODE) 
; 



insert into tabledefs (tableid,hdrupdate,dtlupdate,codemask)
values('TMSFacilityGroup','Y','Y','>Aaaa;0;_');


exit;