--
-- $Id$
--

DROP TABLE TMSSERVICEROUTE CASCADE CONSTRAINTS ; 

CREATE TABLE TMSSERVICEROUTE ( 
  FACILITYGROUP     VARCHAR2 (4)  NOT NULL, 
  AREA         VARCHAR2 (5)  NOT NULL, 
  SERVICEDAYS  NUMBER	NOT NULL, 
  ROUTE        VARCHAR2 (5)  NOT NULL, 
  DEFAULTCARRIER  VARCHAR2 (4) NOT NULL,
  LASTUSER     VARCHAR2 (12), 
  LASTUPDATE   DATE);


CREATE UNIQUE INDEX FACILITYAREA ON 
  TMSSERVICEROUTE(FACILITYGROUP, AREA); 
  
exit;


