--
-- $Id$
--

DROP TABLE TMSSERVICEZIP CASCADE CONSTRAINTS ; 

CREATE TABLE TMSSERVICEZIP ( 
  BEGZIP            CHAR (5)      NOT NULL, 
  ENDZIP            CHAR (5)      NOT NULL, 
  AREA              VARCHAR2 (5)  NOT NULL,  
  LASTUSER          VARCHAR2 (12), 
  LASTUPDATE        DATE);


CREATE UNIQUE INDEX BEGZIPENDZIP ON 
  TMSSERVICEZIP(BEGZIP, ENDZIP);
  
 
 exit;

