--drop table weber_tms_export;

create table weber_tms_export
(
  orderid                       number(9),
  shipid                        number(2),
  orderid_shipid                varchar2(12),
  shipment_owner                varchar2(10),
  disposition                   varchar2(6),
  mbl_pri_ref                   number(7),
  mbl_pri_ref_type              varchar2(11),
  mbl_addl_ref                  varchar2(17),
  mbl_addl_ref_type             varchar2(8),
  col_not_used_1                varchar2(1),
  po_pri_ref                    varchar2(20),
  po_pri_ref_type               varchar2(9),
  po_date                       varchar2(16),
  shipment_type                 varchar2(1),
  shipment_pri_ref              number(9),
  shipment_pri_ref_type         varchar2(3),
  ship_status                   varchar2(8),
  ship_start_date               varchar2(16),
  ship_end_date                 varchar2(16),
  delivery_start_date           varchar2(16),
  delivery_end_date             varchar2(16),
  origin_alias                  varchar2(10),
  origin_name                   varchar2(40),
  origin_address1               varchar2(40),
  origin_address2               varchar2(40),
  origin_city                   varchar2(30),
  origin_state                  varchar2(5),
  origin_postalcode             varchar2(12),
  origin_country                varchar2(3),
  dest_alias                    varchar2(10),
  dest_name                     varchar2(40),
  dest_address1                 varchar2(40),
  dest_address2                 varchar2(40),
  dest_city                     varchar2(30),
  dest_state                    varchar2(5),
  dest_postalcode               varchar2(12),
  dest_country                  varchar2(3),
  bill_alias                    varchar2(10),
  bill_name                     varchar2(40),
  bill_address1                 varchar2(40),
  bill_address2                 varchar2(40),
  bill_city                     varchar2(30),
  bill_state                    varchar2(5),
  bill_postalcode               varchar2(12),
  bill_country                  varchar2(3),
  payment_method                varchar2(11),
  third_party                   varchar2(1),
  scac                          varchar2(10),
  col_not_used_2                varchar2(1),
  col_not_used_3                varchar2(1),
  special_instructions          varchar2(800),
  col_not_used_4                varchar2(1),
  item_id                       varchar2(20),
  item_description              varchar2(255),
  item_commodity                varchar2(12),
  item_freightclass             number(4,1),
  item_quantity                 number,
  item_quantity_uom             varchar2(4),
  item_weight                   number,
  col_not_used_5                varchar2(1),
  col_not_used_6                varchar2(1),
  item_hazmat                   varchar2(5),
  order_item_quantity           number,
  col_not_used_7                varchar2(1),
  col_not_used_8                varchar2(1),
  col_not_used_9                varchar2(1),
  col_not_used_10               varchar2(1),
  item_quantity_top_level       number,
  gl_code                       varchar2(1),
  dest_phone                    varchar2(25),
  buyer_code                    varchar2(1),
  col_actual_quantity           varchar2(1),
  col_actual_quantity_uom       varchar2(1),
  col_shipment_addl_ref_type_1  varchar2(8),
  col_shipment_addl_ref_val_1   varchar2(8),
  col_shipment_addl_ref_type_2  varchar2(25),
  col_shipment_addl_ref_val_2   varchar2(20),
  col_shipment_service_codes    varchar2(1),
  col_item_cube                 varchar2(1),
  col_item_temp_min             varchar2(1),
  col_item_temp_max             varchar2(1),
  col_item_temp_units           varchar2(1),
  col_item_stcc_code            varchar2(1),
  col_item_stackability         varchar2(1),
  col_not_used_11               varchar2(1),
  col_not_used_12               varchar2(1)
);

--
-- $Id$
--
create index weber_tms_export_ordidx
   on weber_tms_export(orderid, shipid);

exit;

