--
-- $Id$
--
drop table worldshipdtl;
create table worldshipdtl
(ORDERID NUMBER(7)
,SHIPID NUMBER(2)
,CARTONID VARCHAR2(15) not null
,ESTWEIGHT NUMBER(13,4)
,ACTWEIGHT NUMBER(13,4)
,TRACKID VARCHAR2(20)
,STATUS VARCHAR2(10)
,SHIPDATETIME VARCHAR2(14)
,CARRIERUSED VARCHAR2(10)
,REASON VARCHAR2(100)
,COST NUMBER(10,2)
,TERMID VARCHAR2(4)
,SATDELIVERYUSED VARCHAR2(1)
,PACKLISTSHIPDATETIME VARCHAR2(14)
);

