create or replace view f_order_detail as
select
  sys_context('USERENV','SERVICE_NAME') DB_Service_Name,
  a.lastupdate Modification_Time,
  orderid,
  shipid,
  custid as customer,
  item,
  lotnumber as lot_number,
  linestatus as status,
  decode(linestatus, 'A', 'Active', 'X', 'Cancelled', '') as status_description,
  priority,
  b.abbrev as priority_desc,
  invstatusind as inv_status_indicator,
  invstatus as inv_status,
  invclassind as inv_class_indicator,
  inventoryclass as inv_class,
  uom as unit_of_measure,
  nvl(qtyentered, 0) as qty_entered,
  itementered as item_entered,
  uomentered as unit_of_measure_entered,
  nvl(qtyorder, 0) as qty_order,
  nvl(weightorder, 0) as weight_order,
  nvl(qtycommit, 0) as qty_commit,
  nvl(weightcommit, 0) as weight_commit,
  nvl(qtypick, 0) as qty_pick,
  nvl(weightpick, 0) as weight_pick,
  nvl(qty2pack, 0) as qty_to_pack,
  nvl(weight2pack, 0) as weight_to_pack,
  nvl(qty2sort, 0) as qty_to_sort,
  nvl(weight2sort, 0) as weight_to_sort,
  nvl(qty2check, 0) as qty_to_check,
  nvl(weight2check, 0) as weight_to_check,
  nvl(qtyship, 0) as qty_ship,
  nvl(weightship, 0) as weight_ship,
  nvl(qtyrcvd, 0) as qty_received,
  nvl(weightrcvd, 0) as weight_received,
  nvl(qtyrcvdgood, 0) as qty_received_good,
  nvl(weightrcvdgood, 0) as weight_received_good,
  nvl(qtyrcvddmgd, 0) as qty_received_damaged,
  nvl(weightrcvddmgd, 0) as weight_received_damaged,
  dtlpassthrudate01 as pt_date_01,
  dtlpassthrudate02 as pt_date_02,
  dtlpassthrudate03 as pt_date_03,
  dtlpassthrudate04 as pt_date_04,
  dtlpassthrudoll01 as pt_dollar_01,
  dtlpassthrudoll02 as pt_dollar_02,
  dtlpassthruchar01 as pt_character_01,
  dtlpassthruchar02 as pt_character_02,
  dtlpassthruchar03 as pt_character_03,
  dtlpassthruchar04 as pt_character_04,
  dtlpassthruchar05 as pt_character_05,
  dtlpassthruchar06 as pt_character_06,
  dtlpassthruchar07 as pt_character_07,
  dtlpassthruchar08 as pt_character_08,
  dtlpassthruchar09 as pt_character_09,
  dtlpassthruchar10 as pt_character_10,
  dtlpassthruchar11 as pt_character_11,
  dtlpassthruchar12 as pt_character_12,
  dtlpassthruchar13 as pt_character_13,
  dtlpassthruchar14 as pt_character_14,
  dtlpassthruchar15 as pt_character_15,
  dtlpassthruchar16 as pt_character_16,
  dtlpassthruchar17 as pt_character_17,
  dtlpassthruchar18 as pt_character_18,
  dtlpassthruchar19 as pt_character_19,
  dtlpassthruchar20 as pt_character_20,
  dtlpassthruchar21 as pt_character_21,
  dtlpassthruchar22 as pt_character_22,
  dtlpassthruchar23 as pt_character_23,
  dtlpassthruchar24 as pt_character_24,
  dtlpassthruchar25 as pt_character_25,
  dtlpassthruchar26 as pt_character_26,
  dtlpassthruchar27 as pt_character_27,
  dtlpassthruchar28 as pt_character_28,
  dtlpassthruchar29 as pt_character_29,
  dtlpassthruchar30 as pt_character_30,
  dtlpassthruchar31 as pt_character_31,
  dtlpassthruchar32 as pt_character_32,
  dtlpassthruchar33 as pt_character_33,
  dtlpassthruchar34 as pt_character_34,
  dtlpassthruchar35 as pt_character_35,
  dtlpassthruchar36 as pt_character_36,
  dtlpassthruchar37 as pt_character_37,
  dtlpassthruchar38 as pt_character_38,
  dtlpassthruchar39 as pt_character_39,
  dtlpassthruchar40 as pt_character_40, 
  dtlpassthrunum01 as pt_number_01,
  dtlpassthrunum02 as pt_number_02,
  dtlpassthrunum03 as pt_number_03,
  dtlpassthrunum04 as pt_number_04,
  dtlpassthrunum05 as pt_number_05,
  dtlpassthrunum06 as pt_number_06,
  dtlpassthrunum07 as pt_number_07,
  dtlpassthrunum08 as pt_number_08,
  dtlpassthrunum09 as pt_number_09,
  dtlpassthrunum10 as pt_number_10,
  dtlpassthrunum11 as pt_number_11,
  dtlpassthrunum12 as pt_number_12,
  dtlpassthrunum13 as pt_number_13,
  dtlpassthrunum14 as pt_number_14,
  dtlpassthrunum15 as pt_number_15,
  dtlpassthrunum16 as pt_number_16,
  dtlpassthrunum17 as pt_number_17,
  dtlpassthrunum18 as pt_number_18,
  dtlpassthrunum19 as pt_number_19,
  dtlpassthrunum20 as pt_number_20,
  a.statusupdate status_update_time,
  a.statususer status_update_user,
  a.lastupdate last_update_time,
  a.lastuser last_update_user
from alps.orderdtl a, alps.orderpriority b
where a.priority = b.code(+);
  