alter table allocrulesdtl modify facility not null;
alter table allocrulesdtl modify priority not null;
alter table allocrulesdtl modify facility not null;
alter table allocruleshdr modify facility not null;
alter table applocks modify lockid not null;
alter table carrierstageloc modify shiptype not null;
alter table caselabels modify barcode not null;
alter table conversions modify fromuom not null;
alter table conversions modify touom not null;
alter table custconsigneenotice modify shipto not null;
delete from custitemcount
 where uom is null;
alter table custitemcount modify uom not null;
alter table custitemuom modify sequence not null;
alter table custlastrenewal modify facility not null;
alter table custlastrenewal modify custid not null;
alter table customcode modify businessevent not null;
delete from custrenewal
 where custid is null
   or renewal is null;
alter table custrenewal modify custid not null;
alter table custrenewal modify renewal not null;
alter table loads modify loadno not null;
alter table loadstop modify loadno not null;
delete from loadstop
 where stopno is null;
alter table loadstop modify stopno not null;
delete from loadstopship where loadno is null;
delete from loadstopship where stopno is null;
delete from loadstopship where shipno is null;
alter table loadstopship modify loadno not null;
alter table loadstopship modify stopno not null;
alter table loadstopship modify shipno not null;
alter table mass_manifest_ctn modify ctnid not null;
alter table orderhdrbolcomments modify orderid not null;
alter table orderhdrbolcomments modify shipid not null;
alter table p1pkcaselabels modify orderid not null;
alter table p1pkcaselabels modify shipid not null;
alter table p1pkcaselabels modify custid not null;
alter table p1pkcaselabels modify item not null;
alter table printer modify facility not null;
alter table section modify facility not null;
alter table shipdays modify facility not null;
alter table shipdays modify postalkey not null;
alter table splitshipmentdtl modify lotnumber not null;
alter table spoolerqueues modify prtqueue not null;
alter table systemdefaults modify defaultid not null;
alter table tempcustitemout modify nameid not null;
alter table tempcustitemout modify custid not null;
alter table tempcustitemout modify item not null;
alter table tempcustitemout modify lotnumber not null;
alter table ursa modify zipcode not null;
alter table ursa modify state not null;
alter table ursa modify cityprefixes null;
alter table userforms modify formid not null;
alter table usergrids modify nameid not null;
alter table usergrids modify formid not null;
alter table usergrids modify gridid not null;
alter table usercxgrids modify formid not null;
alter table usercxgrids modify gridid not null;
alter table zone modify facility not null;
alter table custworkorder modify kitted_class not null;
