--
-- $Id$
--
SELECT 
    "BOLRPT"."OH_ORDERID", "BOLRPT"."OH_SHIPID", "BOLRPT"."OH_ENTRYDATE", "BOLRPT"."OH_APPTDATE", "BOLRPT"."OH_SHIPDATE", "BOLRPT"."OH_PO", "BOLRPT"."OH_ARRIVALDATE", "BOLRPT"."OH_LOADNO", "BOLRPT"."OH_REFERENCE", "BOLRPT"."CN_NAME", "BOLRPT"."CN_ADDR1", "BOLRPT"."CN_ADDR2", "BOLRPT"."CN_CITY", "BOLRPT"."CN_STATE", "BOLRPT"."CN_POSTALCODE", "BOLRPT"."CN_COUNTRYCODE", "BOLRPT"."CR_NAME", "BOLRPT"."CR_ADDR1", "BOLRPT"."CR_ADDR2", "BOLRPT"."CR_CITY", "BOLRPT"."CR_STATE", "BOLRPT"."CR_POSTALCODE", "BOLRPT"."CR_COUNTRYCODE", "BOLRPT"."CAR_NAME", "BOLRPT"."CR_SCAC", "BOLRPT"."CU_NAME", "BOLRPT"."CU_ADDR1", "BOLRPT"."CU_ADDR2", "BOLRPT"."CU_CITY", "BOLRPT"."CU_STATE", "BOLRPT"."CU_POSTALCODE", "BOLRPT"."CU_COUNTRYCODE", "BOLRPT"."OD_ITEM", "BOLRPT"."OD_QTYSHIP", "BOLRPT"."OD_WEIGHTSHIP", "BOLRPT"."OD_LOTNUMBER", "BOLRPT"."OD_LOTNUMBER_NULL", "BOLRPT"."FAC_NAME", "BOLRPT"."FAC_ADDR1", "BOLRPT"."FAC_ADDR2", "BOLRPT"."FAC_CITY", "BOLRPT"."FAC_STATE", "BOLRPT"."FAC_POSTALCODE", "BOLRPT"."FAC_COUNTRYCODE", "BOLRPT"."LD_TRAILER", "BOLRPT"."LD_SEAL", "BOLRPT"."LD_PRONO", "BOLRPT"."CI_DESCR", "BOLRPT"."CI_HAZARDOUS", "BOLRPT"."ST_ABBREV", "BOLRPT"."STRM_ABBREV", "BOLITMCMTVIEW"."ODC_ITEM", "BOLITMCMTVIEW"."CI_ITEM", "BOLITMCMTVIEW"."CID_ITEM"
FROM
    "ALPS"."BOLRPT" "BOLRPT",
    "ALPS"."BOLITMCMTVIEW" "BOLITMCMTVIEW"
WHERE
    "BOLRPT"."OH_ORDERID" = "BOLITMCMTVIEW"."ORDERID"(+) AND
    "BOLRPT"."OH_SHIPID" = "BOLITMCMTVIEW"."SHIPID"(+) AND
    "BOLRPT"."OD_ITEM" = "BOLITMCMTVIEW"."ITEM"(+) AND
    "BOLRPT"."OH_LOADNO" = 123
ORDER BY
    "BOLRPT"."OH_ORDERID" ASC,
    "BOLRPT"."OH_SHIPID" ASC;
exit;