--
-- $Id$
--
set show off
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
3, 1, NULL, 0, 'HDR', ',', 'Header', 'ORDERCONFIRMVIEW', 0, 'UPDATE_CONFIRM_DATE'
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
2, 1, NULL, 0, 'ERR_REC', NULL, 'Error Record', 'ORDERREJECTVIEW', 0, 'UPDATE_CONFIRM_DATE'
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
5, 1, NULL, 0, NULL, NULL, 'Ship Header', 'SHIP_NOTIFY_HDR', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
5, 2, 1, 0, NULL, NULL, 'Container', 'SHIP_NOTIFY_CONTAINER', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
17, 2, 1, 0, NULL, NULL, 'Container', 'SHIP_NOTIFY_CONTAINER', 0, NULL, 'N', 'TRACKINGNO');
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
17, 3, 1, 0, NULL, NULL, 'Contents', 'SHIP_NOTIFY_CONTENTS', 0, NULL, 'N', 'LINENUMBERSTR');
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
6, 12, NULL, 0, 'OEOH', NULL, 'Order Header Record', 'IMPORT_ORDER_HEADER', 4, NULL
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
6, 13, 12, 0, 'OENO', NULL, 'Order Header Notes Record', 'IMPORT_ORDER_SEQ_COMMENT'
, 4, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
6, 14, 12, 0, 'OEOL', NULL, 'Order Line Record', 'IMPORT_ORDER_LINE', 4, NULL, 'N'
, NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
7, 1, NULL, 0, 'ERR_REC', NULL, 'Error Record', 'ORDERREJECTVIEW', 0, 'UPDATE_CONFIRM_DATE'
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
10, 1, NULL, 0, 'HDR', ',', 'Header', 'ORDERCONFIRMVIEW', 0, 'UPDATE_CONFIRM_DATE'
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
14, 1, NULL, 0, NULL, NULL, 'Header Record', 'STOCKSTAT_FILE_HDR', 0, NULL, 'H', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
14, 2, NULL, 0, NULL, NULL, 'Sub Header', 'STOCKSTAT_ITEM_HDR', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
14, 3, 2, 0, NULL, NULL, 'Stock Status Line Record', 'STOCKSTAT_ITEM_DTL', 0, NULL
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
14, 4, 2, 0, NULL, NULL, 'Sub Trailer Record', 'STOCKSTAT_ITEM_TRL', 0, NULL, 'N'
, NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
14, 5, NULL, 0, NULL, NULL, 'File Trailer', 'STOCKSTAT_FILE_TRL', 0, NULL, 'T', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
15, 1, NULL, 1, NULL, '^', 'Header RecordNew Line', 'SHIP_SUMMARY_HDR', 0, NULL, 'N'
, NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
15, 2, 1, 1, NULL, '^', 'Report Detail', 'SHIP_SUMMARY_DTL', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
15, 3, 1, 1, NULL, '^', 'Total Record', 'SHIP_SUMMARY_TOT', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
15, 4, NULL, 1, NULL, '^', 'Grand Total', 'SHIP_SUMMARY_GRAND_TOT', 0, NULL, 'T', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
16, 1, NULL, 0, NULL, NULL, 'Notification Header', 'RCPTNOTE_HDR', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
16, 2, 1, 0, NULL, NULL, 'Receipt Detail', 'RCPTNOTE_DTL', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
17, 1, NULL, 0, NULL, NULL, 'Ship Header', 'SHIP_NOTIFY_HDR', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
18, 1, NULL, 1, 'LOC', ',', 'header', 'IMPORT_LOCATION', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
5, 3, 1, 0, NULL, NULL, 'Contents', 'SHIP_NOTIFY_CONTENTS', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
8, 1, NULL, 0, NULL, NULL, 'Header Record', 'STOCKSTAT_FILE_HDR', 0, NULL, 'H', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
8, 2, NULL, 0, NULL, NULL, 'Sub Header', 'STOCKSTAT_ITEM_HDR', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
8, 3, 2, 0, NULL, NULL, 'Stock Status Line Record', 'STOCKSTAT_ITEM_DTL', 0, NULL
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
1, 12, NULL, 0, 'OEOH', NULL, 'Order Header Record', 'IMPORT_ORDER_HEADER', 4, NULL
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
1, 13, 12, 0, 'OENO', NULL, 'Order Header Notes Record', 'IMPORT_ORDER_SEQ_COMMENT'
, 4, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
1, 14, 12, 0, 'OEOL', NULL, 'Order Line Record', 'IMPORT_ORDER_LINE', 4, NULL, 'N'
, NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
19, 1, NULL, 0, '01', NULL, 'Receiver Record', 'IRISRECV_DTL', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
20, 1, NULL, 0, '02', NULL, 'Shipment Record Type', 'IRISSHIP_DTL', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
4, 12, NULL, 0, 'OEOH', NULL, 'Order Header Record', 'IMPORT_ORDER_HEADER', 4, NULL
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
4, 13, 12, 0, 'OENO', NULL, 'Order Header Notes Record', 'IMPORT_ORDER_SEQ_COMMENT'
, 4, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
4, 14, 12, 0, 'OEOL', NULL, 'Order Line Record', 'IMPORT_ORDER_LINE', 4, NULL, 'N'
, NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
11, 1, NULL, 0, 'ERR_REC', NULL, 'Error Record', 'ORDERREJECTVIEW', 0, 'UPDATE_CONFIRM_DATE'
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
12, 1, NULL, 0, NULL, NULL, 'Ship Header', 'SHIP_NOTIFY_HDR', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
12, 2, 1, 0, NULL, NULL, 'Container', 'SHIP_NOTIFY_CONTAINER', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
12, 3, 1, 0, NULL, NULL, 'Contents', 'SHIP_NOTIFY_CONTENTS', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
13, 1, NULL, 1, NULL, '^', 'Header RecordNew Line', 'SHIPSUM_HDR', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
13, 2, 1, 1, NULL, '^', 'Report Detail', 'SHIPSUM_DTL', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
13, 3, 1, 1, NULL, '^', 'Total Record', 'SHIPSUM_TOT', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
13, 4, NULL, 1, NULL, '^', 'Grand Total', 'SHIPSUM_GRAND_TOT', 0, NULL, 'T', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
8, 4, 2, 0, NULL, NULL, 'Sub Trailer Record', 'STOCKSTAT_ITEM_TRL', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
8, 5, NULL, 0, NULL, NULL, 'File Trailer', 'STOCKSTAT_FILE_TRL', 0, NULL, 'T', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
26, 1, NULL, 1, NULL, '~', 'Return Receipt Record', 'RTRNONLY_DTL', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
21, 1, NULL, 0, NULL, NULL, 'Anscillary Record', 'IRISANCL_DTL', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
24, 1, NULL, 1, 'PRE', '~', 'Pre-Alert Record', 'IMPORT_ASN_ITEM', NULL, NULL, 'N'
, NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
25, 1, NULL, 1, NULL, '~', 'OEM Receipt Record', 'RCPTONLY_DTL', 0, NULL, 'H', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
9, 1, NULL, 1, 'LOC', ',', 'header', 'IMPORT_LOCATION', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
27, 1, NULL, 1, 'CAR', '|', 'Header', 'IMPORT_CARRIER', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
28, 1, NULL, 1, 'POS', '|', 'Postal', 'IMPORT_POSTALCODES', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
29, 1, NULL, 1, 'CON', '|', 'Header', 'IMPORT_CONSIGNEENAME', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
30, 1, NULL, 0, 'POS', NULL, 'Record Type', NULL, 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
30, 2, NULL, 0, NULL, NULL, 'New Line', NULL, 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
31, 1, NULL, 1, 'NMF', '|', 'NMFC', 'IMPORT_NMFC', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
32, 1, NULL, 1, 'INM', '|', 'Item', 'IMPORT_ITEMNAME', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
33, 1, NULL, 1, 'IBU', '|', 'Base UOM', 'IMPORT_ITEMBASEUOM', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
34, 1, NULL, 1, 'IR1', '|', 'Item Rec 1', 'IMPORT_ITEMRECOPTIONS1', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
35, 1, NULL, 1, 'IR2', '|', 'Item Rec 2', 'IMPORT_ITEMRECOPTIONS2', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
36, 1, NULL, 1, 'IS1', '|', 'Item Ship 1', 'IMPORT_SHIPPINGOPTIONS1', 0, NULL, 'N'
, NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
37, 1, NULL, 1, 'IS2', '|', 'Item Ship 2', 'IMPORT_ITEMSHIPPINGOPTIONS2', 0, NULL
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
38, 1, NULL, 1, 'ISP', '|', 'Item Specs', 'IMPORT_ITEMSPECS', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
39, 1, NULL, 1, 'IST', '|', 'Item Storage', 'IMPORT_ITEMSTORAGE', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
40, 1, NULL, 1, 'IUS', '|', 'UOM Sequences', 'IMPORT_ITEMUOMSEQUENCES', 0, NULL, 'N'
, NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
41, 1, NULL, 1, 'IVA', '|', 'Item Validation', 'IMPORT_ITEMVALIDATION', 0, NULL, 'N'
, NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
42, 1, NULL, 1, 'PFT', '|', 'Pick Front', 'IMPORT_PICKFRONTS', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
43, 1, NULL, 1, 'LOC', ',', 'Location', 'IMPORT_LOCATION', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
44, 1, NULL, 1, 'IAL', '|', 'Item Aliases', 'IMPORT_ORDER_HEADER', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
45, 1, NULL, 1, 'CAR', '|', 'Carrier', 'IMPORT_CARRIER', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
46, 1, NULL, 0, 'OEOH', NULL, 'Order Header Record', 'IMPORT_ORDER_HEADER', 0, NULL
, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
46, 2, NULL, 0, NULL, NULL, 'New Line', NULL, 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
22, 1, NULL, 1, 'CCN', '|', 'Header', 'IMPORT_CUSTCONSIGNEE', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
23, 1, NULL, 1, 'CBL', '|', 'Header', 'IMPORT_CUSTITEMBOLCOMMENTS', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
23, 2, NULL, 0, NULL, NULL, 'New Line', NULL, 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
47, 1, NULL, 1, 'CON', '|', 'New Line', 'IMPORT_COUNTRYCODES', 0, NULL, 'N', NULL);
INSERT INTO IMPEXP_LINES ( DEFINC, LINEINC, PARENT, TYPE, IDENTIFIER, DELIMITER, LINEALIAS,
PROCNAME, DELIMITEROFFSET, AFTERPROCESSPROCNAME, HEADERTRAILERFLAG,
ORDERBYCOLUMNS ) VALUES (
48, 1, NULL, 1, 'CIN', '|', 'Header', 'IMPORT_CUSTITEMNMFC', 0, NULL, 'N', NULL);
commit;

