--
-- $Id$
--
set show off
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
7, 'Error Notification', 'alsOhlTrain', 'N:\OHLTRAIN\export\Error Notification\outgoing\A$SEQ.rdy'
, 'YYYYMMDD', 'E', 0, 0, 1012, NULL, NULL, NULL, NULL, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
10, 'Order Confirmation', 'alsOhlTrain', 'N:\OHLTRAIN\export\Order Confirmation\outgoing\A$SEQ.RDY'
, 'YYYYMMDD', 'E', 0, 0, 1012, NULL, NULL, NULL, NULL, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
14, 'Stock Status', 'alsOhlTrain', 'N:\OHLTRAIN\export\$ID\$DIRPARMStock Status\outgoing\A$SEQ.RDY'
, 'YYYYMMDD', 'E', 6, 2, 1012, 'END_STOCKSTAT', 'BEGIN_STOCKSTAT', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$BEGDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMM', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
15, 'Shipping Summary', 'alsOhlTrain', 'N:\OHLTRAIN\export\$ID\Shipping Summary\outgoing\SU$YESMMDD$SUFFIX'
, 'YYYYMMDD', 'E', 0, 0, 69, 'END_SHIP_SUM', 'BEGIN_SHIP_SUM', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$LASTDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMM', 'Y', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
16, 'Receipt Notification', 'alsOhlTrain', 'N:\OHLTRAIN\export\$ID\Receipt Notification\outgoing\A$SEQ'
, 'YYYYMMDD', 'E', 3, 6, 1012, 'END_RCPTNOTE', 'BEGIN_RCPTNOTE', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$LASTDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
17, 'Ship Notification', 'alsOhlTrain', 'N:\OHLTRAIN\export\$ID\Ship Notification\outgoing\A$SEQ'
, 'YYYYMMDD', 'E', 6, 2, 1012, NULL, NULL, NULL, NULL, 'HHMM', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
18, 'location test', 'alssynapseTraining', 'C:\Documents and Settings\coechsel\My Documents\LogTech\Weber\Training\Testoverride000713.csv'
, NULL, 'I', 0, 0, 9, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
6, 'DTV Demand Order', 'alsOhlTrain', 'N:\OHLTRAIN\DTVIMPORT\INCOMING\rec.*', 'YYYYMMDD'
, 'I', 2, 4, 1012, 'END_OF_IMPORT', NULL, 'IN_CUSTID=17131
IN_IMPORTFILEID=$FILENAME
IN_USERID=SYSTEM
OUT_ERRORNO=
OUT_MSG=
'
, NULL, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
2, 'DTV Error Notification', 'alsOhlTrain', 'N:\OHLTRAIN\dtvexport\Error Notification\outgoing\A$SEQ.rdy'
, 'YYYYMMDD', 'E', 0, 0, 1012, NULL, NULL, NULL, NULL, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
3, 'DTV Order Confirmation', 'alsOhlTrain', 'N:\OHLTRAIN\dtvexport\Order Confirmation\outgoing\A$SEQ.RDY'
, 'YYYYMMDD', 'E', 0, 0, 1012, NULL, NULL, NULL, NULL, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
5, 'DTV Ship Notification', 'alsOhlTrain', 'N:\OHLTRAIN\dtvexport\Ship Notification\outgoing\A$SEQ'
, 'YYYYMMDD', 'E', 6, 2, 1012, NULL, NULL, NULL, NULL, 'HHMM', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
1, 'HP DEMAND ORDER', 'alsOhlTrain', 'N:\OHLTRAIN\IMPORT\INCOMING\rec.*', 'YYYYMMDD'
, 'I', 2, 4, 1012, 'END_OF_IMPORT', NULL, 'IN_CUSTID=HP
IN_IMPORTFILEID=$FILENAME
IN_USERID=SYSTEM
OUT_ERRORNO=
OUT_MSG=
'
, NULL, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
19, 'IRIS Billing Receiver Record', 'alsohltrain', 'N:\Ohltrain\IRIS Billing\Receiver\ready\ROH$MMDD'
, 'YYYYMMDD', 'E', 0, 0, 799, 'END_IRISRECV', 'BEGIN_IRISRECV', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$LASTDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMM', 'Y', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
21, 'IRIS Billing Ancillary Record', 'alsohltrain', 'N:\Ohltrain\IRIS Billing\Ancillary\ready\AOH$MMDD'
, 'YYYYMMDD', 'E', 0, 0, 799, 'END_IRISANCL', 'BEGIN_IRISANCL', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$LASTDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMM', 'Y', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
11, 'Pegasus Error Notification', 'alsOhlTrain', 'N:\OHLTRAIN\pegexport\Error Notification\outgoing\A$SEQ.rdy'
, 'YYYYMMDD', 'E', 0, 0, 1012, NULL, NULL, NULL, NULL, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
12, 'Pegasus Ship Notification', 'alsOhlTrain', 'N:\OHLTRAIN\pegexport\Ship Notification\outgoing\A$SEQ'
, 'YYYYMMDD', 'E', 6, 2, 1012, NULL, NULL, NULL, NULL, 'HHMM', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
13, 'RETURNS Shipping Summary', 'alsOhlTrain', 'N:\OHLTRAIN\export\$ID\Shipping Summary\outgoing\SU$YESMMDD$SUFFIX'
, 'YYYYMMDD', 'E', 0, 0, 69, 'END_SHIPSUM', 'BEGIN_SHIPSUM', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$LASTDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMM', 'Y', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
8, 'DTV Stock Status', 'alsOhlTrain', 'N:\OHLTRAIN\DTVexport\Stock Status\outgoing\A$SEQ.RDY'
, 'YYYYMMDD', 'E', 6, 2, 1012, 'END_STOCKSTAT', 'BEGIN_STOCKSTAT', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$BEGDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMM', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
26, 'DTV Returns Receipt', 'alsohltrain', 'N:\OHLTRAIN\dtvexport\return notification\outgoing\A$SEQ.'
, 'YYYYMMDD', 'E', 0, 0, 1012, 'END_RTRNONLY', 'BEGIN_RTRNONLY', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$LASTDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMMSS', 'Y', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
20, 'IRIS Billing Shipment Record', 'alsohltrain', 'N:\Ohltrain\IRIS Billing\Shipment\ready\SOH$MMDD.'
, 'YYYYMMDD', 'E', 0, 0, 799, 'END_IRISSHIP', 'BEGIN_IRISSHIP', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$LASTDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMM', 'Y', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
25, 'DTV OEM Receipt', 'alsohltrain', 'N:\OHLTRAIN\dtvexport\receipt notification\outgoing\A$SEQ.'
, 'YYYYMMDD', 'E', 0, 0, 1012, 'END_RCPTONLY', 'BEGIN_RCPTONLY', 'IN_CUSTID=$CUSTPARM
IN_VIEWSUFFIX=$VIEWNUM
OUT_ERRORNO=
OUT_MSG=
'
, 'IN_CUSTID=$CUSTPARM
IN_BEGDATESTR=$LASTDATE
IN_ENDDATESTR=$BEGDATE
OUT_ERRORNO=
OUT_MSG=
'
, 'HHMMSS', 'Y', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
24, 'DTV Pre-Alert', 'alsohltrain', 'N:\OHLTRAIN\DTVIMPORT\PREALERTS\*.*', 'YYYYMMDD'
, 'I', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
4, 'Pegasus Demand Order', 'alsOhlTrain', 'N:\OHLTRAIN\PEGIMPORT\INCOMING\*.*', 'YYYYMMDD'
, 'I', 2, 4, 1012, 'END_OF_IMPORT', NULL, 'IN_CUSTID=PEG TEST
IN_IMPORTFILEID=$FILENAME
IN_USERID=SYSTEM
OUT_ERRORNO=
OUT_MSG=
'
, NULL, 'HHMMSS', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
9, 'Weber Location Import', 'alssynapseTraining', 'C:\alsSynapseTraining\Import\incoming\iMPORT LOCATION-WEBER.csv'
, NULL, 'I', 0, 0, 9, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
27, 'WEBERadjustmentreasons', 'alssynapseprod', 'C:\Synapse\Import\WBRadjustmentreasons'
, 'MMDDYY', 'I', 0, 0, 0, NULL, NULL, NULL, NULL, 'HHMM', 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
28, 'Weber Postal Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\PostalCodes.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
29, 'Weber Consignee Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\Consignee.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
30, 'postal clone', 'alssynapseprod', 'C:\alsSynapseTraining\Import\incoming\test.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
31, 'Weber NMFC Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\NMFC.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
32, 'Weber Item Name Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\ItemName.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
33, 'Weber Base UOM Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\Products-BaseUOM.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
34, 'Weber Item Rec Options 1 Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\IMPORT - Products-Rec-Options-1.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
35, 'Weber Item Rec Options 2 Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\IMPORT - Products-Rec-Options-2.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
36, 'Weber Item Ship Options 1', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\IMPORT - Products-Shipping-Options-1.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
37, 'Weber Item Ship Options 2', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\IMPORT - Products-Shipping-Options-2.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
38, 'Weber Item Specs Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\IMPORT - Products-Specs.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
39, 'Weber Item Storage Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\IMPORT - Products-Storage.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
40, 'Weber Item UOM Sequences Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\IMPORT - Products-UOM Sequences.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
41, 'Weber Item Validation Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\IMPORT - Products-Validation.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
42, 'Weber Item Pick Front Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\pickfronttest.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
43, 'Weber Location 2 Import', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\Location.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
44, 'Weber Item Aliases', 'alsSynapseProduction', 'C:\alsSynapseTraining\Import\tobe\Product Aliases.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
45, 'Weber Carrier Import', 'alsSynapseProduction', NULL, NULL, 'I', 0, 0, 0, NULL
, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
46, 'Weber 940 Order', 'alsSynapseTesting', 'N:\Implentantion Team\EDI MAPS\940 Incoming\'
, 'YYYYMMDD', 'I', 2, 2, 2000, NULL, NULL, NULL, NULL, 'HHMMSS', 'N', NULL);
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
47, 'Weber Country Code Import', 'alssynapseprod', 'N:\Implentantion Team\Data Ready to Upload\SALLY_ARE THESE UPLOADED YET\IMPORT - LINKS - Country Codes2.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
23, 'Weber Cust BOL Comments', 'alsSynapseProduction', 'N:\Implentantion Team\Data Ready to Upload\SALLY_ARE THESE UPLOADED YET\IMPORT - LINKS - CustItemBOLComments.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
22, 'Weber Cust Consignee Import', 'alsSynapseProduction', 'N:\Implentantion Team\Data Ready to Upload\SALLY_ARE THESE UPLOADED YET\IMPORT - LINKS - CustConsignee.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
INSERT INTO IMPEXP_DEFINITIONS ( DEFINC, NAME, TARGETALIAS, DEFFILENAME, DATEFORMAT, DEFTYPE,
FLOATDECIMALS, AMOUNTDECIMALS, LINELENGTH, AFTERPROCESSPROC, BEFOREPROCESSPROC,
AFTERPROCESSPROCPARAMS, BEFOREPROCESSPROCPARAMS, TIMEFORMAT, INCLUDECRLF,
SEPARATEFILES ) VALUES (
48, 'Weber Cust Item NMFC Import', 'alsSynapseDEV', 'N:\Implentantion Team\Data Ready to Upload\SALLY_ARE THESE UPLOADED YET\IMPORT - Links - Products NMFC.txt'
, NULL, 'I', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 'N', NULL);
commit;

