insert into systemdefaults
       (
        defaultid,
        defaultvalue,
        lastuser,
        lastupdate
       )
       values
       (
       'IMPEXP_TRADITIONAL',
       'Y',
       'SUP',
       sysdate
       );
insert into systemdefaults
       (
        defaultid,
        defaultvalue,
        lastuser,
        lastupdate
       )
       values
       (
       'IMPEXP_TABLE',
       'N',
       'SUP',
       sysdate
       );
commit;
exit;
