--
-- $Id$
--
set show off
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
7, 1, 'IN_CUSTID', NULL, 'HP');
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
7, 1, 'IN_REFERENCE', 20, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
7, 1, 'IN_CONFIRMDATE', 26, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
7, 1, 'IN_USERID', NULL, 'System');
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
10, 1, 'IN_CUSTID', NULL, 'HP');
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
10, 1, 'IN_REFERENCE', 5, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
10, 1, 'IN_CONFIRMDATE', 13, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
10, 1, 'IN_USERID', NULL, 'EXPORT');
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
2, 1, 'IN_CONFIRMDATE', 26, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
2, 1, 'IN_CUSTID', NULL, 'HP');
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
2, 1, 'IN_REFERENCE', 20, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
2, 1, 'IN_USERID', NULL, 'System');
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
3, 1, 'IN_CONFIRMDATE', 13, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
3, 1, 'IN_CUSTID', NULL, 'HP');
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
3, 1, 'IN_REFERENCE', 5, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
3, 1, 'IN_USERID', NULL, 'EXPORT');
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
11, 1, 'IN_CONFIRMDATE', 26, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
11, 1, 'IN_CUSTID', NULL, 'HP');
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
11, 1, 'IN_REFERENCE', 20, NULL);
INSERT INTO IMPEXP_AFTERPROCESSPROCPARAMS ( DEFINC, LINEINC, PARAMNAME, CHUNKINC,
DEFVALUE ) VALUES (
11, 1, 'IN_USERID', NULL, 'System');
commit;

