--
-- $Id$
--
insert into tmsarea ( code,descr,abbrev) values ('CA1','LA Basin','CA1');
insert into tmsarea ( code,descr,abbrev) values ('CA2','San Diego Area','CA2');
insert into tmsarea ( code,descr,abbrev) values ('CA3','Outlying S.Cal','CA3');
insert into tmsarea ( code,descr,abbrev) values ('CA4','Central Valley','CA4');
insert into tmsarea ( code,descr,abbrev) values ('CA5','SFO Bay Area','CA5');
insert into tmsarea ( code,descr,abbrev) values ('CA6','Outlying N.Cal','CA6');
insert into tmsarea ( code,descr,abbrev) values ('EC1','East Coast Area (DE, VA, MD, WV, NC, SC)','EC1');
insert into tmsarea ( code,descr,abbrev) values ('MT1','Mountain States (SD, ND, MT, MO, KS, NE, CO, WY, ID, UT)','MT1');
insert into tmsarea ( code,descr,abbrev) values ('MW1','Mid West Area (IL)','MW1');
insert into tmsarea ( code,descr,abbrev) values ('MW2','Mid West Area (IA, WI, MN)','MW2');
insert into tmsarea ( code,descr,abbrev) values ('NE1','NE Area (MA, RI, NH, ME, VT, CT, NJ, NY)','NE1');
insert into tmsarea ( code,descr,abbrev) values ('NE2','NE Area (PA)','NE2');
insert into tmsarea ( code,descr,abbrev) values ('PNW1','Pacific NW Area (OR)','PNW1');
insert into tmsarea ( code,descr,abbrev) values ('PNW2','Pacific NW Area (WA)','PNW2');
insert into tmsarea ( code,descr,abbrev) values ('SE1','SE Area (GA)','SE1');
insert into tmsarea ( code,descr,abbrev) values ('SE2','SE Area (FL)','SE2');
insert into tmsarea ( code,descr,abbrev) values ('SO1','S Area (AL, TN, MS, KY, OH, IN, MI, AR)','SO1');
insert into tmsarea ( code,descr,abbrev) values ('SO2','S Area (LA, OK)','SO2');
insert into tmsarea ( code,descr,abbrev) values ('TX1','Texas','TX1');
insert into tmsarea ( code,descr,abbrev) values ('WC1','Western States (AZ, NV)','WC1');
insert into tmsarea ( code,descr,abbrev) values ('WC2','Western States (NM)','WC2');
insert into tmsarea ( code,descr,abbrev) values ('HA1','Hawaii','HA1');
insert into tmsarea ( code,descr,abbrev) values ('DEF','Default Area','DEF');


insert into tmsroute ( code,descr,abbrev) values ('212','WEBER LOGISTICS - CA INTRASTATE','212');
insert into tmsroute ( code,descr,abbrev) values ('213','WEBER LOGISTICS - INTERSTATE','213');
insert into tmsroute ( code,descr,abbrev) values ('165','WEBER TRANS - LA - SDO','165');
insert into tmsroute ( code,descr,abbrev) values ('191','WEBER TRANS - SDO FLEET','191');
insert into tmsroute ( code,descr,abbrev) values ('192','WEBER - SDO CA INTRASTE','192');
insert into tmsroute ( code,descr,abbrev) values ('193','WEBER - SDO INTERSTATE','193');
insert into tmsroute ( code,descr,abbrev) values ('195','WEBER TRANS - SDO -LA','195');
insert into tmsroute ( code,descr,abbrev) values ('182','WEBER - LATHROP CA INTRASTATE','182');
insert into tmsroute ( code,descr,abbrev) values ('183','WEBER - LATHROP INTERSTATE','183');

insert into tmsstatecode ( code,descr,abbrev) values ('AK','2','AK');
insert into tmsstatecode ( code,descr,abbrev) values ('AL','2','AL');
insert into tmsstatecode ( code,descr,abbrev) values ('AR','2','AR');
insert into tmsstatecode ( code,descr,abbrev) values ('AZ','2','AZ');
insert into tmsstatecode ( code,descr,abbrev) values ('CA','4','CA');
insert into tmsstatecode ( code,descr,abbrev) values ('CO','2','CO');
insert into tmsstatecode ( code,descr,abbrev) values ('CT','2','CT');
insert into tmsstatecode ( code,descr,abbrev) values ('DC','2','DC');
insert into tmsstatecode ( code,descr,abbrev) values ('DE','2','DE');
insert into tmsstatecode ( code,descr,abbrev) values ('FL','2','FL');
insert into tmsstatecode ( code,descr,abbrev) values ('GA','2','GA');
insert into tmsstatecode ( code,descr,abbrev) values ('GU','2','GU');
insert into tmsstatecode ( code,descr,abbrev) values ('HI','2','HI');
insert into tmsstatecode ( code,descr,abbrev) values ('IA','2','IA');
insert into tmsstatecode ( code,descr,abbrev) values ('ID','2','ID');
insert into tmsstatecode ( code,descr,abbrev) values ('IL','2','IL');
insert into tmsstatecode ( code,descr,abbrev) values ('IN','2','IN');
insert into tmsstatecode ( code,descr,abbrev) values ('KS','2','KS');
insert into tmsstatecode ( code,descr,abbrev) values ('KY','2','KY');
insert into tmsstatecode ( code,descr,abbrev) values ('LA','2','LA');
insert into tmsstatecode ( code,descr,abbrev) values ('MA','2','MA');
insert into tmsstatecode ( code,descr,abbrev) values ('MD','2','MD');
insert into tmsstatecode ( code,descr,abbrev) values ('ME','2','ME');
insert into tmsstatecode ( code,descr,abbrev) values ('MI','2','MI');
insert into tmsstatecode ( code,descr,abbrev) values ('MN','2','MN');
insert into tmsstatecode ( code,descr,abbrev) values ('MO','2','MO');
insert into tmsstatecode ( code,descr,abbrev) values ('MS','2','MS');
insert into tmsstatecode ( code,descr,abbrev) values ('MT','2','MT');
insert into tmsstatecode ( code,descr,abbrev) values ('NC','2','NC');
insert into tmsstatecode ( code,descr,abbrev) values ('ND','2','ND');
insert into tmsstatecode ( code,descr,abbrev) values ('NE','2','NE');
insert into tmsstatecode ( code,descr,abbrev) values ('NH','2','NH');
insert into tmsstatecode ( code,descr,abbrev) values ('NJ','2','NJ');
insert into tmsstatecode ( code,descr,abbrev) values ('NM','2','NM');
insert into tmsstatecode ( code,descr,abbrev) values ('NV','2','NV');
insert into tmsstatecode ( code,descr,abbrev) values ('NY','2','NY');
insert into tmsstatecode ( code,descr,abbrev) values ('OH','2','OH');
insert into tmsstatecode ( code,descr,abbrev) values ('OK','2','OK');
insert into tmsstatecode ( code,descr,abbrev) values ('OR','2','OR');
insert into tmsstatecode ( code,descr,abbrev) values ('PA','2','PA');
insert into tmsstatecode ( code,descr,abbrev) values ('SC','2','SC');
insert into tmsstatecode ( code,descr,abbrev) values ('SD','2','SD');
insert into tmsstatecode ( code,descr,abbrev) values ('TN','2','TN');
insert into tmsstatecode ( code,descr,abbrev) values ('TX','2','TX');
insert into tmsstatecode ( code,descr,abbrev) values ('UT','2','UT');
insert into tmsstatecode ( code,descr,abbrev) values ('VA','2','VA');
insert into tmsstatecode ( code,descr,abbrev) values ('VT','2','VT');
insert into tmsstatecode ( code,descr,abbrev) values ('WA','2','WA');
insert into tmsstatecode ( code,descr,abbrev) values ('WI','2','WI');
insert into tmsstatecode ( code,descr,abbrev) values ('WV','2','WV');
insert into tmsstatecode ( code,descr,abbrev) values ('WY','2','WY');

insert into tmsfacilitygroup ( code,descr,abbrev) values ('SCAL','SCAL','SCAL');
insert into tmsfacilitygroup ( code,descr,abbrev) values ('SD','SD','SD');
insert into tmsfacilitygroup ( code,descr,abbrev) values ('NCAL','NCAL','NCAL');


insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','CA1','161','WDWI',1);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','CA2','165','WDWI',1);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','CA3','212','PROO',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','CA4','212','TONI',1);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','CA5','212','TONI',1);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','CA6','212','VIKN',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','EC1','213','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','MT1','213','GCMP',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','MW1','213','SERJ',4);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','MW2','213','BLLF',4);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','NE1','213','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','NE2','213','BLLF',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','PNW1','213','RETL',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','PNW2','213','BLLF',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','SE1','213','SERJ',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','SE2','213','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','SO1','213','SERJ',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','SO2','213','BLLF',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','TX1','213','DOLR',4);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','WC1','213','MTVL',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','WC2','213','DOLR',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','HA1','213','DPHE',7);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SCAL','DEF','213','DEF',0);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','DEF','213','DEF',0);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','CA1','195','WDWI',1);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','CA2','191','WDWI',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','CA3','192','PROO',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','CA4','192','TONI',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','CA5','192','TONI',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','CA6','192','VIKN',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','EC1','193','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','MT1','193','GCMP',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','MW1','193','SERJ',4);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','MW2','193','BLLF',4);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','NE1','193','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','NE2','193','BLLF',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','PNW1','193','RETL',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','PNW2','193','BLLF',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','SE1','193','SERJ',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','SE2','193','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','SO1','193','SERJ',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','SO2','193','BLLF',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','TX1','193','DOLR',4);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','WC1','193','MTVL',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','WC2','193','DOLR',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('SD','HA1','193','DPHE',7);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','CA1','182','TONI',1);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','CA2','182','TONI',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','CA3','182','PROO',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','CA4','182','TONI',1);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','CA5','182','TONI',1);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','CA6','182','VIKN',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','EC1','183','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','MT1','183','DOLR',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','MW1','183','DOLR',4);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','MW2','183','BLLF',4);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','NE1','183','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','NE2','183','BLLF',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','PNW1','183','RETL',2);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','PNW2','183','BLLF',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','SE1','183','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','SE2','183','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','SO1','183','DOLR',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','SO2','183','BLLF',6);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','TX1','183','DOLR',4);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','WC1','183','DOLR',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','WC2','183','DOLR',3);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','HA1','183','DPHE',7);
insert into tmsserviceroute( facilitygroup,area,route,defaultcarrier,servicedays) values ('NCAL','DEF','213','DEF',0);

insert into tmsservicezip (begzip,endzip,area) values ('00000','00999','DEF');
insert into tmsservicezip (begzip,endzip,area) values ('01000','14999','NE1');
insert into tmsservicezip (begzip,endzip,area) values ('15000','19699','NE2');
insert into tmsservicezip (begzip,endzip,area) values ('19700','29999','EC1');
insert into tmsservicezip (begzip,endzip,area) values ('30000','31999','SE1');
insert into tmsservicezip (begzip,endzip,area) values ('32000','34999','SE2');
insert into tmsservicezip (begzip,endzip,area) values ('35000','49999','SO1');
insert into tmsservicezip (begzip,endzip,area) values ('50000','56999','MW2');
insert into tmsservicezip (begzip,endzip,area) values ('57000','59999','MT1');
insert into tmsservicezip (begzip,endzip,area) values ('60000','62999','MW1');
insert into tmsservicezip (begzip,endzip,area) values ('63000','69999','MT1');
insert into tmsservicezip (begzip,endzip,area) values ('70000','71599','SO2');
insert into tmsservicezip (begzip,endzip,area) values ('71600','72999','SO1');
insert into tmsservicezip (begzip,endzip,area) values ('73000','74999','SO2');
insert into tmsservicezip (begzip,endzip,area) values ('75000','79999','TX1');
insert into tmsservicezip (begzip,endzip,area) values ('80000','84999','MT1');
insert into tmsservicezip (begzip,endzip,area) values ('85000','86999','WC1');
insert into tmsservicezip (begzip,endzip,area) values ('87000','88899','WC2');
insert into tmsservicezip (begzip,endzip,area) values ('88900','89999','WC1');
insert into tmsservicezip (begzip,endzip,area) values ('90000','91899','CA1');
insert into tmsservicezip (begzip,endzip,area) values ('91900','92199','CA2');
insert into tmsservicezip (begzip,endzip,area) values ('92200','92399','CA3');
insert into tmsservicezip (begzip,endzip,area) values ('92400','93099','CA1');
insert into tmsservicezip (begzip,endzip,area) values ('93100','93699','CA3');
insert into tmsservicezip (begzip,endzip,area) values ('93700','93899','CA4');
insert into tmsservicezip (begzip,endzip,area) values ('93900','93999','CA6');
insert into tmsservicezip (begzip,endzip,area) values ('94000','94899','CA5');
insert into tmsservicezip (begzip,endzip,area) values ('94900','94999','CA6');
insert into tmsservicezip (begzip,endzip,area) values ('95000','95299','CA5');
insert into tmsservicezip (begzip,endzip,area) values ('95300','95599','CA6');
insert into tmsservicezip (begzip,endzip,area) values ('95600','95699','CA5');
insert into tmsservicezip (begzip,endzip,area) values ('85700','95799','CA6');
insert into tmsservicezip (begzip,endzip,area) values ('95800','95899','CA5');
insert into tmsservicezip (begzip,endzip,area) values ('95900','96199','CA6');
insert into tmsservicezip (begzip,endzip,area) values ('96200','96999','HA1');
insert into tmsservicezip (begzip,endzip,area) values ('97000','97999','PNW1');
insert into tmsservicezip (begzip,endzip,area) values ('98000','99499','PNW2');
insert into tmsservicezip (begzip,endzip,area) values ('99500','99999','DEF');

commit;

exit;
