--
-- $Id$
--
SELECT 
    "XXPACKLISTHDR"."OH_ORDERID", "XXPACKLISTHDR"."OH_SHIPID", "XXPACKLISTHDR"."OH_ENTRYDATE", "XXPACKLISTHDR"."OH_REFERENCE",
"XXPACKLISTHDR"."CN_NAME", "XXPACKLISTHDR"."CN_ADDR1", "XXPACKLISTHDR"."CN_ADDR2", "XXPACKLISTHDR"."CN_CITY", 
"XXPACKLISTHDR"."CN_STATE", "XXPACKLISTHDR"."CN_POSTALCODE", "XXPACKLISTHDR"."CN_PHONE", 
"XXPACKLISTHDR"."OH_TAX", "XXPACKLISTHDR"."OH_SHIPPING", 
"XXPACKLISTHDR"."OH_TOTAL", "XXPACKLISTHDR"."OH_HDRPASSTHRUCHAR15", "XXPACKLISTHDR"."OH_HDRPASSTHRUCHAR16", 
"XXPACKLISTHDR"."OH_HDRPASSTHRUCHAR17", "XXPACKLISTHDR"."OH_HDRPASSTHRUCHAR18", 
"XXPACKLISTHDR"."OH_HDRPASSTHRUCHAR19", "XXPACKLISTHDR"."OH_LASTPICKLABEL", 
"XXPACKLISTHDR"."OH_PACKLISTSHIPDATE", "XXPACKLISTHDR"."MC_DELSERVICEDESCR", 
"XXPACKLIST_ORDER_LINE"."ORDERID", "XXPACKLIST_ORDER_LINE"."SHIPID", 
"XXPACKLIST_ORDER_LINE"."LINENUMBER", "XXPACKLIST_ORDER_LINE"."ORDERITEM", 
"XXPACKLIST_ORDER_LINE"."DESCRIPTION", "XXPACKLIST_ORDER_LINE"."QUANTITY", 
"XXPACKLIST_ORDER_LINE"."UNITOFMEASURE", "XXPACKLIST_ORDER_LINE"."UNITAMOUNT", 
"XXPACKLIST_ORDER_LINE_ITEMS"."SERIALNUMBER", "XXPACKLIST_ORDER_LINE_ITEMS"."TRACKINGNO"
FROM
    "ALPS"."XXPACKLISTHDR" "XXPACKLISTHDR",
    "ALPS"."XXPACKLIST_ORDER_LINE" "XXPACKLIST_ORDER_LINE",
    "ALPS"."XXPACKLIST_ORDER_LINE_ITEMS" "XXPACKLIST_ORDER_LINE_ITEMS"
WHERE
    "XXPACKLISTHDR"."OH_ORDERID" = "XXPACKLIST_ORDER_LINE"."ORDERID" AND
    "XXPACKLISTHDR"."OH_SHIPID" = "XXPACKLIST_ORDER_LINE"."SHIPID" AND
    "XXPACKLIST_ORDER_LINE"."ORDERID" = "XXPACKLIST_ORDER_LINE_ITEMS"."ORDERID"(+) AND
    "XXPACKLIST_ORDER_LINE"."SHIPID" = "XXPACKLIST_ORDER_LINE_ITEMS"."SHIPID"(+) AND
    "XXPACKLIST_ORDER_LINE"."ORDERITEM" = "XXPACKLIST_ORDER_LINE_ITEMS"."ORDERITEM"(+) AND
    "XXPACKLIST_ORDER_LINE"."ORDERLOTNUMBER" = "XXPACKLIST_ORDER_LINE_ITEMS"."ORDERLOT"(+) AND
    "XXPACKLISTHDR"."OH_ORDERID" = 1093 AND
    "XXPACKLISTHDR"."OH_SHIPID" = 1
ORDER BY
    "XXPACKLIST_ORDER_LINE"."LINENUMBER" ASC
