#!/bin/bash

SYN_TABLES="APPMSGS ASOFINVENTORY ASOFINVENTORYDTL AUDIT_TABLE \
BATCHTASKHISTORY BILLPALLETCNT \
CASELABELS CONSIGNEE \
DELETEDPLATE \
INVOICEHDR INVOICEDTL \
LOADS LOADSTOP LOADSTOPSHIP \
MULTISHIPHDR MULTISHIPDTL \
ORDERHDR ORDERDTL ORDERDTLLINE ORDERDTLRCPT ORDERHISTORY \
PALLETHISTORY PLATE PLATEHISTORY \
SUBTASKHISTORY SHIPPINGPLATE \
TASKHISTORY \
UCC_STANDARD_LABELS \
WAVES WEBER_CASE_LABELS WEBER_PALLET_LABELS WORLDSHIPDTL \
USERHISTORY"

for SYN_TABLE in ${SYN_TABLES};
do
  sql @${SYN_HOME}/db/sql/switch_index_tablespace $SYN_TABLE y
done;
