CREATE OR REPLACE TRIGGER ALPS.CUSTITEM_SARA_MOD_UPD
AFTER UPDATE
ON ALPS.CUSTITEM_SARA
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
ms number(10);
mti date;
mty char(1);
mg varchar2(255);
o CUSTITEM_SARA%rowtype;
n CUSTITEM_SARA%rowtype;

/******************************************************************************
   NAME:       
   PURPOSE:    

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        8/24/2018      MikeLeslie-LT       1. Created this trigger.

   NOTES:

   Automatically available Auto Replace Keywords:
      Object Name:     
      Sysdate:         8/24/2018
      Date and Time:   8/24/2018, 9:52:43 AM, and 8/24/2018 9:52:43 AM
      Username:        MikeLeslie-LT (set in TOAD Options, Proc Templates)
      Table Name:      CUSTITEM_SARA (set in the "New PL/SQL Object" dialog)
      Trigger Options:  (set in the "New PL/SQL Object" dialog)
******************************************************************************/
BEGIN
mti := sysdate;

if nvl(:old.SARA_CUSTID,'x') = nvl(:new.SARA_CUSTID,'x')
and nvl(:old.SARA_ITEM,'x') = nvl(:new.SARA_ITEM,'x')
and nvl(:old.SARA_PH_EXPLOSIVE,'x') = nvl(:new.SARA_PH_EXPLOSIVE,'x')
and nvl(:old.SARA_PH_FLAMABLE,'x') = nvl(:new.SARA_PH_FLAMABLE,'x')
and nvl(:old.SARA_PH_OXIDIZER,'x') = nvl(:new.SARA_PH_OXIDIZER,'x')
and nvl(:old.SARA_PH_SELF_REACTIVE,'x') = nvl(:new.SARA_PH_SELF_REACTIVE,'x')
and nvl(:old.SARA_PH_PYROPH_LIQ_SOLID,'x') = nvl(:new.SARA_PH_PYROPH_LIQ_SOLID,'x')
and nvl(:old.SARA_PH_PYROPHORIC_GAS,'x') = nvl(:new.SARA_PH_PYROPHORIC_GAS,'x')
and nvl(:old.SARA_PH_SELF_HEATING,'x') = nvl(:new.SARA_PH_SELF_HEATING,'x')
and nvl(:old.SARA_PH_ORGANIC_PEROXIDE,'x') = nvl(:new.SARA_PH_ORGANIC_PEROXIDE,'x')
and nvl(:old.SARA_PH_CORROSIVE_TO_METAL,'x') = nvl(:new.SARA_PH_CORROSIVE_TO_METAL,'x')
and nvl(:old.SARA_PH_GAS_UNDER_PRESS_COMP,'x') = nvl(:new.SARA_PH_GAS_UNDER_PRESS_COMP,'x')
and nvl(:old.SARA_PH_WTR_CONT_EMIT_FLAM_GAS,'x') = nvl(:new.SARA_PH_WTR_CONT_EMIT_FLAM_GAS,'x')
and nvl(:old.SARA_PH_COMBUSTIBLE_DUST,'x') = nvl(:new.SARA_PH_COMBUSTIBLE_DUST,'x')
and nvl(:old.SARA_PH_HAZ_NOT_OTHRWISE_CLASS,'x') = nvl(:new.SARA_PH_HAZ_NOT_OTHRWISE_CLASS,'x')
and nvl(:old.SARA_HH_ACUTE_TOXICITY,0) = nvl(:new.SARA_HH_ACUTE_TOXICITY,0)
and nvl(:old.SARA_HH_SKIN_CORROS_OR_IRRITA,0) = nvl(:new.SARA_HH_SKIN_CORROS_OR_IRRITA,0)
and nvl(:old.SARA_HH_SERI_EYE_DAM_OR_IRRIT,0) = nvl(:new.SARA_HH_SERI_EYE_DAM_OR_IRRIT,0)
and nvl(:old.SARA_HH_RESPIR_OR_SKIN_SENSI,0) = nvl(:new.SARA_HH_RESPIR_OR_SKIN_SENSI,0)
and nvl(:old.SARA_HH_GERM_CELL_MUTAGENICITY,0) = nvl(:new.SARA_HH_GERM_CELL_MUTAGENICITY,0)
and nvl(:old.SARA_HH_CARCINOGENICITY,0) = nvl(:new.SARA_HH_CARCINOGENICITY,0)
and nvl(:old.SARA_HH_REPRODUCTIVE_TOXICITY,'x') = nvl(:new.SARA_HH_REPRODUCTIVE_TOXICITY,'x')
and nvl(:old.SARA_HH_SPECIFIC_TARG_ORG_TOXI,0) = nvl(:new.SARA_HH_SPECIFIC_TARG_ORG_TOXI,0)
and nvl(:old.SARA_HH_ASPIRATION_HAZARD,'x') = nvl(:new.SARA_HH_ASPIRATION_HAZARD,'x')
and nvl(:old.SARA_HH_SIMPLE_ASPHYXIANT,'x') = nvl(:new.SARA_HH_SIMPLE_ASPHYXIANT,'x')
and nvl(:old.SARA_HH_HAZARD_NOT_CLASSIFIED,'x') = nvl(:new.SARA_HH_HAZARD_NOT_CLASSIFIED,'x')
then
  return;
end if;

o := null;
n := null;
zaud.get_next_modseq('CUSTITEM_SARA_OLD','CUSTITEM_SARA_NEW',ms,mg);
 mty := 'U';
o.SARA_ITEM := :old.SARA_ITEM;
n.SARA_ITEM := :new.SARA_ITEM;
o.LASTUSER := :old.LASTUSER;
n.LASTUSER := :new.LASTUSER;
o.LASTUPDATE := :old.LASTUPDATE;
n.LASTUPDATE := :new.LASTUPDATE;

if nvl(:old.SARA_CUSTID,'x') != nvl(:new.SARA_CUSTID,'x') then
o.SARA_CUSTID := :old.SARA_CUSTID;
n.SARA_CUSTID := :new.SARA_CUSTID;
end if;
if nvl(:old.SARA_PH_EXPLOSIVE,'x') != nvl(:new.SARA_PH_EXPLOSIVE,'x') then
o.SARA_PH_EXPLOSIVE := :old.SARA_PH_EXPLOSIVE;
n.SARA_PH_EXPLOSIVE := :new.SARA_PH_EXPLOSIVE;
end if;
if nvl(:old.SARA_PH_FLAMABLE,'x') != nvl(:new.SARA_PH_FLAMABLE,'x') then
o.SARA_PH_FLAMABLE := :old.SARA_PH_FLAMABLE;
n.SARA_PH_FLAMABLE := :new.SARA_PH_FLAMABLE;
end if;
if nvl(:old.SARA_PH_OXIDIZER,'x') != nvl(:new.SARA_PH_OXIDIZER,'x') then
o.SARA_PH_OXIDIZER := :old.SARA_PH_OXIDIZER;
n.SARA_PH_OXIDIZER := :new.SARA_PH_OXIDIZER;
end if;
if nvl(:old.SARA_PH_SELF_REACTIVE,'x') != nvl(:new.SARA_PH_SELF_REACTIVE,'x') then
o.SARA_PH_SELF_REACTIVE := :old.SARA_PH_SELF_REACTIVE;
n.SARA_PH_SELF_REACTIVE := :new.SARA_PH_SELF_REACTIVE;
end if;
if nvl(:old.SARA_PH_PYROPH_LIQ_SOLID,'x') != nvl(:new.SARA_PH_PYROPH_LIQ_SOLID,'x') then
o.SARA_PH_PYROPH_LIQ_SOLID := :old.SARA_PH_PYROPH_LIQ_SOLID;
n.SARA_PH_PYROPH_LIQ_SOLID := :new.SARA_PH_PYROPH_LIQ_SOLID;
end if;
if nvl(:old.SARA_PH_PYROPHORIC_GAS,'x') != nvl(:new.SARA_PH_PYROPHORIC_GAS,'x') then
o.SARA_PH_PYROPHORIC_GAS := :old.SARA_PH_PYROPHORIC_GAS;
n.SARA_PH_PYROPHORIC_GAS := :new.SARA_PH_PYROPHORIC_GAS;
end if;
if nvl(:old.SARA_PH_SELF_HEATING,'x') != nvl(:new.SARA_PH_SELF_HEATING,'x') then
o.SARA_PH_SELF_HEATING := :old.SARA_PH_SELF_HEATING;
n.SARA_PH_SELF_HEATING := :new.SARA_PH_SELF_HEATING;
end if;
if nvl(:old.SARA_PH_ORGANIC_PEROXIDE,'x') != nvl(:new.SARA_PH_ORGANIC_PEROXIDE,'x') then
o.SARA_PH_ORGANIC_PEROXIDE := :old.SARA_PH_ORGANIC_PEROXIDE;
n.SARA_PH_ORGANIC_PEROXIDE := :new.SARA_PH_ORGANIC_PEROXIDE;
end if;
if nvl(:old.SARA_PH_CORROSIVE_TO_METAL,'x') != nvl(:new.SARA_PH_CORROSIVE_TO_METAL,'x') then
o.SARA_PH_CORROSIVE_TO_METAL := :old.SARA_PH_CORROSIVE_TO_METAL;
n.SARA_PH_CORROSIVE_TO_METAL := :new.SARA_PH_CORROSIVE_TO_METAL;
end if;
if nvl(:old.SARA_PH_GAS_UNDER_PRESS_COMP,'x') != nvl(:new.SARA_PH_GAS_UNDER_PRESS_COMP,'x') then
o.SARA_PH_GAS_UNDER_PRESS_COMP := :old.SARA_PH_GAS_UNDER_PRESS_COMP;
n.SARA_PH_GAS_UNDER_PRESS_COMP := :new.SARA_PH_GAS_UNDER_PRESS_COMP;
end if;
if nvl(:old.SARA_PH_WTR_CONT_EMIT_FLAM_GAS,'x') != nvl(:new.SARA_PH_WTR_CONT_EMIT_FLAM_GAS,'x') then
o.SARA_PH_WTR_CONT_EMIT_FLAM_GAS := :old.SARA_PH_WTR_CONT_EMIT_FLAM_GAS;
n.SARA_PH_WTR_CONT_EMIT_FLAM_GAS := :new.SARA_PH_WTR_CONT_EMIT_FLAM_GAS;
end if;
if nvl(:old.SARA_PH_COMBUSTIBLE_DUST,'x') != nvl(:new.SARA_PH_COMBUSTIBLE_DUST,'x') then
o.SARA_PH_COMBUSTIBLE_DUST := :old.SARA_PH_COMBUSTIBLE_DUST;
n.SARA_PH_COMBUSTIBLE_DUST := :new.SARA_PH_COMBUSTIBLE_DUST;
end if;
if nvl(:old.SARA_PH_HAZ_NOT_OTHRWISE_CLASS,'x') != nvl(:new.SARA_PH_HAZ_NOT_OTHRWISE_CLASS,'x') then
o.SARA_PH_HAZ_NOT_OTHRWISE_CLASS := :old.SARA_PH_HAZ_NOT_OTHRWISE_CLASS;
n.SARA_PH_HAZ_NOT_OTHRWISE_CLASS := :new.SARA_PH_HAZ_NOT_OTHRWISE_CLASS;
end if;
if nvl(:old.SARA_HH_ACUTE_TOXICITY,0) != nvl(:new.SARA_HH_ACUTE_TOXICITY,0) then
o.SARA_HH_ACUTE_TOXICITY := :old.SARA_HH_ACUTE_TOXICITY;
n.SARA_HH_ACUTE_TOXICITY := :new.SARA_HH_ACUTE_TOXICITY;
end if;
if nvl(:old.SARA_HH_SKIN_CORROS_OR_IRRITA,0) != nvl(:new.SARA_HH_SKIN_CORROS_OR_IRRITA,0) then
o.SARA_HH_SKIN_CORROS_OR_IRRITA := :old.SARA_HH_SKIN_CORROS_OR_IRRITA;
n.SARA_HH_SKIN_CORROS_OR_IRRITA := :new.SARA_HH_SKIN_CORROS_OR_IRRITA;
end if;
if nvl(:old.SARA_HH_SERI_EYE_DAM_OR_IRRIT,0) != nvl(:new.SARA_HH_SERI_EYE_DAM_OR_IRRIT,0) then
o.SARA_HH_SERI_EYE_DAM_OR_IRRIT := :old.SARA_HH_SERI_EYE_DAM_OR_IRRIT;
n.SARA_HH_SERI_EYE_DAM_OR_IRRIT := :new.SARA_HH_SERI_EYE_DAM_OR_IRRIT;
end if;
if nvl(:old.SARA_HH_RESPIR_OR_SKIN_SENSI,0) != nvl(:new.SARA_HH_RESPIR_OR_SKIN_SENSI,0) then
o.SARA_HH_RESPIR_OR_SKIN_SENSI := :old.SARA_HH_RESPIR_OR_SKIN_SENSI;
n.SARA_HH_RESPIR_OR_SKIN_SENSI := :new.SARA_HH_RESPIR_OR_SKIN_SENSI;
end if;
if nvl(:old.SARA_HH_GERM_CELL_MUTAGENICITY,0) != nvl(:new.SARA_HH_GERM_CELL_MUTAGENICITY,0) then
o.SARA_HH_GERM_CELL_MUTAGENICITY := :old.SARA_HH_GERM_CELL_MUTAGENICITY;
n.SARA_HH_GERM_CELL_MUTAGENICITY := :new.SARA_HH_GERM_CELL_MUTAGENICITY;
end if;
if nvl(:old.SARA_HH_CARCINOGENICITY,0) != nvl(:new.SARA_HH_CARCINOGENICITY,0) then
o.SARA_HH_CARCINOGENICITY := :old.SARA_HH_CARCINOGENICITY;
n.SARA_HH_CARCINOGENICITY := :new.SARA_HH_CARCINOGENICITY;
end if;
n.SARA_CUSTID := :new.SARA_CUSTID;
o.SARA_CUSTID := :old.SARA_CUSTID;
if nvl(:old.SARA_HH_REPRODUCTIVE_TOXICITY,0) != nvl(:new.SARA_HH_REPRODUCTIVE_TOXICITY,0) then
o.SARA_HH_REPRODUCTIVE_TOXICITY := :old.SARA_HH_REPRODUCTIVE_TOXICITY;
n.SARA_HH_REPRODUCTIVE_TOXICITY := :new.SARA_HH_REPRODUCTIVE_TOXICITY;
end if;
if nvl(:old.SARA_HH_SPECIFIC_TARG_ORG_TOXI,'x') != nvl(:new.SARA_HH_SPECIFIC_TARG_ORG_TOXI,'x') then
o.SARA_HH_SPECIFIC_TARG_ORG_TOXI := :old.SARA_HH_SPECIFIC_TARG_ORG_TOXI;
n.SARA_HH_SPECIFIC_TARG_ORG_TOXI := :new.SARA_HH_SPECIFIC_TARG_ORG_TOXI;
end if;
if nvl(:old.SARA_HH_ASPIRATION_HAZARD,'x') != nvl(:new.SARA_HH_ASPIRATION_HAZARD,'x') then
o.SARA_HH_ASPIRATION_HAZARD := :old.SARA_HH_ASPIRATION_HAZARD;
n.SARA_HH_ASPIRATION_HAZARD := :new.SARA_HH_ASPIRATION_HAZARD;
end if;
if nvl(:old.SARA_HH_SIMPLE_ASPHYXIANT,'x') != nvl(:new.SARA_HH_SIMPLE_ASPHYXIANT,'x') then
o.SARA_HH_SIMPLE_ASPHYXIANT := :old.SARA_HH_SIMPLE_ASPHYXIANT;
n.SARA_HH_SIMPLE_ASPHYXIANT := :new.SARA_HH_SIMPLE_ASPHYXIANT;
end if;
if nvl(:old.SARA_HH_HAZARD_NOT_CLASSIFIED,mti) != nvl(:new.SARA_HH_HAZARD_NOT_CLASSIFIED,mti) then
o.SARA_HH_HAZARD_NOT_CLASSIFIED := :old.SARA_HH_HAZARD_NOT_CLASSIFIED;
n.SARA_HH_HAZARD_NOT_CLASSIFIED := :new.SARA_HH_HAZARD_NOT_CLASSIFIED;
end if;
insert into CUSTITEM_SARA_OLD
(MOD_SEQ,MOD_TABLE_NAME,MOD_TYPE,MOD_TIME
,SARA_CUSTID
,SARA_ITEM
,SARA_PH_EXPLOSIVE
,SARA_PH_FLAMABLE
,SARA_PH_OXIDIZER
,SARA_PH_SELF_REACTIVE
,SARA_PH_PYROPH_LIQ_SOLID
,SARA_PH_PYROPHORIC_GAS
,SARA_PH_SELF_HEATING
,SARA_PH_ORGANIC_PEROXIDE
,SARA_PH_CORROSIVE_TO_METAL
,SARA_PH_GAS_UNDER_PRESS_COMP
,SARA_PH_WTR_CONT_EMIT_FLAM_GAS
,SARA_PH_COMBUSTIBLE_DUST
,SARA_PH_HAZ_NOT_OTHRWISE_CLASS
,SARA_HH_ACUTE_TOXICITY
,SARA_HH_SKIN_CORROS_OR_IRRITA
,SARA_HH_SERI_EYE_DAM_OR_IRRIT
,SARA_HH_RESPIR_OR_SKIN_SENSI
,SARA_HH_GERM_CELL_MUTAGENICITY
,SARA_HH_CARCINOGENICITY
,SARA_HH_REPRODUCTIVE_TOXICITY
,SARA_HH_SPECIFIC_TARG_ORG_TOXI
,SARA_HH_ASPIRATION_HAZARD
,SARA_HH_SIMPLE_ASPHYXIANT
,SARA_HH_HAZARD_NOT_CLASSIFIED
,LASTUSER
,LASTUPDATE
) values
(ms,'CUSTITEM_SARA',mty,mti
,o.SARA_CUSTID
,o.SARA_ITEM
,o.SARA_PH_EXPLOSIVE
,o.SARA_PH_FLAMABLE
,o.SARA_PH_OXIDIZER
,o.SARA_PH_SELF_REACTIVE
,o.SARA_PH_PYROPH_LIQ_SOLID
,o.SARA_PH_PYROPHORIC_GAS
,o.SARA_PH_SELF_HEATING
,o.SARA_PH_ORGANIC_PEROXIDE
,o.SARA_PH_CORROSIVE_TO_METAL
,o.SARA_PH_GAS_UNDER_PRESS_COMP
,o.SARA_PH_WTR_CONT_EMIT_FLAM_GAS
,o.SARA_PH_COMBUSTIBLE_DUST
,o.SARA_PH_HAZ_NOT_OTHRWISE_CLASS
,o.SARA_HH_ACUTE_TOXICITY
,o.SARA_HH_SKIN_CORROS_OR_IRRITA
,o.SARA_HH_SERI_EYE_DAM_OR_IRRIT
,o.SARA_HH_RESPIR_OR_SKIN_SENSI
,o.SARA_HH_GERM_CELL_MUTAGENICITY
,o.SARA_HH_CARCINOGENICITY
,o.SARA_HH_REPRODUCTIVE_TOXICITY
,o.SARA_HH_SPECIFIC_TARG_ORG_TOXI
,o.SARA_HH_ASPIRATION_HAZARD
,o.SARA_HH_SIMPLE_ASPHYXIANT
,o.SARA_HH_HAZARD_NOT_CLASSIFIED
,o.LASTUSER
,o.LASTUPDATE
);
insert into CUSTITEM_SARA_NEW
(MOD_SEQ,MOD_TABLE_NAME,MOD_TYPE,MOD_TIME
,SARA_CUSTID
,SARA_ITEM
,SARA_PH_EXPLOSIVE
,SARA_PH_FLAMABLE
,SARA_PH_OXIDIZER
,SARA_PH_SELF_REACTIVE
,SARA_PH_PYROPH_LIQ_SOLID
,SARA_PH_PYROPHORIC_GAS
,SARA_PH_SELF_HEATING
,SARA_PH_ORGANIC_PEROXIDE
,SARA_PH_CORROSIVE_TO_METAL
,SARA_PH_GAS_UNDER_PRESS_COMP
,SARA_PH_WTR_CONT_EMIT_FLAM_GAS
,SARA_PH_COMBUSTIBLE_DUST
,SARA_PH_HAZ_NOT_OTHRWISE_CLASS
,SARA_HH_ACUTE_TOXICITY
,SARA_HH_SKIN_CORROS_OR_IRRITA
,SARA_HH_SERI_EYE_DAM_OR_IRRIT
,SARA_HH_RESPIR_OR_SKIN_SENSI
,SARA_HH_GERM_CELL_MUTAGENICITY
,SARA_HH_CARCINOGENICITY
,SARA_HH_REPRODUCTIVE_TOXICITY
,SARA_HH_SPECIFIC_TARG_ORG_TOXI
,SARA_HH_ASPIRATION_HAZARD
,SARA_HH_SIMPLE_ASPHYXIANT
,SARA_HH_HAZARD_NOT_CLASSIFIED
,LASTUSER
,LASTUPDATE
) values
(ms,'CUSTITEM_SARA',mty,mti
,n.SARA_CUSTID
,n.SARA_ITEM
,n.SARA_PH_EXPLOSIVE
,n.SARA_PH_FLAMABLE
,n.SARA_PH_OXIDIZER
,n.SARA_PH_SELF_REACTIVE
,n.SARA_PH_PYROPH_LIQ_SOLID
,n.SARA_PH_PYROPHORIC_GAS
,n.SARA_PH_SELF_HEATING
,n.SARA_PH_ORGANIC_PEROXIDE
,n.SARA_PH_CORROSIVE_TO_METAL
,n.SARA_PH_GAS_UNDER_PRESS_COMP
,n.SARA_PH_WTR_CONT_EMIT_FLAM_GAS
,n.SARA_PH_COMBUSTIBLE_DUST
,n.SARA_PH_HAZ_NOT_OTHRWISE_CLASS
,n.SARA_HH_ACUTE_TOXICITY
,n.SARA_HH_SKIN_CORROS_OR_IRRITA
,n.SARA_HH_SERI_EYE_DAM_OR_IRRIT
,n.SARA_HH_RESPIR_OR_SKIN_SENSI
,n.SARA_HH_GERM_CELL_MUTAGENICITY
,n.SARA_HH_CARCINOGENICITY
,n.SARA_HH_REPRODUCTIVE_TOXICITY
,n.SARA_HH_SPECIFIC_TARG_ORG_TOXI
,n.SARA_HH_ASPIRATION_HAZARD
,n.SARA_HH_SIMPLE_ASPHYXIANT
,n.SARA_HH_HAZARD_NOT_CLASSIFIED
,n.LASTUSER
,n.LASTUPDATE
);
END ;
/

CREATE OR REPLACE TRIGGER ALPS.CUSTITEM_SARA_MOD_DEL
AFTER DELETE
ON ALPS.CUSTITEM_SARA
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
ms number(10);
mti date;
mty char(1);
mg varchar2(255);
o CUSTITEM_SARA%rowtype;

/******************************************************************************
   NAME:       CUSTITEM_SARA_MOD_DEL
   PURPOSE:    

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        8/23/2018      MikeLeslie-LT       1. Created this trigger.

   NOTES:

   Automatically available Auto Replace Keywords:
      Object Name:     CUSTITEM_SARA_MOD_DEL
      Sysdate:         8/23/2018
      Date and Time:   8/23/2018, 12:37:10 PM, and 8/23/2018 12:37:10 PM
      Username:        MikeLeslie-LT (set in TOAD Options, Proc Templates)
      Table Name:      CUSTITEM_SARA (set in the "New PL/SQL Object" dialog)
      Trigger Options:  (set in the "New PL/SQL Object" dialog)
******************************************************************************/
BEGIN
mti := sysdate;

zaud.get_next_modseq('CUSTITEM_SARA_OLD','CUSTITEM_SARA_NEW',ms,mg);
 mty := 'D';

insert into CUSTITEM_SARA_OLD
(MOD_SEQ,MOD_TABLE_NAME,MOD_TYPE,MOD_TIME
,SARA_CUSTID
,SARA_ITEM
,SARA_PH_EXPLOSIVE
,SARA_PH_FLAMABLE
,SARA_PH_OXIDIZER
,SARA_PH_SELF_REACTIVE
,SARA_PH_PYROPH_LIQ_SOLID
,SARA_PH_PYROPHORIC_GAS
,SARA_PH_SELF_HEATING
,SARA_PH_ORGANIC_PEROXIDE
,SARA_PH_CORROSIVE_TO_METAL
,SARA_PH_GAS_UNDER_PRESS_COMP
,SARA_PH_WTR_CONT_EMIT_FLAM_GAS
,SARA_PH_COMBUSTIBLE_DUST
,SARA_PH_HAZ_NOT_OTHRWISE_CLASS
,SARA_HH_ACUTE_TOXICITY
,SARA_HH_SKIN_CORROS_OR_IRRITA
,SARA_HH_SERI_EYE_DAM_OR_IRRIT
,SARA_HH_RESPIR_OR_SKIN_SENSI
,SARA_HH_GERM_CELL_MUTAGENICITY
,SARA_HH_CARCINOGENICITY
,SARA_HH_REPRODUCTIVE_TOXICITY
,SARA_HH_SPECIFIC_TARG_ORG_TOXI
,SARA_HH_ASPIRATION_HAZARD
,SARA_HH_SIMPLE_ASPHYXIANT
,SARA_HH_HAZARD_NOT_CLASSIFIED
,LASTUSER
,LASTUPDATE
) values
(ms,'CUSTITEM_SARA',mty,mti
,:old.SARA_CUSTID
,:old.SARA_ITEM
,:old.SARA_PH_EXPLOSIVE
,:old.SARA_PH_FLAMABLE
,:old.SARA_PH_OXIDIZER
,:old.SARA_PH_SELF_REACTIVE
,:old.SARA_PH_PYROPH_LIQ_SOLID
,:old.SARA_PH_PYROPHORIC_GAS
,:old.SARA_PH_SELF_HEATING
,:old.SARA_PH_ORGANIC_PEROXIDE
,:old.SARA_PH_CORROSIVE_TO_METAL
,:old.SARA_PH_GAS_UNDER_PRESS_COMP
,:old.SARA_PH_WTR_CONT_EMIT_FLAM_GAS
,:old.SARA_PH_COMBUSTIBLE_DUST
,:old.SARA_PH_HAZ_NOT_OTHRWISE_CLASS
,:old.SARA_HH_ACUTE_TOXICITY
,:old.SARA_HH_SKIN_CORROS_OR_IRRITA
,:old.SARA_HH_SERI_EYE_DAM_OR_IRRIT
,:old.SARA_HH_RESPIR_OR_SKIN_SENSI
,:old.SARA_HH_GERM_CELL_MUTAGENICITY
,:old.SARA_HH_CARCINOGENICITY
,:old.SARA_HH_REPRODUCTIVE_TOXICITY
,:old.SARA_HH_SPECIFIC_TARG_ORG_TOXI
,:old.SARA_HH_ASPIRATION_HAZARD
,:old.SARA_HH_SIMPLE_ASPHYXIANT
,:old.SARA_HH_HAZARD_NOT_CLASSIFIED
,:old.LASTUSER
,:old.LASTUPDATE
);

END CUSTITEM_SARA_MOD_DEL;
/

CREATE OR REPLACE TRIGGER ALPS.CUSTITEM_SARA_MOD_INS
AFTER INSERT
ON ALPS.CUSTITEM_SARA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
ms number(10);
mti date;
mty char(1);
mg varchar2(255);
/******************************************************************************
   NAME:       
   PURPOSE:    

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        8/23/2018      MikeLeslie-LT       1. Created this trigger.

   NOTES:

   Automatically available Auto Replace Keywords:
      Object Name:     
      Sysdate:         8/23/2018
      Date and Time:   8/23/2018, 1:21:07 PM, and 8/23/2018 1:21:07 PM
      Username:        MikeLeslie-LT (set in TOAD Options, Proc Templates)
      Table Name:      CUSTITEM_SARA (set in the "New PL/SQL Object" dialog)
      Trigger Options:  (set in the "New PL/SQL Object" dialog)
******************************************************************************/

begin

mti := sysdate;

zaud.get_next_modseq('CUSTITEM_SARA_OLD','CUSTITEM_SARA_NEW',ms,mg);
 mty := 'I';

insert into CUSTITEM_SARA_NEW
(MOD_SEQ,MOD_TABLE_NAME,MOD_TYPE,MOD_TIME
,SARA_CUSTID
,SARA_ITEM
,SARA_PH_EXPLOSIVE
,SARA_PH_FLAMABLE
,SARA_PH_OXIDIZER
,SARA_PH_SELF_REACTIVE
,SARA_PH_PYROPH_LIQ_SOLID
,SARA_PH_PYROPHORIC_GAS
,SARA_PH_SELF_HEATING
,SARA_PH_ORGANIC_PEROXIDE
,SARA_PH_CORROSIVE_TO_METAL
,SARA_PH_GAS_UNDER_PRESS_COMP
,SARA_PH_WTR_CONT_EMIT_FLAM_GAS
,SARA_PH_COMBUSTIBLE_DUST
,SARA_PH_HAZ_NOT_OTHRWISE_CLASS
,SARA_HH_ACUTE_TOXICITY
,SARA_HH_SKIN_CORROS_OR_IRRITA
,SARA_HH_SERI_EYE_DAM_OR_IRRIT
,SARA_HH_RESPIR_OR_SKIN_SENSI
,SARA_HH_GERM_CELL_MUTAGENICITY
,SARA_HH_CARCINOGENICITY
,SARA_HH_REPRODUCTIVE_TOXICITY
,SARA_HH_SPECIFIC_TARG_ORG_TOXI
,SARA_HH_ASPIRATION_HAZARD
,SARA_HH_SIMPLE_ASPHYXIANT
,SARA_HH_HAZARD_NOT_CLASSIFIED
,LASTUSER
,LASTUPDATE
) values
(ms,'CUSTITEM_SARA',mty,mti
,:new.SARA_CUSTID
,:new.SARA_ITEM
,:new.SARA_PH_EXPLOSIVE
,:new.SARA_PH_FLAMABLE
,:new.SARA_PH_OXIDIZER
,:new.SARA_PH_SELF_REACTIVE
,:new.SARA_PH_PYROPH_LIQ_SOLID
,:new.SARA_PH_PYROPHORIC_GAS
,:new.SARA_PH_SELF_HEATING
,:new.SARA_PH_ORGANIC_PEROXIDE
,:new.SARA_PH_CORROSIVE_TO_METAL
,:new.SARA_PH_GAS_UNDER_PRESS_COMP
,:new.SARA_PH_WTR_CONT_EMIT_FLAM_GAS
,:new.SARA_PH_COMBUSTIBLE_DUST
,:new.SARA_PH_HAZ_NOT_OTHRWISE_CLASS
,:new.SARA_HH_ACUTE_TOXICITY
,:new.SARA_HH_SKIN_CORROS_OR_IRRITA
,:new.SARA_HH_SERI_EYE_DAM_OR_IRRIT
,:new.SARA_HH_RESPIR_OR_SKIN_SENSI
,:new.SARA_HH_GERM_CELL_MUTAGENICITY
,:new.SARA_HH_CARCINOGENICITY
,:new.SARA_HH_REPRODUCTIVE_TOXICITY
,:new.SARA_HH_SPECIFIC_TARG_ORG_TOXI
,:new.SARA_HH_ASPIRATION_HAZARD
,:new.SARA_HH_SIMPLE_ASPHYXIANT
,:new.SARA_HH_HAZARD_NOT_CLASSIFIED
,:new.LASTUSER
,:new.LASTUPDATE
);
END ;
/